### ISSUE TITLE
ConcurrentModificationException in DefaultKeyedChannelPool.doClose()

### ISSUE THREAD

**Issue by trustin** [line/armeria#1022]
```
Exception in thread "Thread-2" java.util.ConcurrentModificationException 
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) 
at java.util.HashMap$KeyIterator.next(HashMap.java:1461) 
at com.linecorp.armeria.client.pool.DefaultKeyedChannelPool.doClose(DefaultKeyedChannelPool.java:326) 
at com.linecorp.armeria.client.pool.DefaultKeyedChannelPool.lambda$close$6(DefaultKeyedChannelPool.java:313)
...
```

**Comment by anuraaga** [comment]
I can only see this happening if one of these futures isn't on the event loop. Do you think it's possible?

https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/client/pool/DefaultKeyedChannelPool.java#L128

https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/client/pool/DefaultKeyedChannelPool.java#L198

**Comment by trustin** [comment]
@mauhiz Could you elaborate on how this happened?

**Comment by rfkm** [comment]
I encountered the same issue after upgrading Armeria from 0.55.1 to 0.58.1:

```
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
        at com.linecorp.armeria.client.pool.DefaultKeyedChannelPool.doClose(DefaultKeyedChannelPool.java:326)
        at com.linecorp.armeria.client.pool.DefaultKeyedChannelPool.lambda$close$6(DefaultKeyedChannelPool.java:313)
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

This seems to happen when I run integration tests that create an application context (Spring) and then destroy it quickly.

**Comment by trustin** [comment]
@rfkm @mauhiz https://github.com/line/armeria/pull/1045 should fix this issue.
