### ISSUE TITLE
Zipkin dependency issue with spring-boot2

### ISSUE THREAD

**Issue by techno** [line/armeria#1104]
We are using Armeria with Spring-boot 2 and Gradle.

Since spring-boot 2.0, spring-boot gradle plugin no longer add group name to the name of jar.
https://github.com/spring-projects/spring-boot/issues/10778

As a result, conflict zipkin artifacts used by Armeria in jar.
Jar file contains two `BOOT-INF/lib/zipkin-2.5.1.jar` in our project.
Also application booting up failed sometime.... (result depends on build env)

```
2018-03-27 15:45:37.940 ERROR 18459 --- [           main] o.s.boot.SpringApplication               : Application run failed
java.lang.IllegalStateException: Error processing condition on com.linecorp.armeria.spring.ArmeriaAutoConfiguration
    at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:64)
...
    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.TypeNotPresentException: Type zipkin2.Span not present
```

Looks Armeria depends `io.zipkin.java:zipkin` which depends on `io.zipkin.zipkin2:zipkin`.
However, `io.zipkin.java:zipkin` seems just a alias artifact of zipkin2.
If armeria depends on `io.zipkin.zipkin2:zipkin`, this issue might be resolved.

```
|    +--- com.linecorp.armeria:armeria-zipkin-shaded:0.59.0
|    |    +--- com.linecorp.armeria:armeria-shaded:0.59.0 (*)
|    |    +--- com.google.code.findbugs:jsr305:3.0.2
|    |    +--- io.zipkin.brave:brave:4.17.2
|    |    |    +--- io.zipkin.zipkin2:zipkin:2.5.1
|    |    |    \--- io.zipkin.reporter2:zipkin-reporter:2.4.1
|    |    |         \--- io.zipkin.zipkin2:zipkin:2.5.1
|    |    +--- io.zipkin.java:zipkin:2.5.1
|    |    |    \--- io.zipkin.zipkin2:zipkin:2.5.1
|    |    \--- org.slf4j:slf4j-api:1.7.25
```

**Comment by trustin** [comment]
Thanks for reporting!

**Comment by trustin** [comment]
https://search.maven.org/remotecontent?filepath=io/zipkin/java/zipkin/2.6.1/zipkin-2.6.1.pom
https://search.maven.org/remotecontent?filepath=io/zipkin/zipkin2/zipkin/2.6.1/zipkin-2.6.1.pom

It seems like `io.zipkin.java:zipkin` is not just an alias. If I replace `io.zipkin.java:zipkin` with `io.zipkin.zipkin2:zipkin`, it fails to compile:

```
/home/trustin/Workspaces/armeria/zipkin/src/main/java/com/linecorp/armeria/internal/tracing/SpanTags.java:25: error: package zipkin does not exist
import zipkin.Constants;
             ^
/home/trustin/Workspaces/armeria/zipkin/src/main/java/com/linecorp/armeria/internal/tracing/SpanTags.java:26: error: package zipkin does not exist
import zipkin.TraceKeys;
             ^
/home/trustin/Workspaces/armeria/zipkin/src/main/java/com/linecorp/armeria/client/tracing/HttpTracingClient.java:140: error: cannot access Endpoint
        span.remoteEndpoint(Endpoint.newBuilder().serviceName(remoteServiceName).ip(address).build());
            ^
  class file for zipkin.Endpoint not found
/home/trustin/Workspaces/armeria/zipkin/src/main/java/com/linecorp/armeria/internal/tracing/SpanTags.java:38: error: cannot find symbol
            span.tag(TraceKeys.HTTP_HOST, log.host());
                     ^
  symbol:   variable TraceKeys
  location: class SpanTags
/home/trustin/Workspaces/armeria/zipkin/src/main/java/com/linecorp/armeria/internal/tracing/SpanTags.java:51: error: cannot find symbol
            .tag(TraceKeys.HTTP_STATUS_CODE, String.valueOf(log.statusCode()));
                 ^
  symbol:   variable TraceKeys
  location: class SpanTags
/home/trustin/Workspaces/armeria/zipkin/src/main/java/com/linecorp/armeria/internal/tracing/SpanTags.java:50: error: cannot find symbol
            .tag(TraceKeys.HTTP_URL, uriBuilder.toString())
                 ^
  symbol:   variable TraceKeys
  location: class SpanTags
/home/trustin/Workspaces/armeria/zipkin/src/main/java/com/linecorp/armeria/internal/tracing/SpanTags.java:49: error: cannot find symbol
            .tag(TraceKeys.HTTP_PATH, log.path())
                 ^
  symbol:   variable TraceKeys
  location: class SpanTags
/home/trustin/Workspaces/armeria/zipkin/src/main/java/com/linecorp/armeria/internal/tracing/SpanTags.java:48: error: cannot find symbol
        span.tag(TraceKeys.HTTP_METHOD, log.method().name())
                 ^
  symbol:   variable TraceKeys
  location: class SpanTags
/home/trustin/Workspaces/armeria/zipkin/src/main/java/com/linecorp/armeria/internal/tracing/SpanTags.java:54: error: cannot find symbol
            span.tag(Constants.ERROR, responseCause.toString());
                     ^
  symbol:   variable Constants
  location: class SpanTags
9 errors
```

**Comment by trustin** [comment]
If I understood the issue correctly, it's a limitation of spring gradle plugin or an artifact naming issue with Zipkin. Did you try this workaround? https://github.com/spring-projects/spring-boot/issues/10778#issuecomment-372573514

**Comment by techno** [comment]
I tried the workaround, and it works well.

BTW, the brave library only depend on zipkin2, so I thought we can replace with zipkin2 completely.
But it seems difficult...
