### ISSUE TITLE
Fix test failure in ZooKeeperRegistrationTest

### ISSUE THREAD

**Issue by trustin** [line/armeria#1133]
```
com.linecorp.armeria.server.zookeeper.ZooKeeperRegistrationTest > testServerNodeCreateAndDelete FAILED
    java.lang.AssertionError: Unexpected value [Success:false] on Success expected:<true> but was:<false>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at junitextensions.TryAssert.assertSuccess(TryAssert.java:62)
        at zookeeperjunit.ZooKeeperAssert.assertExists(ZooKeeperAssert.java:38)
        at com.linecorp.armeria.server.zookeeper.ZooKeeperRegistrationTest.lambda$testServerNodeCreateAndDelete$1(ZooKeeperRegistrationTest.java:81)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at com.linecorp.armeria.server.zookeeper.ZooKeeperRegistrationTest.testServerNodeCreateAndDelete(ZooKeeperRegistrationTest.java:80)
```

/cc @dongjinleekr

**Comment by dongjinleekr** [comment]
Hmm, it seems like this test is so flaky. Let me have a look.
