### ISSUE TITLE
Invalid argument deep in netty code

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1146]
I recently started making a new request in my code, and I am getting a strange error when trying to connect. It might be a problem in my code, though I suspect the recent `Endpoint` changes a little too, but hard to work out what the problem might be if it's in my code since it's very deep and has an IPv6 address which I definitely don't create or reference anywhere. Any quick thoughts on it? Presumably even if it's a problem in my calling code, armeria must be missing an argument check of its own somewhere.

```
java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Invalid argument: www.googleapis.com/2607:f8b0:4001:c14:0:0:0:5f:443
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
at com.linecorp.armeria.common.HttpMessageAggregator.fail(HttpMessageAggregator.java:161)
at com.linecorp.armeria.common.HttpMessageAggregator.accept(HttpMessageAggregator.java:114)
at com.linecorp.armeria.common.HttpMessageAggregator.accept(HttpMessageAggregator.java:36)
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Invalid argument: www.googleapis.com/2607:f8b0:4001:c14:0:0:0:5f:443
at io.netty.channel.unix.Errors.throwConnectException(Errors.java:112)
at io.netty.channel.unix.Socket.connect(Socket.java:257)
at io.netty.channel.epoll.AbstractEpollChannel.doConnect0(AbstractEpollChannel.java:732)
at io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:717)
at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:559)
at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1366)
at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:545)
at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:530)
at com.linecorp.armeria.client.HttpClientPipelineConfigurator.connect(HttpClientPipelineConfigurator.java:198)
at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:545)
at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:530)
at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:512)
at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:1024)
at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:259)
at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:252)
```

**Comment by anuraaga** [comment]
Actually, this code doesn't use `Endpoint` so guess not related to that.

**Comment by trustin** [comment]
`DnsAddressResolveContext` sends only `A` question if IPv6 is not available, which matches the previous behavior - https://github.com/netty/netty/blob/cd4594d29244f7bea9d718e74ec4ecdcb6c62c13/resolver-dns/src/main/java/io/netty/resolver/dns/DnsAddressResolveContext.java#L34

We here assume OS has IPv6 support, mainly because there's no Java API that allows us to check the underlying OS has IPv6 support. This is often just fine because almost all modern systems have IPv6 enabled.

`-Djava.net.preferIPv4Stack=true` disables JDK's IPv6 support, and as a result, a user has to specify this option when his or her OS has no IPv6 support.

I believe all Netty code is based on this rule. It would could disable IPv6 automatically when OS cannot handle IPv6 addresses. I rougly guess it will be a complicated matter than just trying to bind on `[::1]:0` because of the IPv6-to-4 compatibility layer in most OS. Any suggestion or experiments would be appreciated.

**Comment by anuraaga** [comment]
Yeah but all Java code, including Netty, is supposed to use ipv4 if it got both ipv4 and ipv6 based on this flag.

https://github.com/netty/netty/blob/602ee5444dcd2c9adad9bdffb93ae907ccad5649/common/src/main/java/io/netty/util/NetUtil.java#L130

I'm not sure but believe the `getPreferredAddress` function was allowing this to happen, though I perhaps hackily (it seems to rely on the dns record returning A before AAAA which I don't know if there is any guarantee on).

**Comment by anuraaga** [comment]
I have sent https://github.com/netty/netty/pull/7875 upstream to fix this

**Comment by trustin** [comment]
OK to close?
