### ISSUE TITLE
NPE from void service method

### ISSUE THREAD

**Issue by rkapsi** [line/armeria#1165]
Void service methods throw a NPE and result in a `HTTP 500 Internal Server Error` response. IMHO they shouldn't result in a NPE and be handled as `HTTP 204 No Content`.

```java
public class FooService {
  @Get("/foo")
  public void doFoo() {
  }
}
```

```java
2018-04-26 12:53:23,200 [armeria-common-worker-epoll-5-6] HttpResponseSubscriber WARN : [id: 0xbb5add58, L:/127.0.0.1:8080 - R:/127.0.0.1:4052] Unexpected exception from a service or a response publisher: AnnotatedHttpService{pathMapping=[exact:/foo, {supportedMethods=[GET], consumeTypes=[], produceTypes=[]}], delegate=com.linecorp.armeria.server.AnnotatedHttpServiceMethod@5fafa7d1, decorator=java.util.function.Function$$Lambda$34/1952194564@58efa595}
 java.lang.NullPointerException: null
	at com.linecorp.armeria.server.AnnotatedHttpServiceMethod.convertResponse(AnnotatedHttpServiceMethod.java:218) ~[armeria-0.62.0.jar:?]
	at com.linecorp.armeria.server.AnnotatedHttpServiceMethod.lambda$serve$0(AnnotatedHttpServiceMethod.java:124) ~[armeria-0.62.0.jar:?]
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822) ~[?:1.8.0_162]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797) ~[?:1.8.0_162]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_162]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1595) ~[?:1.8.0_162]
	at com.linecorp.armeria.common.AbstractRequestContext.lambda$makeContextAware$1(AbstractRequestContext.java:72) ~[armeria-0.62.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_162]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.24.Final.jar:4.1.24.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```

**Comment by hyangtack** [comment]
@rkapsi Thanks for reporting! Let me send a PR in order to fix this issue.

**Comment by hyangtack** [comment]
Fixed.  https://github.com/line/armeria/pull/1166/commits/3db8bf79ac7d21403b53ff235ff91204328ab8ec

**Comment by trustin** [comment]
Should be part of the next release. Please feel free to give it a try and let us know if the fix worked for you. As you might already know, the workaround is as simple as returning `HttpResponse.of(204)`.
