### ISSUE TITLE
HttpClient using h2c for http URL for some reason

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1201]
Using armeria to fetch access tokens in Google Cloud, I ran into weird behavior that it tries to use `h2c` for an `http` URL, and fails when the response is `h1c`.

```
Request: {startTime=2018-05-16T09:10:26.732Z(1526461826732), length=0B, duration=775µs(775385ns), scheme=none+h2c, host=169.254.169.254, headers=[:method=GET, metadata-flavor=Google, :authority=169.254.169.254, :scheme=http, user-agent=armeria/0.63.1, :path=/computeMetadata/v1/instance/service-accounts/default/token]}
```

Note that `:scheme` is `http` but `scheme` is `none+h2c`.

The user code fails with `ClosedSessionException` and there is a log

```
[id: 0xc013be2e, L:/10.146.0.11:35526 - R:169.254.169.254/169.254.169.254:80] Sent a GOAWAY frame: lastStreamId=0, errorCode=PROTOCOL_ERROR(1), debugData="type: io.netty.handler.codec.http2.Http2Exception, message: First received frame was not SETTINGS. Hex dump for first 5 bytes: 3c21444f43, cause: io.netty.handler.codec.http2.Http2Exception:
First received frame was not SETTINGS. Hex dump for first 5 bytes: 3c21444f43 at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85) at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:350) at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:251) at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450) at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at
```
The decoded bytes are `<DOCT`. This is somewhat strange too since you'd expect an HTTP/1 response to start with `HTTP `.

Changing the url from `http` to `h1c` fixes the problem. If this is a server side issue (a server that initiates `http2` upgrade but later responds with `http` weirdly?), then I'll close this but filing just in case it's an issue in armeria.

**Comment by imasahiro** [comment]
Recently, I saw similar error when updating armeria. Because client's default behavior is changed by https://github.com/line/armeria/pull/1110, IIRC, if a server cannot recognize request for http2, it fails.
1 workaround for this is disable useHttp2Preface. How do you think @trustin ?

**Comment by anuraaga** [comment]
Hmm - I had interpreted that PR as being fine now that there are no incompliant HTTP/2 servers, with no relation to HTTP/1 servers but if it doesn't work for normal HTTP/1 servers, it might be a bad default as it prevents armeria from being a drop-in replacement for `HttpUrlConnection`.

**Comment by trustin** [comment]
After reading the source code of `PrefaceDecoder`, it rather seems like a bug in Google's HTTP server, given that it sent plaintext content right rather then the SETTINGS frame after sending a connection preface string. However, I'd like to check the complete traffic just in case it's our bug.

**Comment by anuraaga** [comment]
Will try to check with traffic logger at some point - unfortunately not trivial since this server requires the code to be deployed to the cloud :/
