### ISSUE TITLE
Test failure: com.linecorp.armeria.common.rxjava.RequestContextAssemblyTest

### ISSUE THREAD

**Issue by hyangtack** [line/armeria#1211]
```
com.linecorp.armeria.common.rxjava.RequestContextAssemblyTest > composeWithOtherHook FAILED
    org.junit.ComparisonFailure: expected:<[3]> but was:<[0]>
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at com.linecorp.armeria.common.rxjava.RequestContextAssemblyTest.composeWithOtherHook(RequestContextAssemblyTest.java:131)
com.linecorp.armeria.common.rxjava.RequestContextAssemblyTest > enableTracking FAILED
    org.junit.ComparisonFailure: expected:<[200 OK]> but was:<[500 Internal Server Error]>
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at com.linecorp.armeria.common.rxjava.RequestContextAssemblyTest.enableTracking(RequestContextAssemblyTest.java:109)
08:33:00.723 [Thread-6] DEBUG c.l.armeria.client.ClientFactory - Closing the default ClientFactory
```
/cc @kojilin Do you have any idea?

**Comment by hyangtack** [comment]
It was caused by a bug in PR #1191. Thanks to @kojilin . :-)
