### ISSUE TITLE
Default MeterIdFunction implementation sometimes adds 'httpStatus' tag to 'activeRequests'

### ISSUE THREAD

**Issue by trustin** [line/armeria#1258]
Stack trace:

```
onRequestLog() failed with an exception:
java.lang.IllegalArgumentException: Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter containing tag keys [hostnamePattern, method, pathMapping, service]. The meter you are attempting to register has keys [hostnamePattern, httpStatus, method, pathMapping, service].
	at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$collectorByName$9(PrometheusMeterRegistry.java:361)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877)
	at io.micrometer.prometheus.PrometheusMeterRegistry.collectorByName(PrometheusMeterRegistry.java:348)
	at io.micrometer.prometheus.PrometheusMeterRegistry.newGauge(PrometheusMeterRegistry.java:225)
	at io.micrometer.core.instrument.MeterRegistry.lambda$gauge$1(MeterRegistry.java:244)
	at io.micrometer.core.instrument.MeterRegistry.lambda$registerMeterIfNecessary$5(MeterRegistry.java:514)
	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:563)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:525)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:514)
	at io.micrometer.core.instrument.MeterRegistry.gauge(MeterRegistry.java:244)
	at io.micrometer.core.instrument.Gauge$Builder.register(Gauge.java:128)
	at io.micrometer.core.instrument.MeterRegistry.gauge(MeterRegistry.java:426)
	at com.linecorp.armeria.internal.metric.RequestMetricSupport.lambda$onRequest$1(RequestMetricSupport.java:68)
	at com.linecorp.armeria.internal.metric.MicrometerUtil.lambda$register$2(MicrometerUtil.java:95)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1688)
	at com.linecorp.armeria.internal.metric.MicrometerUtil.register(MicrometerUtil.java:92)
	at com.linecorp.armeria.internal.metric.MicrometerUtil.register(MicrometerUtil.java:77)
	at com.linecorp.armeria.internal.metric.RequestMetricSupport.onRequest(RequestMetricSupport.java:65)
	at com.linecorp.armeria.internal.metric.RequestMetricSupport.lambda$setup$0(RequestMetricSupport.java:53)
	at com.linecorp.armeria.common.logging.RequestLogListenerInvoker.invokeOnRequestLog(RequestLogListenerInvoker.java:39)
	at com.linecorp.armeria.common.logging.DefaultRequestLog.notifyListeners(DefaultRequestLog.java:766)
	at com.linecorp.armeria.common.logging.DefaultRequestLog.updateAvailability(DefaultRequestLog.java:723)
	at com.linecorp.armeria.common.logging.DefaultRequestLog.endRequest0(DefaultRequestLog.java:522)
	at com.linecorp.armeria.common.logging.DefaultRequestLog.endRequest0(DefaultRequestLog.java:505)
	at com.linecorp.armeria.common.logging.DefaultRequestLog.endRequest(DefaultRequestLog.java:496)
	at com.linecorp.armeria.server.HttpServerHandler.lambda$handleRequest$3(HttpServerHandler.java:404)
	at com.linecorp.armeria.common.util.Functions.lambda$voidFunction$1(Functions.java:192)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:286)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:193)
	at com.linecorp.armeria.common.stream.AbstractStreamMessage.cleanupQueue(AbstractStreamMessage.java:161)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.cleanup(DefaultStreamMessage.java:390)
	at io.netty.util.concurrent.ImmediateEventExecutor.execute(ImmediateEventExecutor.java:111)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.cancelOrAbort(DefaultStreamMessage.java:222)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.abort(DefaultStreamMessage.java:144)
	at com.linecorp.armeria.server.HttpServerHandler.lambda$handleRequest$4(HttpServerHandler.java:412)
	at com.linecorp.armeria.common.util.Functions.lambda$voidFunction$1(Functions.java:192)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

We'd beter define two methods for `MeterIdPrefixFunction` - one for `activeRequests` and the other for other meters.

**Comment by huydx** [comment]
let me fix that
