### ISSUE TITLE
AbstractMethodError in latest tcnative

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1275]
I tried upgrading armeria, which gets the latest netty and tcnative, but I get the below exception on all client requests. JDK10 issue? Fixing tcnative to 2.0.10 works fine.

Java: JDK10
armeria: 0.67.1
netty: 4.1.25
tcnative: 2.0.11

```
java.lang.AbstractMethodError: null
	at io.netty.internal.tcnative.SSL.doHandshake(Native Method) ~[netty-tcnative-boringssl-static-2.0.11.Final.jar:2.0.11.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.handshake(ReferenceCountedOpenSslEngine.java:1563) ~[netty-handler-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.wrap(ReferenceCountedOpenSslEngine.java:652) ~[netty-handler-4.1.25.Final.jar:4.1.25.Final]
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:511) ~[?:?]
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:997) ~[netty-handler-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:803) ~[netty-handler-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:771) ~[netty-handler-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.ssl.SslHandler.handleUnwrapThrowable(SslHandler.java:1207) ~[netty-handler-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1191) ~[netty-handler-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1223) ~[netty-handler-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:147) [netty-handler-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) [netty-transport-native-epoll-4.1.25.Final-linux-x86_64.jar:4.1.25.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) [netty-transport-native-epoll-4.1.25.Final-linux-x86_64.jar:4.1.25.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) [netty-transport-native-epoll-4.1.25.Final-linux-x86_64.jar:4.1.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-common-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.25.Final.jar:4.1.25.Final]
	at java.lang.Thread.run(Thread.java:844) [?:?]
```

**Comment by trustin** [comment]
Doh! Yeah JDK10 related I guess. Let me take a look this week.
