### ISSUE TITLE
TLS handshake failure on 0.68.1 due to NPE

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1317]
After trying out 0.68.1, which changed the way TLS handshakes work, I see this on my server. I am using TLS mutual auth in case that is affecting this case.

JRE: OpenJDK 10.0.2

```
Caused by: java.lang.NullPointerException
	at sun.net.util.IPAddressUtil.textToNumericFormatV4(IPAddressUtil.java:49) ~[?:?]
	at sun.net.util.IPAddressUtil.isIPv4LiteralAddress(IPAddressUtil.java:241) ~[?:?]
	at sun.security.util.HostnameChecker.isIpAddress(HostnameChecker.java:139) ~[?:?]
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:97) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:481) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:456) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:296) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.checkClientTrusted(X509TrustManagerImpl.java:139) ~[?:?]
	at io.netty.handler.ssl.ReferenceCountedOpenSslServerContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslServerContext.java:232) ~[netty-handler-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:621) ~[netty-handler-4.1.27.Final.jar:4.1.27.Final]
	... 29 more
"    
```

**Comment by anuraaga** [comment]
I am going to first try reverting the change to `HttpServerPipelineConfigurator` to see if the issue resolves.

**Comment by trustin** [comment]
Could you let us know the Java version so we can guess what SSLEngine property is causing an NPE? It may be an issue in OpenSSLEngine that returns an incorrect value on some property.

**Comment by anuraaga** [comment]
Ah yeah - it's OpenJDK 10.0.2

**Comment by anuraaga** [comment]
Confirmed that reverting the change in server configurator fixes the NPE
