### ISSUE TITLE
'IllegalStateException: executor not accepting a task' when sending a request when ClientFactory is closing.

### ISSUE THREAD

**Issue by trustin** [line/armeria#1432]
```
com.linecorp.armeria.it.client.retry.RetryingRpcClientTest > shouldGetExceptionWhenFactoryIsClosed FAILED
    java.lang.AssertionError: 
    Expecting:
      <java.lang.IllegalStateException: executor not accepting a task>
    to be an instance of:
      <com.linecorp.armeria.client.ClosedClientFactoryException>
    but was:
      <"java.lang.IllegalStateException: executor not accepting a task
    	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:60)
    	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:200)
    	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:170)
    	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:145)
    	at com.linecorp.armeria.client.HttpSessionChannelFactory.connect(HttpSessionChannelFactory.java:92)
    	at com.linecorp.armeria.client.HttpSessionChannelFactory.apply(HttpSessionChannelFactory.java:79)
    	at com.linecorp.armeria.client.HttpSessionChannelFactory.apply(HttpSessionChannelFactory.java:43)
    	at com.linecorp.armeria.client.pool.DefaultKeyedChannelPool.acquireHealthyFromPoolOrNew(DefaultKeyedChannelPool.java:126)
    	at com.linecorp.armeria.client.pool.DefaultKeyedChannelPool.acquire(DefaultKeyedChannelPool.java:103)
    	at com.linecorp.armeria.client.pool.DefaultKeyedChannelPool.acquire(DefaultKeyedChannelPool.java:94)
    	at com.linecorp.armeria.client.HttpClientDelegate.executeWithIpAddr(HttpClientDelegate.java:108)
    	at com.linecorp.armeria.client.HttpClientDelegate.execute(HttpClientDelegate.java:73)
    	at com.linecorp.armeria.client.HttpClientDelegate.execute(HttpClientDelegate.java:45)
    	at com.linecorp.armeria.client.thrift.THttpClientDelegate.execute(THttpClientDelegate.java:128)
    	at com.linecorp.armeria.client.thrift.THttpClientDelegate.execute(THttpClientDelegate.java:69)
    	at com.linecorp.armeria.internal.ClientUtil.executeWithFallback(ClientUtil.java:42)
    	at com.linecorp.armeria.client.retry.RetryingRpcClient.doExecute0(RetryingRpcClient.java:109)
    	at com.linecorp.armeria.client.retry.RetryingRpcClient.lambda$doExecute0$2(RetryingRpcClient.java:122)
    	at com.linecorp.armeria.common.AbstractRequestContext.lambda$makeContextAware$1(AbstractRequestContext.java:72)
    	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
    	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
    	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:335)
    	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
    	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    	at java.base/java.lang.Thread.run(Thread.java:844)
    ">
        at com.linecorp.armeria.it.client.retry.RetryingRpcClientTest.shouldGetExceptionWhenFactoryIsClosed(RetryingRpcClientTest.java:174)
```

**Comment by trustin** [comment]
Fixed in 0.79 via #1532
