### ISSUE TITLE
Error logged for prometheus scrape

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#1437]
In a service that is scraped by prometheus using `new LoggingServiceBuilder().build()`, which enables logging of error responses, a large number of scrapes get logged as errors. Perhaps this is a problem with prometheus's golang HTTP client, but wonder if there could be something going wrong in Armeria. The metrics are all available in prometheus so the scrape seems to be succeeding fine.

Log errors are usually Connection reset by peer
```
/internal/metrics#GET] Response: {startTime=2018-11-14T04:16:01.624Z(1542168961624), length=58903B, duration=1039µs(1039150ns), cause=io.netty.channel.unix.Errors$NativeIoException: writevAddresses(..) failed: Connection reset by peer, headers=[:status=200, content-type=text/plain; version=0.0.4; charset=utf-8, content-length=58903]}
```

Using armeria's default `PrometheusExpositionService`.

**Comment by trustin** [comment]
Could you paste the full stack trace just in case it has useful info?

**Comment by anuraaga** [comment]
Sure

```
"io.netty.channel.unix.Errors$NativeIoException: writevAddresses(..) failed: Connection reset by peer
	at io.netty.channel.unix.Errors.newIOException(Errors.java:122) ~[netty-transport-native-unix-common-4.1.30.Final-linux-x86_64.jar:4.1.30.Final]
	at io.netty.channel.unix.Errors.ioResult(Errors.java:146) ~[netty-transport-native-unix-common-4.1.30.Final-linux-x86_64.jar:4.1.30.Final]
	at io.netty.channel.unix.FileDescriptor.writevAddresses(FileDescriptor.java:155) ~[netty-transport-native-unix-common-4.1.30.Final-linux-x86_64.jar:4.1.30.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel.writeBytesMultiple(AbstractEpollStreamChannel.java:316) ~[netty-transport-native-epoll-4.1.30.Final-linux-x86_64.jar:4.1.30.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel.doWriteMultiple(AbstractEpollStreamChannel.java:522) ~[netty-transport-native-epoll-4.1.30.Final-linux-x86_64.jar:4.1.30.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel.doWrite(AbstractEpollStreamChannel.java:434) ~[netty-transport-native-epoll-4.1.30.Final-linux-x86_64.jar:4.1.30.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:525) [netty-transport-native-epoll-4.1.30.Final-linux-x86_64.jar:4.1.30.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:411) [netty-transport-native-epoll-4.1.30.Final-linux-x86_64.jar:4.1.30.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321) [netty-transport-native-epoll-4.1.30.Final-linux-x86_64.jar:4.1.30.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by trustin** [comment]
What's the protocol? H1C or H2C?

**Comment by anuraaga** [comment]
Oops yes that's useful, updated my example with a scrubbed URL. The protocol is `H1` (TLS + HTTP/1)

**Comment by trustin** [comment]
Thanks for coming back with the information. Glad that it's somewhere else. :)
