### ISSUE TITLE
StreamMessageDuplicator feeds null to its Subscriber

### ISSUE THREAD

**Issue by trustin** [line/armeria#1446]
```
java.lang.NullPointerException: null 
	at com.linecorp.armeria.common.HttpMessageAggregator.onData(HttpMessageAggregator.java:91) 
	at com.linecorp.armeria.common.HttpResponseAggregator.onData(HttpResponseAggregator.java:96) 
	at com.linecorp.armeria.common.HttpMessageAggregator.onNext(HttpMessageAggregator.java:78) 
	at com.linecorp.armeria.common.HttpMessageAggregator.onNext(HttpMessageAggregator.java:36) 
	at com.linecorp.armeria.common.stream.DeferredStreamMessage$ForwardingSubscriber.onNext(DeferredStreamMessage.java:302) 
	at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$DownstreamSubscription.doSignalSingle(AbstractStreamMessageDuplicator.java:747) 
	at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$DownstreamSubscription.doSignal(AbstractStreamMessageDuplicator.java:657) 
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) 
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:326) 
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) 
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by trustin** [comment]
Fixed via #1449
