### ISSUE TITLE
Test failure: RequestContextTest.makeContextAwareCompletableFutureWithAsyncChaining()

### ISSUE THREAD

**Issue by trustin** [line/armeria#1598]
```
com.linecorp.armeria.common.RequestContextTest > makeContextAwareCompletableFutureWithAsyncChaining FAILED
    java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
        at com.linecorp.armeria.common.RequestContextTest.makeContextAwareCompletableFutureWithAsyncChaining(RequestContextTest.java:285)
        Caused by:
        java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
            at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
            at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
            at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
            at java.base/java.util.Objects.checkIndex(Objects.java:372)
            at java.base/java.util.ArrayList.remove(ArrayList.java:535)
            at com.linecorp.armeria.common.RequestContextTest.lambda$createContext$29(RequestContextTest.java:414)
```

**Comment by trustin** [comment]
Can't reproduce anymore, but will add some assertions so that it is easier to determine the cause of the failure next time it happened.
