### ISSUE TITLE
Native image compatibility

### ISSUE THREAD

**Issue by trustin** [line/armeria#1681]
Not sure if it is achievable but I think it's worth a research. It seems like we can embed some metadata to our artifacts which is used as a hint when building a native image.

**Comment by dalbodeule** [comment]
Ex: Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.linecorp.armeria.common.ExceptionSampler.<init>(ExceptionSampler.java:31)
	at com.linecorp.armeria.common.DefaultFlagsProvider.<clinit>(DefaultFlagsProvider.java:45)
	at com.linecorp.armeria.common.Flags.<clinit>(Flags.java:107)
	at com.linecorp.armeria.internal.common.RequestContextUtil.<clinit>(RequestContextUtil.java:66)
	at com.linecorp.armeria.server.ServerBuilder.<clinit>(ServerBuilder.java:169)
	at com.linecorp.armeria.server.Server.builder(Server.java:111)
	at space.mori.onlinejudge.backend.MainKt.newServer(Main.kt:27)
	at space.mori.onlinejudge.backend.MainKt.newServer$default(Main.kt:26)
	at space.mori.onlinejudge.backend.MainKt.main(Main.kt:17)
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: _kvs
	at com.linecorp.armeria.internal.shaded.jctools.util.UnsafeAccess.fieldOffset(UnsafeAccess.java:111)
	at com.linecorp.armeria.internal.shaded.jctools.maps.NonBlockingHashMap.<clinit>(NonBlockingHashMap.java:103)
	... 9 more
Caused by: java.lang.NoSuchFieldException: _kvs
	at java.base@17.0.6/java.lang.Class.getDeclaredField(DynamicHub.java:961)
	at com.linecorp.armeria.internal.shaded.jctools.util.UnsafeAccess.fieldOffset(UnsafeAccess.java:107)
	... 10 more

Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: _kvs

Caused by: java.lang.NoSuchFieldException: _kvs

and this error caused by [like this](https://github.com/line/armeria/blob/54f058d6c03e1708eee15b462cf7e5b5ab100663/core/src/main/java/com/linecorp/armeria/common/ExceptionSampler.java#L31)

**Comment by ikhoon** [comment]
Could you provide a reproducible example?

**Comment by dalbodeule** [comment]
In fact, I'm not familiar with Java, so I'm going to provide the current status of the project I'm working on.

The location is [here(Hyperlink)](https://github.com/dalbodeule/OnlineJudge/blob/armeria_native_image_comp/Backend/build.gradle.kts), and only the Backend subproject is applicable.
