### ISSUE TITLE
TLS Protocols & Ciphers with Spring Boot

### ISSUE THREAD

**Issue by gquintana** [line/armeria#1711]
This is related to issue #1659 

HTTPS is working properly until I set armeria.ssl.enabled-protocols or armeria.ssl.ciphers

Here is my spring boot configuration
```
server:
  port: 9411
  ssl:
    enabled: true
    key-alias: "myhost.mycompany.fr"
    # ciphers: "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384,TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256"
    #enabled-protocols: "TLSv1.2"
    key-store: "/opt/zipkin-2.12.8/keystore.jks"
    key-store-password: "changeme"
    trust-store: "/opt/zipkin-2.12.8/keystore.jks"
    trust-store-password: "changeme"

armeria:
  ports:
    - port: 9411
      protocol: HTTPS
  ssl:
    key-alias: "myhost.mycompany.fr"
    # ciphers: "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384,TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256"
    #enabled-protocols: "TLSv1.2"
    key-store: "/opt/zipkin-2.12.8/keystore.jks"
    key-store-password: "changeme"
    trust-store: "/opt/zipkin-2.12.8/keystore.jks"
    trust-store-password: "changeme"
```

When I uncomment enabled-protocols:
```
2019-04-11T18:01:29,975 WARN  com.linecorp.armeria.server.HttpServerPipelineConfigurator$Http2OrHttpHandler - [id: 0xd9cf80d2, L:/10.122.135.222:9411 - R:/163.113.65.61:48292] TLS handshake failed:
javax.net.ssl.SSLHandshakeException: error:1000009c:SSL routines:OPENSSL_internal:HTTP_REQUEST
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:973) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.sslReadErrorResult(ReferenceCountedOpenSslEngine.java:1231) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1185) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1256) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1299) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:217) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1330) [netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1237) [netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274) [netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) [netty-codec-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) [netty-codec-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) [netty-codec-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:249) [netty-codec-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) [netty-codec-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) [netty-codec-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) [netty-codec-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:154) [netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796) [netty-transport-native-epoll-4.1.34.Final-linux-x86_64.jar!/:4.1.34.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427) [netty-transport-native-epoll-4.1.34.Final-linux-x86_64.jar!/:4.1.34.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328) [netty-transport-native-epoll-4.1.34.Final-linux-x86_64.jar!/:4.1.34.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) [netty-common-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.34.Final.jar!/:4.1.34.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

When I uncomment ciphers (but not protocols):
```
Caused by: java.lang.IllegalArgumentException: unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384(ECDHE-ECDSA-AES256-SHA384)
        at io.netty.handler.ssl.CipherSuiteConverter.convertToCipherStrings(CipherSuiteConverter.java:470) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:254) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:43) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:345) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:333) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:423) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:447) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at com.linecorp.armeria.internal.spring.ArmeriaConfigurationUtil.configureTls(ArmeriaConfigurationUtil.java:383) ~[armeria-spring-boot-autoconfigure-0.83.0.jar!/:?]
        at com.linecorp.armeria.internal.spring.ArmeriaConfigurationUtil.configureTls(ArmeriaConfigurationUtil.java:343) ~[armeria-spring-boot-autoconfigure-0.83.0.jar!/:?]
        at com.linecorp.armeria.internal.spring.ArmeriaConfigurationUtil.configureServerWithArmeriaSettings(ArmeriaConfigurationUtil.java:163) ~[armeria-spring-boot-autoconfigure-0.83.0.jar!/:?]
        at com.linecorp.armeria.spring.ArmeriaAutoConfiguration.armeriaServer(ArmeriaAutoConfiguration.java:105) ~[armeria-spring-boot-autoconfigure-0.83.0.jar!/:?]
        at com.linecorp.armeria.spring.ArmeriaAutoConfiguration$$EnhancerBySpringCGLIB$$16ba9c43.CGLIB$armeriaServer$0(<generated>) ~[armeria-spring-boot-autoconfigure-0.83.0.jar!/:?]
        at com.linecorp.armeria.spring.ArmeriaAutoConfiguration$$EnhancerBySpringCGLIB$$16ba9c43$$FastClassBySpringCGLIB$$ad64608f.invoke(<generated>) ~[armeria-spring-boot-autoconfigure-0.83.0.jar!/:?]
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
        at com.linecorp.armeria.spring.ArmeriaAutoConfiguration$$EnhancerBySpringCGLIB$$16ba9c43.armeriaServer(<generated>) ~[armeria-spring-boot-autoconfigure-0.83.0.jar!/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622) ~[spring-beans-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
        ... 25 more
```

What are the appropriate values for fields ciphers and enabled-protocols ?
* SSL Protocols https://docs.oracle.com/javase/8/docs/technotes/guides/security/StandardNames.html#SSLContext
* SSL Cipher Suites https://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html#SupportedCipherSuites

We are running Java 8 u202 which supports cipher TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
```
$  java  -version
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.202-b08, mixed mode)
```

**Comment by trustin** [comment]
When using OpenSSL-based `SSLEngine`, Netty's `CipherSuiteConverter` converts Java cipher names into what OpenSSL understands. It seems like `CipherSuiteConverter` does not recognize some of the cipher you specified, which means Netty needs a fix.

Alternatively, you can disable OpenSSL-based `SSLEngine` by specifying `-Dcom.linecorp.armeria.useOpenSsl=false` JVM option. Could you give it a try and let me know if the problem goes away?

**Comment by gquintana** [comment]
openssl supports the mentioned cipher:
```
$ openssl ciphers -tls1 |grep ECDHE-ECDSA-AES256-SHA384
ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DH-DSS-AES256-GCM-SHA384:DHE-DSS-AES256-GCM-SHA384:DH-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA256:DH-RSA-AES256-SHA256:DH-DSS-AES256-SHA256:DHE-RSA-AES256-SHA:DHE-DSS-AES256-SHA:DH-RSA-AES256-SHA:DH-DSS-AES256-SHA:DHE-RSA-CAMELLIA256-SHA:DHE-DSS-CAMELLIA256-SHA:DH-RSA-CAMELLIA256-SHA:DH-DSS-CAMELLIA256-SHA:ECDH-RSA-AES256-GCM-SHA384:ECDH-ECDSA-AES256-GCM-SHA384:ECDH-RSA-AES256-SHA384:ECDH-ECDSA-AES256-SHA384:ECDH-RSA-AES256-SHA:ECDH-ECDSA-AES256-SHA:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:CAMELLIA256-SHA:PSK-AES256-CBC-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:DH-DSS-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:DH-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-DSS-AES128-SHA256:DH-RSA-AES128-SHA256:DH-DSS-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA:DH-RSA-AES128-SHA:DH-DSS-AES128-SHA:DHE-RSA-SEED-SHA:DHE-DSS-SEED-SHA:DH-RSA-SEED-SHA:DH-DSS-SEED-SHA:DHE-RSA-CAMELLIA128-SHA:DHE-DSS-CAMELLIA128-SHA:DH-RSA-CAMELLIA128-SHA:DH-DSS-CAMELLIA128-SHA:ECDH-RSA-AES128-GCM-SHA256:ECDH-ECDSA-AES128-GCM-SHA256:ECDH-RSA-AES128-SHA256:ECDH-ECDSA-AES128-SHA256:ECDH-RSA-AES128-SHA:ECDH-ECDSA-AES128-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:SEED-SHA:CAMELLIA128-SHA:PSK-AES128-CBC-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:EDH-DSS-DES-CBC3-SHA:DH-RSA-DES-CBC3-SHA:DH-DSS-DES-CBC3-SHA:ECDH-RSA-DES-CBC3-SHA:ECDH-ECDSA-DES-CBC3-SHA:DES-CBC3-SHA:IDEA-CBC-SHA:PSK-3DES-EDE-CBC-SHA:KRB5-IDEA-CBC-SHA:KRB5-DES-CBC3-SHA:KRB5-IDEA-CBC-MD5:KRB5-DES-CBC3-MD5:ECDHE-RSA-RC4-SHA:ECDHE-ECDSA-RC4-SHA:ECDH-RSA-RC4-SHA:ECDH-ECDSA-RC4-SHA:RC4-SHA:RC4-MD5:PSK-RC4-SHA:KRB5-RC4-SHA:KRB5-RC4-MD5
```
The `-Dcom.linecorp.armeria.useOpenSsl=false` flag doesn't help

**Comment by trustin** [comment]
> openssl supports the mentioned cipher:

It does not use your system's OpenSSL but statically-linked BoringSSL, so it may be different? I need to check.

> The `-Dcom.linecorp.armeria.useOpenSsl=false` flag doesn't help

This is weird. Do you see the same error message and stack trace with this? When you start your application, Armeria logs the properties it refers to, e.g.

```
2019-04-12 17:59:38.933 [INFO ](c.l.a.c.Flags) com.linecorp.armeria.verboseExceptions: false (default)
2019-04-12 17:59:38.933 [INFO ](c.l.a.c.Flags) com.linecorp.armeria.verboseSocketExceptions: false (default)
2019-04-12 17:59:38.933 [INFO ](c.l.a.c.Flags) com.linecorp.armeria.verboseResponses: false (default)
2019-04-12 17:59:38.951 [INFO ](c.l.a.c.Flags) com.linecorp.armeria.useEpoll: true (default)
2019-04-12 17:59:39.047 [INFO ](c.l.a.c.Flags) com.linecorp.armeria.useOpenSsl: true (default)
...
```

Could you paste its output?

**Comment by gquintana** [comment]
```
2019-04-12T14:02:01,241 DEBUG org.springframework.boot.StartupInfoLogger - Running with Spring Boot v2.1.4.RELEASE, Spring v5.1.6.RELEASE
2019-04-12T14:02:01,242 INFO  org.springframework.boot.SpringApplication - The following profiles are active: shared
2019-04-12T14:02:04,124 INFO  com.linecorp.armeria.common.Flags - com.linecorp.armeria.verboseExceptions: false (default)
2019-04-12T14:02:04,125 INFO  com.linecorp.armeria.common.Flags - com.linecorp.armeria.verboseSocketExceptions: false (default)
2019-04-12T14:02:04,126 INFO  com.linecorp.armeria.common.Flags - com.linecorp.armeria.verboseResponses: false (default)
2019-04-12T14:02:04,160 INFO  com.linecorp.armeria.common.Flags - com.linecorp.armeria.useEpoll: true (default)
2019-04-12T14:02:04,296 INFO  com.linecorp.armeria.common.Flags - com.linecorp.armeria.useOpenSsl: false
2019-04-12T14:02:04,297 INFO  com.linecorp.armeria.common.Flags - com.linecorp.armeria.maxNumConnections: 2147483647 (default)
2019-04-12T14:02:04,297 INFO  com.linecorp.armeria.common.Flags - com.linecorp.armeria.numCommonWorkers: 8 (default)
2019-04-12T14:02:04,298 INFO  com.linecorp.armeria.common.Flags - com.linecorp.armeria.numCommonBlockingTaskThreads: 200 (default)
```
The error is the same:
```
Caused by: java.lang.IllegalArgumentException: unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384(ECDHE-ECDSA-AES256-SHA384)
        at io.netty.handler.ssl.CipherSuiteConverter.convertToCipherStrings(CipherSuiteConverter.java:470) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:254) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:43) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:345) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:333) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:423) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:447) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at com.linecorp.armeria.internal.spring.ArmeriaConfigurationUtil.configureTls(ArmeriaConfigurationUtil.java:383) ~[armeria-spring-boot-autoconfigure-0.83.0.jar!/:?]
        at com.linecorp.armeria.internal.spring.ArmeriaConfigurationUtil.configureTls(ArmeriaConfigurationUtil.java:343) ~[armeria-spring-boot-autoconfigure-0.83.0.jar!/:?]
        at com.linecorp.armeria.internal.spring.ArmeriaConfigurationUtil.configureServerWithArmeriaSettings(ArmeriaConfigurationUtil.java:163) ~[armeria-spring-boot-autoconfigure-0.83.0.jar!/:?]
```

**Comment by trustin** [comment]
Uh-oh. That sounds like a bug on our side that prevents the workaround from working. Let me try to investigate in both directions.

**Comment by anuraaga** [comment]
I wonder if this relates to https://github.com/line/armeria/issues/615

In the end, I never figured out why Armeria seems to support a limited set of ciphers

**Comment by anuraaga** [comment]
Ah seeing the Pro guess they're not related :)

**Comment by gquintana** [comment]
This PR is more a quick workaround (disable OpenSSL) rather than a real fix (fix OpenSSL ciphers)

**Comment by hyangtack** [comment]
Seems that it's because I missed [this part](https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/server/AbstractVirtualHostBuilder.java#L181-L187) when setting TLS from the Spring configuration. 😭

**Comment by anuraaga** [comment]
@gquintana I was digging into this again and found that Adam seems to have a very explicit reason to remove the "new yet still flawed and slow to boot" CBC ciphers from boringssl

https://boringssl.googlesource.com/boringssl/+/6e678eeb

What do you think about using boringssl and removing those from your cipher list?

**Comment by gquintana** [comment]
@anuraaga You're probably right, I 'am not a security expert, I am just trying to apply security requirements.

At first, I ignored Armeria was using Boring SSL, I expected that `ciphers`and `enabled-protocols` would work as using usual Java options. I am not against Boring SSL, I just need to 
* remove some ciphers which are considered as unsafe by our security team
* remove TLSv1.0, 1.1 and SSLv* protocols, also considered as unsafe (in short for TLSv1.2)

How can I find which ciphers and protocols values are allowed, so that I can build a white list?

**Comment by anuraaga** [comment]
@gquintana I don't think there's an easy way like there is for JDK where you just look at the Oracle docs. In #1777 I've added a flag that can be used so when the application starts up it shows what it supports. Hopefully this helps.

**Comment by gquintana** [comment]
@anuraaga Looks awesome! Thanks

**Comment by abkura** [comment]
@gquintana where you able to get SSL working with armeria?
