### ISSUE TITLE
responseFirstBytesTransferredTimeNanos is not available if a response is timed out

### ISSUE THREAD

**Issue by imasahiro** [line/armeria#1769]
# Problem
We are using HttpTracingService as follow. 

```
    @Bean
    HttpServiceRegistrationBean springMvcTomcatService(
            ServletWebServerApplicationContext applicationContext,
            Tracing tracing) {
        TomcatWebServer container =
                (TomcatWebServer) applicationContext.getWebServer();
        container.start();
        Connector tomcatConnector = container.getTomcat().getConnector();

        return new HttpServiceRegistrationBean()
                .setServiceName(SERVICE_NAME)
                .setService(TomcatService.forConnector(tomcatConnector)
                                         .decorate(HttpTracingService.newDecorator(tracing)))
                .setPathMapping(PathMapping.ofPrefix("/api"));
    }
```

When a response to client was timed out (maybe because it has large response), we got `RequestLogAvailabilityException`.

```
2019-05-15 01:01:56.199  WARN [-] [armeria-common-worker-epoll-2-18] c.l.a.c.l.RequestLogListenerInvoker      : onRequestLog() failed with an exception:

com.linecorp.armeria.common.logging.RequestLogAvailabilityException: RESPONSE_FIRST_BYTES_TRANSFERRED
        at com.linecorp.armeria.common.logging.RequestLog.ensureAvailability(RequestLog.java:110)
        at com.linecorp.armeria.common.logging.DefaultRequestLog.responseFirstBytesTransferredTimeNanos(DefaultRequestLog.java:717)
        at com.linecorp.armeria.server.tracing.HttpTracingService.lambda$serve$2(HttpTracingService.java:94)
        at com.linecorp.armeria.common.logging.RequestLogListenerInvoker.invokeOnRequestLog(RequestLogListenerInvoker.java:38)
        at com.linecorp.armeria.common.logging.DefaultRequestLog.notifyListeners(DefaultRequestLog.java:1006)
        at com.linecorp.armeria.common.logging.DefaultRequestLog.updateAvailability(DefaultRequestLog.java:963)
        at com.linecorp.armeria.common.logging.DefaultRequestLog.endResponse0(DefaultRequestLog.java:940)
        at com.linecorp.armeria.common.logging.DefaultRequestLog.endResponse0(DefaultRequestLog.java:919)
        at com.linecorp.armeria.common.logging.DefaultRequestLog.endResponse(DefaultRequestLog.java:905)
        at com.linecorp.armeria.server.HttpResponseSubscriber.lambda$addCallbackAndFlush$2(HttpResponseSubscriber.java:421)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:476)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
        at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:152)
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
        at com.linecorp.armeria.server.HttpResponseSubscriber.addCallbackAndFlush(HttpResponseSubscriber.java:418)
        at com.linecorp.armeria.server.HttpResponseSubscriber.failAndRespond(HttpResponseSubscriber.java:403)
        at com.linecorp.armeria.server.HttpResponseSubscriber.onTimeout(HttpResponseSubscriber.java:128)
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)
```

# Suggestion
Maybe need to call `responseFirstBytesTransferred` at `DefaultRequestLog.endResponse0(responseCause, responseEndTimeNanos)`?

**Comment by imasahiro** [comment]
cc: @mauhiz

**Comment by minwoox** [comment]
Thanks, @imasahiro for the report. But I'm not sure whether we should fill the time with the end response time or shouldn't call [`SpanTags.logWireReceive(...)`](https://github.com/line/armeria/blob/master/zipkin/src/main/java/com/linecorp/armeria/server/tracing/HttpTracingService.java#L93) when a request timed out.
@adriancole and @anuraaga, you guys have any thought?

**Comment by adriancole** [comment]
my thought is that the span finish() should be when the error occurred. If there's a timing method that can crash a request, we should call it carefully.

**Comment by anuraaga** [comment]
Sent a fix, I found two issues

- We do send a response when server times out, but didn't log it
- When client times out, we do need to ignore the response wire timing
