### ISSUE TITLE
Disabled OpenSSL raises ALPN unsupported: use Conscrypt

### ISSUE THREAD

**Issue by gquintana** [line/armeria#1772]
When I run Armeria 0.84 with `-Dcom.linecorp.armeria.useOpenSsl=false` I get the following error:

```
2019-05-15T19:23:14,920 WARN  com.linecorp.armeria.common.util.Exceptions - [id: 0x89878206, L:/10.122.135.222:9411 ! R:/10.121.199.16:36088] Unexpected exception:
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: ALPN unsupported. Is your classpath configured correctly? For Conscrypt, add the appropriate Conscrypt JAR to classpath and set the security provider. For Jetty-ALPN, see http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-starting
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472) ~[netty-codec-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:405) ~[netty-codec-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:372) ~[netty-codec-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355) ~[netty-codec-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1403) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:912) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:827) [netty-transport-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333) [netty-transport-native-epoll-4.1.34.Final-linux-x86_64.jar!/:4.1.34.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) [netty-common-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.34.Final.jar!/:4.1.34.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.RuntimeException: ALPN unsupported. Is your classpath configured correctly? For Conscrypt, add the appropriate Conscrypt JAR to classpath and set the security provider. For Jetty-ALPN, see http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-starting
        at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator$FailureWrapper.wrapSslEngine(JdkAlpnApplicationProtocolNegotiator.java:122) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.JdkSslContext.configureAndWrapEngine(JdkSslContext.java:361) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.JdkSslContext.newEngine(JdkSslContext.java:331) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.SslContext.newHandler(SslContext.java:896) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.SslContext.newHandler(SslContext.java:888) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.SniHandler.newSslHandler(SniHandler.java:151) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.SniHandler.replaceHandler(SniHandler.java:133) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.SniHandler.onLookupComplete(SniHandler.java:114) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.AbstractSniHandler.select(AbstractSniHandler.java:229) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.ssl.AbstractSniHandler.decode(AbstractSniHandler.java:221) ~[netty-handler-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-codec-4.1.34.Final.jar!/:4.1.34.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-codec-4.1.34.Final.jar!/:4.1.34.Final]
        ... 21 more
```
If I add the Conscrypt JAR to the classpath, SSL will based on BoringSSL, so there is no benefit in using the aforementioned flag.

Is it possible to use Armeria with JDK8 SSL engine?

**Comment by anuraaga** [comment]
@gquintana Thanks for raising this issue. Armeria is an HTTP/2 server and does require ALPN to be able to serve HTTP/1 connections using ALPN upgrade. While it's often simplest to either use JVM9+ or boringssl, if you'd like to use Java 8's SSL engine, it's possible by adding Jetty ALPN to your bootclasspath. Check out ALPN and OpenJDK 8 here - https://www.eclipse.org/jetty/documentation/9.4.x/alpn-chapter.html
