### ISSUE TITLE
Failed to parse the media type in 'accept' header: *; q=.2

### ISSUE THREAD

**Issue by Adanz** [line/armeria#1849]
I use armeria-tomcat service, version 0.87, Configures an Armeria to redirect the incoming requests to the Tomcat instance provided by Spring Boot. like: examples\spring-boot-tomcat
And Client use java.net.HttpURLConnection, but found below failed issue:

019-06-18 16:14:06.728 [armeria-common-worker-nio-5-1] DEBUG com.linecorp.armeria.server.DefaultRoutingContext - Failed to parse the media type in 'accept' header: *; q=.2
java.lang.IllegalArgumentException: Could not parse '*; q=.2'
	at com.linecorp.armeria.common.MediaType.parse(MediaType.java:994)
	at com.linecorp.armeria.server.DefaultRoutingContext.lambda$extractAcceptTypes$0(DefaultRoutingContext.java:177)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.linecorp.armeria.server.DefaultRoutingContext.lambda$extractAcceptTypes$1(DefaultRoutingContext.java:174)
	at com.linecorp.armeria.internal.shaded.guava.collect.ImmutableList.forEach(ImmutableList.java:405)
	at com.linecorp.armeria.server.DefaultRoutingContext.extractAcceptTypes(DefaultRoutingContext.java:173)
	at com.linecorp.armeria.server.DefaultRoutingContext.of(DefaultRoutingContext.java:57)
	at com.linecorp.armeria.server.HttpServerHandler.handleRequest(HttpServerHandler.java:329)
	at com.linecorp.armeria.server.HttpServerHandler.channelRead(HttpServerHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at com.linecorp.armeria.server.Http1RequestDecoder.channelRead(Http1RequestDecoder.java:185)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:249)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: null
	at com.linecorp.armeria.internal.shaded.guava.base.Preconditions.checkState(Preconditions.java:492)
	at com.linecorp.armeria.common.MediaType$Tokenizer.consumeCharacter(MediaType.java:1030)
	at com.linecorp.armeria.common.MediaType.parse(MediaType.java:964)
	... 62 common frames omitted
2019-06-18 16:14:06.790 [armeria-common-worker-nio-5-1] INFO  armeria.services.api.test - [id: 0xf2709a41, L:/127.0.0.1:8096 - R:/127.0.0.1:64177][h1c://xxxxxx:8096/api/test/login#POST] Request: {startTime=2019-06-18T08:14:06.743Z(1560845646743000), length=114B, duration=24607µs(24607248ns), scheme=none+h1c, headers=[:method=POST, :path=/api/test/login, :scheme=http, :authority=localhost:8096, content-type=application/json, authorization=Bearer 123, user-agent=Java/1.8.0_161, accept=text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2, content-length=114]}

what can I do? thank.

**Comment by trustin** [comment]
Hi @Adanz! Thanks for reporting a bug. IIUC there's no workaround for this issue. Let us fix and release a new version soon.

**Comment by trustin** [comment]
We could also try to parse the headers related with content type negotiation only when necessay, perhaps using lazy initialization.

**Comment by trustin** [comment]
Offending header: accept=text/html, image/gif, image/jpeg, *; q=.2, /; q=.2

We could replace * and / with * / * when parsing fails.

**Comment by minwoox** [comment]
I found out that it's just a `DEBUG` log while parsing the `Accept` header and I think you don't have to worry about it.
The logic splits the header using `,` as the delimiter and it just gathers the values which were parsed successfully.
So `accept=text/html, image/gif, image/jpeg, *; q=.2, /; q=.2` this will be the list of `['text/html', 'image/gif', 'image/jpeg']` and Armeria uses it for the content negatiation.
So I think we only need to add a logic that parses the header only when it's necessary as @trustin said.

**Comment by minwoox** [comment]
And perhaps we could lower the log level to `TRACE`?

**Comment by trustin** [comment]
Yeah, and we could also make the log message more comprehensive, e.g. 

    Ignoring a malformed media type from 'accept': /; q=.2
