### ISSUE TITLE
FieldValueMetaData cannot be cast to org.apache.thrift.meta_data.StructMetaData

### ISSUE THREAD

**Issue by xiemeilong** [line/armeria#187]
```
Caused by: java.lang.ClassCastException: org.apache.thrift.meta_data.FieldValueMetaData cannot be cast to org.apache.thrift.meta_data.StructMetaData
	at com.linecorp.armeria.common.thrift.ThriftUtil.toJavaType(ThriftUtil.java:82)
	at com.linecorp.armeria.server.thrift.ThriftFunction.<init>(ThriftFunction.java:106)
	at com.linecorp.armeria.server.thrift.ThriftFunction.<init>(ThriftFunction.java:52)
	at com.linecorp.armeria.server.thrift.ThriftServiceCodec.registerFunction(ThriftServiceCodec.java:146)
```

**Comment by trustin** [comment]
Fixed already.

**Comment by trustin** [comment]
Ugh, I guess not. Could you elaborate on how this exception is triggered?

**Comment by trustin** [comment]
@xiemeilong For example, you could provide us the IDL that reproduces the problem.

**Comment by xiemeilong** [comment]
@trustin This exception is gone by put the service after all messages in thrift file,  so I closed the issue. I don't know why.
