### ISSUE TITLE
NPE in HttpSessionHandler.channelInactive with JRE11

### ISSUE THREAD

**Issue by mauhiz** [line/armeria#2010]
The following issue is reproduced on latest armeria (0.90.x) with openjdk 11.0.2 when the remote server requires a downgrade from HTTP2 to H1C :

```
java.lang.NullPointerException: remoteAddress
	at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:33)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:141)
	at com.linecorp.armeria.client.HttpChannelPool.connect(HttpChannelPool.java:347)
	at com.linecorp.armeria.client.HttpSessionHandler.channelInactive(HttpSessionHandler.java:306)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:236)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:393)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:358)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.channelInactive(Http2ConnectionHandler.java:415)
```

It appears that the Channel's remoteAddress is not set. (requestedRemoteAddress is set though)

This cannot be reproduced e.g. with oracle 10.0.2 where remoteAddress = requestedRemoteAddress

It could be an issue with netty (interop with recent openJDKs) or with the way Armeria uses Netty.

**Comment by mauhiz** [comment]
Debugging through, remoteAddress is `null` because the underlying socket is not connected.
<img width="563" alt="Screen Shot 2019-08-21 at 21 28 14" src="https://user-images.githubusercontent.com/1818187/63431782-9d7fa600-c45a-11e9-860c-494e37b3045d.png">

**Comment by trustin** [comment]
It's interesting that we did not see this problem before since we run our builds on Java 11. Is this always reproduced? What happens if you use a newer JRE such as AdoptOpenJDK 11.0.3+?

**Comment by mauhiz** [comment]
> Is this always reproduced?

Yes so far

> Newer JRE

The JRE I tested with is 

```
brew cask info java11
java11: 11.0.2,9
```
```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

I suppose this is an Oracle build.

Let me try with an AdaptOpenJDK build.

**Comment by mauhiz** [comment]
Reproduced with 
```
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
```

**Comment by mauhiz** [comment]
I'm wondering whether this is related to the platform since we didn't find any issue on CentOS, but it is reproducible on our macs.

**Comment by delegacy** [comment]
I have the same issue on my mac.
Is there any chance that it is related to different `Channel` implementation between platforms? `EpollChannel` vs. `NioChannel`

**Comment by trustin** [comment]
@minwoox @ikhoon I'm not using OS X, so could you guys take a look into this?

**Comment by minwoox** [comment]
Yeah, let me figure it out.

**Comment by ikhoon** [comment]
I also explore this issue .

**Comment by delegacy** [comment]
Checked that the issue is not reproduced anymore with the current master. (AdoptOpenJDK11, AdoptOpenJDK12)

**Comment by minwoox** [comment]
Thanks for checking it @delegacy!
