### ISSUE TITLE
RetryingClient does not have a child request if a root request is already done

### ISSUE THREAD

**Issue by imasahiro** [line/armeria#2082]
I'm pretty not sure how to reproduce it but here is the stacktrace from our service.

* OS: Linux
* Client: Armeria-0.91.0
* Server: Armeria-0.88.0

```
Caused by: java.lang.IllegalStateException: at least one child should be already added
	at com.linecorp.armeria.internal.shaded.guava.base.Preconditions.checkState(Preconditions.java:508)
	at com.linecorp.armeria.common.logging.DefaultRequestLog.endResponseWithLastChild(DefaultRequestLog.java:234)
	at com.linecorp.armeria.client.retry.RetryingClient.onRetryingComplete(RetryingClient.java:128)
	at com.linecorp.armeria.client.retry.RetryingHttpClient.handleException(RetryingHttpClient.java:204)
	at com.linecorp.armeria.client.retry.RetryingHttpClient.doExecute0(RetryingHttpClient.java:151)
	at com.linecorp.armeria.client.retry.RetryingHttpClient.doExecute(RetryingHttpClient.java:141)
	at com.linecorp.armeria.client.retry.RetryingHttpClient.doExecute(RetryingHttpClient.java:58)
	at com.linecorp.armeria.client.retry.RetryingClient.execute(RetryingClient.java:115)
	at com.linecorp.armeria.client.metric.MetricCollectingClient.execute(MetricCollectingClient.java:73)
	at com.linecorp.armeria.client.tracing.HttpTracingClient.execute(HttpTracingClient.java:154)
	at com.linecorp.armeria.client.tracing.HttpTracingClient.execute(HttpTracingClient.java:63)
	at com.linecorp.armeria.internal.ClientUtil.pushAndExecute(ClientUtil.java:82)
	at com.linecorp.armeria.internal.ClientUtil.initContextAndExecuteWithFallback(ClientUtil.java:51)
	at com.linecorp.armeria.client.UserClient.execute(UserClient.java:148)
	at com.linecorp.armeria.client.DefaultHttpClient.execute(DefaultHttpClient.java:99)
	at com.linecorp.armeria.client.DefaultHttpClient.execute(DefaultHttpClient.java:90)
	at com.linecorp.armeria.client.DefaultHttpClient.execute(DefaultHttpClient.java:117)
	at com.linecorp.armeria.client.DefaultHttpClient.execute(DefaultHttpClient.java:113)
	at com.linecorp.armeria.client.HttpClient.execute(HttpClient.java:217)
	at com.linecorp.armeria.client.HttpClient.get(HttpClient.java:259)
```

**Comment by minwoox** [comment]
Will investigate it soon. Thanks!
