### ISSUE TITLE
Dedup request path parsing at HttpClient

### ISSUE THREAD

**Issue by imasahiro** [line/armeria#2171]
When we send a request using `HttpClient`, this http client parse a path name using `PathAndQuery.parse`.
```
at com.linecorp.armeria.internal.PathAndQuery.parse(PathAndQuery.java:122)
at com.linecorp.armeria.client.DefaultHttpClient.execute(DefaultHttpClient.java:94)
at com.linecorp.armeria.client.DefaultHttpClient.execute(DefaultHttpClient.java:90)
at com.linecorp.armeria.client.DefaultHttpClient.execute(DefaultHttpClient.java:117)
at com.linecorp.armeria.client.DefaultHttpClient.execute(DefaultHttpClient.java:113)
at com.linecorp.armeria.client.HttpClient.execute(HttpClient.java:217)
at com.linecorp.armeria.client.HttpClient.get(HttpClient.java:259)
```

And because parse result is not cached into PathAndQuery's CACHE, armeria client try to parse the path again at `HttpClientDelegate`.

```
at com.linecorp.armeria.internal.PathAndQuery.parse(PathAndQuery.java:122)
at com.linecorp.armeria.client.HttpClientDelegate.isValidPath(HttpClientDelegate.java:200)
at com.linecorp.armeria.client.HttpClientDelegate.execute(HttpClientDelegate.java:69)
at com.linecorp.armeria.client.HttpClientDelegate.execute(HttpClientDelegate.java:42)
at com.linecorp.armeria.internal.ClientUtil.pushAndExecute(ClientUtil.java:86)
at com.linecorp.armeria.internal.ClientUtil.initContextAndExecuteWithFallback(ClientUtil.java:49)
at com.linecorp.armeria.client.UserClient.execute(UserClient.java:160)
at com.linecorp.armeria.client.DefaultHttpClient.execute(DefaultHttpClient.java:99)
```

It would be better to avoid duplicated parsing at `DefaultHttpClient`.

**Comment by imasahiro** [comment]
Note that, this is not happened at DefaultTHttpClient because it caches `PathAndQuery` result already.

**Comment by anuraaga** [comment]
I missed this issue - for `Service` we can opt a generic HTTP service in with this method

https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/server/Service.java#L116

For `Client`, I think we can have a similar knob as a `ClientOption` - how does that sound? @imasahiro @trustin
