### ISSUE TITLE
RequestContextCurrentTraceContext warns when using with `spring-data-redis-starter` and `spring-cloud-starter-zipkin`

### ISSUE THREAD

**Issue by alex-lx** [line/armeria#2181]
The Armeria using the shared `Tracing` instance created by the sleuth-starter. Is it encouraged or necessary to use two `Tracing` instance for each of them?
Here's the log
```
2019-10-11 10:20:07.035 WARN  [RMI TCP Connection(4)-10.0.5.2] c.l.a.c.b.RequestContextCurrentTraceContext Attempted to propagate trace context, but no request context available. Did you forget to use RequestContext.contextAwareExecutor() or RequestContext.makeContextAware()?
com.linecorp.armeria.common.brave.RequestContextCurrentTraceContext$LogRequestContextWarningOnce$NoRequestContextException: null
	at com.linecorp.armeria.common.brave.RequestContextCurrentTraceContext$LogRequestContextWarningOnce$ClassLoaderHack.<clinit>(RequestContextCurrentTraceContext.java:266)
	at com.linecorp.armeria.common.brave.RequestContextCurrentTraceContext$LogRequestContextWarningOnce.get(RequestContextCurrentTraceContext.java:254)
	at com.linecorp.armeria.common.brave.RequestContextCurrentTraceContext$LogRequestContextWarningOnce.get(RequestContextCurrentTraceContext.java:247)
	at com.linecorp.armeria.common.RequestContext.mapCurrent(RequestContext.java:108)
	at com.linecorp.armeria.common.brave.RequestContextCurrentTraceContext.getRequestContextOrWarnOnce(RequestContextCurrentTraceContext.java:232)
	at com.linecorp.armeria.common.brave.RequestContextCurrentTraceContext.get(RequestContextCurrentTraceContext.java:143)
	at brave.Tracer.currentSpan(Tracer.java:440)
	at org.springframework.cloud.sleuth.instrument.reactor.ReactorSleuth.scopePassingSpanSubscription(ReactorSleuth.java:113)
	at org.springframework.cloud.sleuth.instrument.reactor.ReactorSleuth.lambda$scopePassingSpanOperator$1(ReactorSleuth.java:87)
	at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:41)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3590)
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:3696)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3584)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3551)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3523)
	at io.lettuce.core.AbstractRedisClient.initializeChannelAsync(AbstractRedisClient.java:289)
	at io.lettuce.core.RedisClient.connectStatefulAsync(RedisClient.java:314)
	at io.lettuce.core.RedisClient.connectStandaloneAsync(RedisClient.java:271)
	at io.lettuce.core.RedisClient.connect(RedisClient.java:204)
	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.lambda$getConnection$1(StandaloneConnectionProvider.java:113)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.getConnection(StandaloneConnectionProvider.java:113)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection(LettuceConnectionFactory.java:1085)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getConnection(LettuceConnectionFactory.java:1065)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getSharedReactiveConnection(LettuceConnectionFactory.java:875)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getReactiveConnection(LettuceConnectionFactory.java:376)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getReactiveConnection(LettuceConnectionFactory.java:90)
	at org.springframework.boot.actuate.redis.RedisReactiveHealthIndicator.doHealthCheck(RedisReactiveHealthIndicator.java:48)
	at org.springframework.boot.actuate.health.AbstractReactiveHealthIndicator.health(AbstractReactiveHealthIndicator.java:34)
	at org.springframework.boot.actuate.autoconfigure.health.HealthIndicatorRegistryBeans$ReactiveHealthIndicators.lambda$adapt$1(HealthIndicatorRegistryBeans.java:61)
	at org.springframework.boot.actuate.health.CompositeHealthIndicator.health(CompositeHealthIndicator.java:98)
	at org.springframework.boot.actuate.health.HealthEndpoint.health(HealthEndpoint.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:244)
	at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:76)
	at org.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:61)
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:126)
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:99)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

And the dependencies(part):
```groovy
    [
            'armeria-grpc',
            'armeria-tomcat',
            'armeria-logback',
            'armeria-rxjava',
            'armeria-spring-boot-starter',
            'armeria-spring-boot-actuator-starter',
            'armeria-brave'
    ].each {
        implementation("com.linecorp.armeria:${it}")
    }
    implementation('org.springframework.boot:spring-boot-starter-actuator')
    implementation('org.springframework.boot:spring-boot-starter-data-redis')
    implementation('org.springframework.cloud:spring-cloud-starter-sleuth')
    implementation('org.springframework.cloud:spring-cloud-starter-zipkin')
```
And some spring configuration:
```java
    @Bean
    CurrentTraceContext.Builder currentTraceContext() {
        return RequestContextCurrentTraceContext.builder();
    }
```

**Comment by anuraaga** [comment]
It looks like this stacktrace is for a RMI fetch of the health of the server - Armeria traces usually start with the Armeria server, and that log message is to indicate if you accidentally did not propagate the context during the request.

We added https://line.github.io/armeria/apidocs/com/linecorp/armeria/common/brave/RequestContextCurrentTraceContext.html#setCurrentThreadNotRequestThread(boolean) to be called when creating threads that start traces outside the context of the server. But I guess we can't use it for RMI threads... so we need to finally add the suggestion we got earlier from @adriancole to be able to whitelist threads by name for this log message.

Just to confirm, do you see any other issues with the tracing? That error message, while should be silenced, does not indicate anything is wrong so hopefully it's working fine.

**Comment by alex-lx** [comment]
> Just to confirm, do you see any other issues with the tracing? That error message, while should be silenced, does not indicate anything is wrong so hopefully it's working fine.

No any other yet. And our service works fine AFAIK, just post this to look for any way to stop the noisy logging.

And as motioned in the issue description,  is it encouraged or necessary to use two Tracing instances, one for armeria request-threads and one for others?

**Comment by anuraaga** [comment]
Nah, it's discouraged to use two, you should only use one instance in your app. Otherwise, things initialized by spring (like this Redis client I think) will not be able to participate in server traces started from services hosted by Armeria.
