### ISSUE TITLE
`ClassCastException` while building a `Client` with additional headers

### ISSUE THREAD

**Issue by trustin** [line/armeria#2190]
```
Caused by: java.lang.ClassCastException: com.linecorp.armeria.common.HttpHeadersBase cannot be cast to com.linecorp.armeria.common.HttpHeaders
    at com.linecorp.armeria.common.DefaultHttpHeadersBuilder.build(DefaultHttpHeadersBuilder.java:38)
    at com.linecorp.armeria.client.AbstractClientOptionsBuilder.buildOptions(AbstractClientOptionsBuilder.java:430)
    at com.linecorp.armeria.client.ClientBuilder.build(ClientBuilder.java:162)
```

**Comment by trustin** [comment]
Occurs when `ClientBuilder.build()` is called twice. :scream:
