### ISSUE TITLE
Flaky test: DnsAddressEndpointGroupTest.backoff

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#2315]
Found at: https://ci.appveyor.com/project/line/armeria/builds/29459636/job/laf55hgwbaktsfg2#L1168

```
com.linecorp.armeria.client.endpoint.dns.DnsAddressEndpointGroupTest > backoff FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in com.linecorp.armeria.client.endpoint.dns.DnsAddressEndpointGroupTest that uses com.linecorp.armeria.client.endpoint.dns.DnsAddressEndpointGroup 
    Expecting:
      <[Endpoint{backoff.com, ipAddr=::1, weight=1000}]>
    to contain exactly (and in same order):
      <[Endpoint{backoff.com, ipAddr=1.1.1.1, weight=1000},
        Endpoint{backoff.com, ipAddr=::1, weight=1000}]>
    but could not find the following elements:
      <[Endpoint{backoff.com, ipAddr=1.1.1.1, weight=1000}]>
     within 10 seconds.
        at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:148)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:873)
        at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:657)
        at com.linecorp.armeria.client.endpoint.dns.DnsAddressEndpointGroupTest.backoff(DnsAddressEndpointGroupTest.java:248)
        Caused by:
        java.lang.AssertionError: 
        Expecting:
          <[Endpoint{backoff.com, ipAddr=::1, weight=1000}]>
        to contain exactly (and in same order):
          <[Endpoint{backoff.com, ipAddr=1.1.1.1, weight=1000},
            Endpoint{backoff.com, ipAddr=::1, weight=1000}]>
        but could not find the following elements:
          <[Endpoint{backoff.com, ipAddr=1.1.1.1, weight=1000}]>
            at com.linecorp.armeria.client.endpoint.dns.DnsAddressEndpointGroupTest.lambda$backoff$1(DnsAddressEndpointGroupTest.java:248)
```

**Comment by minwoox** [comment]
```java
com.linecorp.armeria.client.endpoint.dns.DnsAddressEndpointGroupTest > backoffOnEmptyResponse FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in com.linecorp.armeria.client.endpoint.dns.DnsAddressEndpointGroupTest that uses com.linecorp.armeria.client.endpoint.dns.DnsAddressEndpointGroup 
    Expecting:
      <[Endpoint{empty.com, ipAddr=::1, weight=1000}]>
    to contain exactly (and in same order):
      <[Endpoint{empty.com, ipAddr=1.1.1.1, weight=1000},
        Endpoint{empty.com, ipAddr=::1, weight=1000}]>
    but could not find the following elements:
      <[Endpoint{empty.com, ipAddr=1.1.1.1, weight=1000}]>
     within 10 seconds.
        at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:148)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:873)
        at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:657)
        at com.linecorp.armeria.client.endpoint.dns.DnsAddressEndpointGroupTest.backoffOnEmptyResponse(DnsAddressEndpointGroupTest.java:279)
        Caused by:
        java.lang.AssertionError: 
        Expecting:
          <[Endpoint{empty.com, ipAddr=::1, weight=1000}]>
        to contain exactly (and in same order):
          <[Endpoint{empty.com, ipAddr=1.1.1.1, weight=1000},
            Endpoint{empty.com, ipAddr=::1, weight=1000}]>
        but could not find the following elements:
          <[Endpoint{empty.com, ipAddr=1.1.1.1, weight=1000}]>
            at com.linecorp.armeria.client.endpoint.dns.DnsAddressEndpointGroupTest.lambda$backoffOnEmptyResponse$3(DnsAddressEndpointGroupTest.java:279)
```

**Comment by trustin** [comment]
There's an inevitable race condition in this test because `A` and `AAAA` responses can't be sent in a single response in DNS. (There's `ANY` question, but we don't use it because of how DNS servers work - (UDP truncation, etc).)
