### ISSUE TITLE
Unexpected Exception when pushing`RequestContext`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#2414]
While testing gRPC server & client, I saw the following exception with `WARN` message. 
```java
[armeria-common-worker-nio-2-1] WARN  i.n.util.concurrent.DefaultPromise - An exception was thrown by com.linecorp.armeria.server.HttpResponseSubscriber$$Lambda$630/0x000000080153f040.operationComplete()
java.lang.IllegalStateException: Trying to call object wrapped with context [S][id: 0x36589007, L:/127.0.0.1:54739 - R:/127.0.0.1:54740][h2c://ihi.local:54739/armeria.GithubService/Simple#POST], but context is currently set to [S][id: 0x36589007, L:/127.0.0.1:54739 - R:/127.0.0.1:54740][h2c://ihi.local:54739/armeria.GithubService/Simple#POST]. This means the callback was called from unexpected thread or forgetting to close previous context.
	at com.linecorp.armeria.internal.RequestContextUtil.newIllegalContextPushingException(RequestContextUtil.java:46)
	at com.linecorp.armeria.server.ServiceRequestContext.push(ServiceRequestContext.java:228)
	at com.linecorp.armeria.common.logging.RequestLogListenerInvoker.invokeOnRequestLog(RequestLogListenerInvoker.java:58)
	at com.linecorp.armeria.common.logging.DefaultRequestLog.updateAvailability(DefaultRequestLog.java:985)
	at com.linecorp.armeria.common.logging.DefaultRequestLog.endResponse0(DefaultRequestLog.java:961)
	at com.linecorp.armeria.common.logging.DefaultRequestLog.endResponse0(DefaultRequestLog.java:940)
	at com.linecorp.armeria.common.logging.DefaultRequestLog.endResponse(DefaultRequestLog.java:921)
	at com.linecorp.armeria.server.HttpResponseSubscriber.lambda$write$1(HttpResponseSubscriber.java:325)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.handler.codec.http2.Http2CodecUtil$SimpleChannelPromiseAggregator.tryPromise(Http2CodecUtil.java:383)
	at io.netty.handler.codec.http2.Http2CodecUtil$SimpleChannelPromiseAggregator.trySuccess(Http2CodecUtil.java:349)
	at io.netty.handler.codec.http2.Http2CodecUtil$SimpleChannelPromiseAggregator.trySuccess(Http2CodecUtil.java:261)
	at io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48)
	at io.netty.channel.ChannelOutboundBuffer.safeSuccess(ChannelOutboundBuffer.java:715)
	at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:270)
	at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:350)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:431)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:898)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1384)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727)
	at io.netty.handler.flush.FlushConsolidationHandler.flushNow(FlushConsolidationHandler.java:206)
	at io.netty.handler.flush.FlushConsolidationHandler.flush(FlushConsolidationHandler.java:140)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727)
	at com.linecorp.armeria.internal.TrafficLoggingHandler.flush(TrafficLoggingHandler.java:49)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:189)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727)
	at com.linecorp.armeria.server.HttpResponseSubscriber.write(HttpResponseSubscriber.java:342)
	at com.linecorp.armeria.server.HttpResponseSubscriber.onNext(HttpResponseSubscriber.java:225)
	at com.linecorp.armeria.server.HttpResponseSubscriber.onNext(HttpResponseSubscriber.java:59)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberWithElements(DefaultStreamMessage.java:341)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:319)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:252)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:238)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.addObject(DefaultStreamMessage.java:158)
	at com.linecorp.armeria.common.stream.AbstractStreamMessageAndWriter.tryWrite(AbstractStreamMessageAndWriter.java:74)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.tryWrite(DefaultStreamMessage.java:63)
	at com.linecorp.armeria.common.stream.StreamWriter.write(StreamWriter.java:71)
	at com.linecorp.armeria.server.grpc.ArmeriaServerCall.doSendHeaders(ArmeriaServerCall.java:242)
	at com.linecorp.armeria.server.grpc.ArmeriaServerCall.sendHeaders(ArmeriaServerCall.java:208)
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:348)
	at com.linecorp.armeria.it.grpc.GithubApiService.simple(GithubApiService.java:47)
	at com.linecorp.armeria.grpc.GithubServiceGrpc$MethodHandlers.invoke(GithubServiceGrpc.java:277)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
	at com.linecorp.armeria.server.grpc.ArmeriaServerCall.invokeHalfClose(ArmeriaServerCall.java:436)
	at com.linecorp.armeria.server.grpc.ArmeriaServerCall.endOfStream(ArmeriaServerCall.java:429)
	at com.linecorp.armeria.common.grpc.protocol.ArmeriaMessageDeframer.close(ArmeriaMessageDeframer.java:313)
	at com.linecorp.armeria.common.grpc.protocol.ArmeriaMessageDeframer.closeWhenComplete(ArmeriaMessageDeframer.java:293)
	at com.linecorp.armeria.internal.grpc.HttpStreamReader.closeDeframer(HttpStreamReader.java:204)
	at com.linecorp.armeria.internal.grpc.HttpStreamReader.apply(HttpStreamReader.java:183)
	at com.linecorp.armeria.internal.grpc.HttpStreamReader.apply(HttpStreamReader.java:48)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

The error can be reproduced by executing the `simpleNonBlocking` test with 20% chance.
https://github.com/line/armeria/blob/08afa31fbe512e65a2e38bfcd6a3315ed313c241/grpc/src/test/java/com/linecorp/armeria/it/grpc/DownstreamSimpleBenchmarkTest.java#L95-L113

**Comment by minwoox** [comment]
😱

**Comment by minwoox** [comment]
I fount the cause. Will send a PR soon.
