### ISSUE TITLE
Intermittent test failure in ZooKeeperRegistrationTest

### ISSUE THREAD

**Issue by minwoox** [line/armeria#2428]
```
com.linecorp.armeria.server.zookeeper.ZooKeeperRegistrationTest > testServerNodeCreateAndDelete FAILED
    java.util.concurrent.CompletionException: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
        at java.base/java.util.concurrent.CompletableFuture.reportJoin(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.join(Unknown Source)
        at com.linecorp.armeria.common.util.EventLoopCheckingFuture.join(EventLoopCheckingFuture.java:70)
        at com.linecorp.armeria.server.zookeeper.ZooKeeperRegistrationTest.startServers(ZooKeeperRegistrationTest.java:67)
        Caused by:
        io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
```

**Comment by minwoox** [comment]
```
ZooKeeperRegistrationTest > legacyZooKeeperRegistrationSpec() FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a com.linecorp.armeria.server.zookeeper.ZooKeeperRegistrationTest null within 10 seconds.
        at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:166)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:939)
        at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:723)
        at com.linecorp.armeria.server.zookeeper.ZooKeeperRegistrationTest.legacyZooKeeperRegistrationSpec(ZooKeeperRegistrationTest.java:79)

        Caused by:
        java.util.concurrent.TimeoutException
            at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
            at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:101)
            at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:81)
            at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:102)
            ... 5 more

```
