### ISSUE TITLE
Flaky test: BraveClientIntegrationTest

### ISSUE THREAD

**Issue by minwoox** [line/armeria#2534]
```
BraveClientIntegrationTest > asyncRootSpan[1] FAILED
    org.opentest4j.AssertionFailedError: 
    Expecting:
     <698454d500542dc9/698454d500542dc9>
    to be equal to:
     <null>
    but was not.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at brave.test.http.ITHttpAsyncClient.asyncRootSpan(ITHttpAsyncClient.java:142)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by ikhoon** [comment]
I found another flaky test.
https://ci.appveyor.com/project/line/armeria/builds/31090681/job/vspwvmq1aa2d17jr#L626
```
BraveClientIntegrationTest > makesChildOfCurrentSpan[0] FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 5 seconds
        at app//io.netty.handler.ssl.ReferenceCountedOpenSslEngine.<init>(ReferenceCountedOpenSslEngine.java:239)
        at app//io.netty.handler.ssl.OpenSslEngine.<init>(OpenSslEngine.java:32)
        at app//io.netty.handler.ssl.OpenSslContext.newEngine0(OpenSslContext.java:49)
        at app//io.netty.handler.ssl.ReferenceCountedOpenSslContext.newEngine(ReferenceCountedOpenSslContext.java:386)
        at app//io.netty.handler.ssl.ReferenceCountedOpenSslContext.newEngine(ReferenceCountedOpenSslContext.java:419)
        at app//com.linecorp.armeria.internal.common.util.SslContextUtil.supportedProtocols(SslContextUtil.java:158)
        at app//com.linecorp.armeria.internal.common.util.SslContextUtil.lambda$createSslContext$2(SslContextUtil.java:96)
        at app//com.linecorp.armeria.internal.common.util.SslContextUtil$$Lambda$361/0x000000010032dc40.get(Unknown Source)
        at app//com.linecorp.armeria.internal.common.util.BouncyCastleKeyFactoryProvider.call(BouncyCastleKeyFactoryProvider.java:69)
        at app//com.linecorp.armeria.internal.common.util.SslContextUtil.createSslContext(SslContextUtil.java:91)
        at app//com.linecorp.armeria.client.HttpClientFactory.<init>(HttpClientFactory.java:128)
        at app//com.linecorp.armeria.client.ClientFactoryBuilder.build(ClientFactoryBuilder.java:551)
        at app//com.linecorp.armeria.client.DefaultClientFactory.<clinit>(DefaultClientFactory.java:62)
        at app//com.linecorp.armeria.client.ClientFactory.<clinit>(ClientFactory.java:78)
        at app//com.linecorp.armeria.client.ClientOption.<clinit>(ClientOption.java:49)
        at app//com.linecorp.armeria.client.AbstractClientOptionsBuilder.buildOptions(AbstractClientOptionsBuilder.java:373)
        at app//com.linecorp.armeria.client.AbstractClientOptionsBuilder.buildOptions(AbstractClientOptionsBuilder.java:362)
        at app//com.linecorp.armeria.client.WebClientBuilder.build(WebClientBuilder.java:152)
        at app//com.linecorp.armeria.client.brave.BraveClientIntegrationTest.newClient(BraveClientIntegrationTest.java:89)
        at app//com.linecorp.armeria.client.brave.BraveClientIntegrationTest.newClient(BraveClientIntegrationTest.java:49)
        at app//brave.test.http.ITHttpClient.setup(ITHttpClient.java:51)
        at app//com.linecorp.armeria.client.brave.BraveClientIntegrationTest.setup(BraveClientIntegrationTest.java:77)
```
