### ISSUE TITLE
`Maximum active streams violated for this endpoint` error under load

### ISSUE THREAD

**Issue by trustin** [line/armeria#2593]
Not exactly sure, but it seems to occur when clients attempt to make many requests all of sudden.

```
2020-03-14 20:30:32.610  WARN 49385 --- [-] [armeria-common-worker-epoll-2-22] c.l.a.client.HttpRequestSubscriber [...] Unexpected exception:
io.netty.handler.codec.http2.Http2Exception$StreamException: Maximum active streams violated for this endpoint.
        at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:147)
        at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.checkNewStreamAllowed(DefaultHttp2Connection.java:896)
        at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:748)
        at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:668)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders0(DefaultHttp2ConnectionEncoder.java:201)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:151)
        at io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writeHeaders(DecoratingHttp2FrameWriter.java:45)
        at com.linecorp.armeria.internal.Http2ObjectEncoder.doWriteHeaders(Http2ObjectEncoder.java:73)
        at com.linecorp.armeria.internal.HttpObjectEncoder.writeHeaders(HttpObjectEncoder.java:56)
        at com.linecorp.armeria.client.HttpRequestSubscriber.write0(HttpRequestSubscriber.java:298)
        at com.linecorp.armeria.client.HttpRequestSubscriber.writeFirstHeader(HttpRequestSubscriber.java:183)
        at com.linecorp.armeria.client.HttpRequestSubscriber.onSubscribe(HttpRequestSubscriber.java:161)
        at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$DownstreamSubscription.invokeOnSubscribe(AbstractStreamMessageDuplicator.java:739)
        at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$StreamMessageProcessor.doSubscribe(AbstractStreamMessageDuplicator.java:330)
        at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$StreamMessageProcessor.subscribe(AbstractStreamMessageDuplicator.java:307)
        at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$ChildStreamMessage.subscribe0(AbstractStreamMessageDuplicator.java:581)
        at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$ChildStreamMessage.subscribe(AbstractStreamMessageDuplicator.java:569)
        at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$ChildStreamMessage.subscribe(AbstractStreamMessageDuplicator.java:559)
        at com.linecorp.armeria.common.stream.StreamMessageWrapper.subscribe(StreamMessageWrapper.java:105)
        at com.linecorp.armeria.client.HttpSessionHandler.invoke(HttpSessionHandler.java:161)
        at com.linecorp.armeria.client.HttpClientDelegate.doExecute(HttpClientDelegate.java:234)
        at com.linecorp.armeria.client.HttpClientDelegate.lambda$acquireConnectionAndExecute$2(HttpClientDelegate.java:142)
        at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
        at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at com.linecorp.armeria.client.HttpChannelPool.lambda$usePendingAcquisition$4(HttpChannelPool.java:276)
        at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
        at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at com.linecorp.armeria.client.HttpChannelPool.notifyConnect(HttpChannelPool.java:419)
        at com.linecorp.armeria.client.HttpChannelPool.lambda$connect$5(HttpChannelPool.java:331)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
        at com.linecorp.armeria.client.HttpSessionHandler.userEventTriggered(HttpSessionHandler.java:277)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:344)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:330)
        at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:322)
        at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:117)
        at io.netty.handler.codec.ByteToMessageDecoder.userEventTriggered(ByteToMessageDecoder.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:344)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:330)
        at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:322)
        at io.netty.handler.logging.LoggingHandler.userEventTriggered(LoggingHandler.java:169)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:344)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:330)
        at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:322)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.userEventTriggered(DefaultChannelPipeline.java:1428)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:344)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:330)
        at io.netty.channel.DefaultChannelPipeline.fireUserEventTriggered(DefaultChannelPipeline.java:913)
        at com.linecorp.armeria.client.HttpClientPipelineConfigurator.lambda$finishSuccessfully$0(HttpClientPipelineConfigurator.java:348)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by jrhee17** [comment]
I looked into this since I thought this should be fixed by #2374 
Judging by the stacktrace, it seems like this is for version pre 0.98.2 (before this issue was addressed)

```
at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at com.linecorp.armeria.client.HttpChannelPool.lambda$usePendingAcquisition$4(HttpChannelPool.java:276)
```

**Comment by trustin** [comment]
@julnamoo Could you please confirm?

**Comment by julnamoo** [comment]
Sorry for the late reply. Currently, I use `0.98.7` and the error lo seems gone.
Thanks for your help!

**Comment by trustin** [comment]
Thanks for your confirmation, @julnamoo.
