### ISSUE TITLE
Failed executor meter registration with using reactor's scheduler metric

### ISSUE THREAD

**Issue by AmosDoan** [line/armeria#2605]
**Situation**

When I use reactor and enable scheduler metric (https://projectreactor.io/docs/core/release/api/reactor/core/scheduler/Schedulers.html#enableMetrics--), I got exception like below 

```
Caused by: java.lang.IllegalArgumentException: Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter named 'executor_seconds' containing tag keys [name, reactor_scheduler_id]. The meter you are attempting to register has keys [name].
```

When I check in reactor, it registered executor metric with additional tag key `reactor.scheduler.id` (https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/scheduler/SchedulerMetricDecorator.java#L70). meanwhile, Armeria registered executor metric without additional metric (https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/server/ServerConfig.java#L162)

So there is conflict. (I don't know why Prometheus has the constrain same meter should have same tags..)

**Suggestion**

In my case, although I don't use ArmeriaBlockingTaskExecutor, but the metric is registered. I was wondering if there would be flags whether using ArmeriaBlockingTaskExecutor

**Full stack trace** 

```
Caused by: java.lang.IllegalArgumentException: Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter named 'executor_seconds' containing tag keys [name, reactor_scheduler_id]. The meter you are attempting to register has keys [name].
 at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$collectorByName$9(PrometheusMeterRegistry.java:382)
 at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1932)
 at io.micrometer.prometheus.PrometheusMeterRegistry.collectorByName(PrometheusMeterRegistry.java:369)
 at io.micrometer.prometheus.PrometheusMeterRegistry.newTimer(PrometheusMeterRegistry.java:175)
 at io.micrometer.core.instrument.MeterRegistry.lambda$timer$2(MeterRegistry.java:271)
 at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:576)
 at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:529)
 at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:269)
 at io.micrometer.core.instrument.Timer$Builder.register(Timer.java:477)
 at io.micrometer.core.instrument.composite.CompositeTimer.registerNewMeter(CompositeTimer.java:140)
 at io.micrometer.core.instrument.composite.CompositeTimer.registerNewMeter(CompositeTimer.java:31)
 at io.micrometer.core.instrument.composite.AbstractCompositeMeter.add(AbstractCompositeMeter.java:66)
 at java.base/java.lang.Iterable.forEach(Iterable.java:75)
 at java.base/java.util.Collections$SetFromMap.forEach(Collections.java:5581)
 at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lambda$new$0(CompositeMeterRegistry.java:65)
 at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lock(CompositeMeterRegistry.java:184)
 at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lambda$new$1(CompositeMeterRegistry.java:65)
 at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:585)
 at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:529)
 at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:269)
 at io.micrometer.core.instrument.Timer$Builder.register(Timer.java:477)
 at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:396)
 at io.micrometer.core.instrument.internal.TimedScheduledExecutorService.<init>(TimedScheduledExecutorService.java:44)
 at io.micrometer.core.instrument.binder.jvm.ExecutorServiceMetrics.monitor(ExecutorServiceMetrics.java:126)
 at io.micrometer.core.instrument.binder.jvm.ExecutorServiceMetrics.monitor(ExecutorServiceMetrics.java:140)
 at com.linecorp.armeria.server.ServerConfig.<init>(ServerConfig.java:159)
 at com.linecorp.armeria.server.ServerBuilder.build(ServerBuilder.java:1623)
 at com.linecorp.armeria.spring.web.reactive.ArmeriaReactiveWebServerFactory.getWebServer(ArmeriaReactiveWebServerFactory.java:205)
 at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext$ServerManager.<init>(ReactiveWebServerApplicationContext.java:230)
 at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext$ServerManager.get(ReactiveWebServerApplicationContext.java:248)
 at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.createWebServer(ReactiveWebServerApplicationContext.java:91)
 at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:78)
 ... 8 common frames omitted
```

**Comment by trustin** [comment]
Meanwhile, please use `MeterRegistry.config().meterFilter(MeterFilter)` to amend the tag inconsistencies.

**Comment by trustin** [comment]
What @AmosDoan suggests is to provide a way to disable `blockingTaskExecutor` completely, so that Armeria does not register any metrics for executors.

I'm not sure I like the idea, because we can't add knobs for every executor we add in the future. We have only `blockingTaskExecutor` today, but we might have more executors internally and want to monitor them.

There are two options in my opinion:

- Rename the meters, e.g. `executor.*` -> `armeria.executor.*`
  - We need to fork `ExecutorServiceMetrics`.
- Let our users use `MeterRegistry.config()`.

I believe the same problem will arise for Project Reactor as soon as a user tries to monitor his or her executor using `ExecutorServiceMetrics.monitor()` with different tags. Perhaps we should work with Micrometer and Project Reactor to so that:

- `ExecutorServiceMetrics` allows a user to specify a different meter ID prefix than just `executors.`, e.g. `reactor.executor.` or `armeria.executor.`.
- Project Reactor changes the meter ID prefix from `executor.` to `reactor.executor.` so that it does not conflict with other executor metrics.

/cc @smaldini @shakuzen
