### ISSUE TITLE
Intermittent failure in ProxyClientIntegrationTest

### ISSUE THREAD

**Issue by minwoox** [line/armeria#2606]
```
ProxyClientIntegrationTest > testHttpsProxyBasicCase() FAILED
    java.util.concurrent.CompletionException: com.linecorp.armeria.client.WriteTimeoutException
        at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412)
        at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2115)
        at com.linecorp.armeria.common.util.EventLoopCheckingFuture.join(EventLoopCheckingFuture.java:88)
        at com.linecorp.armeria.client.proxy.ProxyClientIntegrationTest.testHttpsProxyBasicCase(ProxyClientIntegrationTest.java:232)

        Caused by:
        com.linecorp.armeria.client.WriteTimeoutException
            at com.linecorp.armeria.client.WriteTimeoutException.get(WriteTimeoutException.java:36)
            at com.linecorp.armeria.client.HttpRequestSubscriber.lambda$onSubscribe$0(HttpRequestSubscriber.java:145)
            at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
            at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
            at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
            at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
            at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
            at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
            at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
            at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
            at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by minwoox** [comment]
This happens a lot in my local recently, which a bit annoying.
I think the reason is that the `promise` used to connect is complete after the connection to the proxy server is established, not after to the final destination.
The writing to the socket is pending until the channel reads a message that indicates the proxy server connects to the final endpoint.
So there's a high chance that `WriteTimeoutException` happens because it additionally needs to wait for the proxy to connect the final endpoint.

I think we can solve this by making `promise` complete after the connection to the final endpoint is established using `connectPromise`.
https://github.com/netty/netty/blob/4.1/handler-proxy/src/main/java/io/netty/handler/proxy/ProxyHandler.java#L179

**Comment by trustin** [comment]
That would change the behavior of `ProxyHandler` which might break existing applications that use it, i.e. it can only happen in Netty 5. We should update `HttpSessionHandler` so that `sessionPromise` is completed only after a `ProxyConnectionEvent`.
