### ISSUE TITLE
Intermittent test failure in BraveClientIntegrationTest

### ISSUE THREAD

**Issue by minwoox** [line/armeria#2628]
```
BraveClientIntegrationTest > clientTimestampAndDurationEnclosedByParent[0] FAILED
    java.lang.AssertionError: Expected {"traceId":"da0150dd415ca65f","id":"da0150dd415ca65f","name":"parent","timestamp":1585130513118842,"duration":9454,
    "localEndpoint":{"serviceName":"unknown","ipv4":"192.168.176.2"}} to finish after {"traceId":"da0150dd415ca65f","parentId":"da0150dd415ca65f","id":"b0481c3cbe548cb1","kind":"CLIENT","name":"get","timestamp":1585130513119199,"duration":9529,"localEndpoint":{"serviceName":"unknown","ipv4":"192.168.176.2"},"remoteEndpoint":{"ipv4":"127.0.0.1","port":48538},"annotations":[{"timestamp":1585130513120174,"value":"connection-acquire.start"},{"timestamp":1585130513120991,"value":"socket-connect.start"},{"timestamp":1585130513124358,"value":"socket-connect.end"},{"timestamp":1585130513124398,"value":"connection-acquire.end"},{"timestamp":1585130513126002,"value":"ws"},{"timestamp":1585130513127897,"value":"wr"}],"tags":{"http.method":"GET","http.path":"/foo"}}
        at brave.test.http.ITHttp.assertParentEnclosesChild(ITHttp.java:258)
        at brave.test.http.ITHttpClient.clientTimestampAndDurationEnclosedByParent(ITHttpClient.java:119)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by ikhoon** [comment]
I'm not sure what is the cause, but we can see this fail frequently these days. 
https://ci.appveyor.com/project/line/armeria/builds/31920717/job/hkj8et7i7a863bhk#L1099

**Comment by heowc** [comment]
This issue seems to have been resolved in [the PR](https://github.com/line/armeria/pull/2618). 😄

**Comment by ikhoon** [comment]
> This issue seems to have been resolved in [the PR](https://github.com/line/armeria/pull/2618). 😄

Yes, the test was ignored. However, I think we can close this PR when the clock problem is fixed.
https://github.com/line/armeria/blob/a6c575e2a675b1590ae53d9481495e101f511bfb/brave/src/test/java/com/linecorp/armeria/client/brave/BraveClientIntegrationTest.java#L128-L130
