### ISSUE TITLE
Support CoroutineStubs from grpc-kotlin

### ISSUE THREAD

**Issue by gary-lo** [line/armeria#2662]
[grpc-kotlin](https://github.com/grpc/grpc-kotlin) generates client stubs are currently incompatible with Armeria GrpcClientFactories see the following stacktrace
```
Caused by: java.lang.IllegalArgumentException: Unknown client type: com.airtasker.application.adapters.grpc.MitchServiceGrpcKt$MitchServiceCoroutineStub (expected: a gRPC client stub class, e.g. MyServiceGrpc.MyServiceStub)
	at com.linecorp.armeria.internal.client.grpc.GrpcClientFactory.newUnknownClientTypeException(GrpcClientFactory.java:155)
	at com.linecorp.armeria.internal.client.grpc.GrpcClientFactory.findStubFactoryMethod(GrpcClientFactory.java:148)
	at com.linecorp.armeria.internal.client.grpc.GrpcClientFactory.newClient(GrpcClientFactory.java:93)
	at com.linecorp.armeria.client.DefaultClientFactory.newClient(DefaultClientFactory.java:148)
	at com.linecorp.armeria.client.ClientBuilder.build(ClientBuilder.java:106)
	at com.linecorp.armeria.client.Clients.newClient(Clients.java:54)
```

Currently gRPC Factory looks via naming findStubFactoryMethod 
```
            final String methodName = method.getName();
            if (!(methodName.startsWith("new") && methodName.endsWith("Stub"))) {
                // Must be named as `new*Stub()`.
                continue;
            }
```

Which do not exist in the generated stubs see example
https://github.com/grpc/grpc-kotlin/blob/master/compiler/src/test/java/io/grpc/kotlin/generator/GreeterCoroutineStub.expected#L26
```
**
 * A stub for issuing RPCs to a(n) helloworld.Greeter service as suspending coroutines.
 */
@StubFor(GreeterGrpc::class)
class GreeterCoroutineStub @JvmOverloads constructor(
  channel: Channel,
  callOptions: CallOptions = DEFAULT
) : AbstractCoroutineStub<GreeterCoroutineStub>(channel, callOptions) {
  override fun build(channel: Channel, callOptions: CallOptions): GreeterCoroutineStub =
      GreeterCoroutineStub(channel, callOptions)
```

**Comment by trustin** [comment]
Thanks for reporting. Let me take a look hopefully tomorrow.
