### ISSUE TITLE
Client requests not using RequestHeaders.authority

### ISSUE THREAD

**Issue by jrhee17** [line/armeria#2715]
Not sure if this is intentional, but it was definitely unexpected

Minimal reproducer

```
final RequestHeadersBuilder requestHeadersBuilder =
                RequestHeaders.builder()
                              .authority("localhost:8080")
                              .scheme("h2c")
                              .add("param1", "val1")
                              .path("/path1");

        final AggregatedHttpRequest request = AggregatedHttpRequest.of(
                requestHeadersBuilder.method(HttpMethod.GET).build());
        final AggregatedHttpResponse response = WebClient.of().execute(request).aggregate().join();
```

Logs
```
Caused by: java.lang.IllegalArgumentException: no authority: /path1
	at com.linecorp.armeria.client.DefaultWebClient.execute(DefaultWebClient.java:70)
	at com.linecorp.armeria.client.DefaultWebClient.execute(DefaultWebClient.java:101)
	... 64 more
```

**Comment by ikhoon** [comment]
We didn't expect that use-case. I thought users will be set full URL(authority + path) to the path using 
```java
var webClient = WebClient.of();
webClient.get("http://some-domain.com/path?param=value");
```
Are you interested in making a PR for this? 😉

**Comment by jrhee17** [comment]
cc. @masonshin (who found this)

**Comment by ikhoon** [comment]
Let me handle this 🙇‍♂️
