### ISSUE TITLE
Flaky test: `BraveServiceIntegrationTest.childCompletesBeforeServer`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#2833]
https://ci.appveyor.com/project/line/armeria/builds/33726346/job/a0rrj3t4qfva6v6f#L1682
```
BraveServiceIntegrationTest > childCompletesBeforeServer FAILED
    java.lang.AssertionError: Expected {"traceId":"323fe8defcbd845a","parentId":"323fe8defcbd845a","id":"b216d181a49390e8","name":"child","timestamp":1593058969521364,"duration":11,"localEndpoint":{"serviceName":"BraveServiceIntegrationTest","ipv4":"127.0.0.1"}} to finish after 1593058969521333
        at brave.test.ITRemote.assertSpanInInterval(ITRemote.java:185)
        at brave.test.http.ITHttpServer.childCompletesBeforeServer(ITHttpServer.java:210)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by minwoox** [comment]
https://github.com/line/armeria/runs/3740642079
```
BraveServiceIntegrationTest > childCompletesBeforeServer FAILED
    java.lang.AssertionError: Thread [armeria-common-worker-epoll-2-6] opened a scope of 43b539d0bf19652b/43b539d0bf19652b here:
        at com.linecorp.armeria.server.brave.BraveService.lambda$serve$1(BraveService.java:108)
        at com.linecorp.armeria.internal.common.RequestContextUtil.invokeHook(RequestContextUtil.java:256)
        at com.linecorp.armeria.internal.common.RequestContextUtil.invokeHookAndPop(RequestContextUtil.java:228)
        at com.linecorp.armeria.server.ServiceRequestContext.push(ServiceRequestContext.java:225)
        at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:546)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```
