### ISSUE TITLE
URLs with userInfo causes parsing error in ClientBuilder.build()

### ISSUE THREAD

**Issue by tobias-** [line/armeria#2869]
URLs with authority causes parsing error. Test case: https://github.com/tobias-/armeria/pull/2 [not claiming copyright for that code]

Imho the authority should be ignored, not cause error.

```
Caused by: java.lang.IllegalArgumentException: Not a valid domain name: 'foobar@example.com'
	at com.linecorp.armeria.internal.shaded.guava.base.Preconditions.checkArgument(Preconditions.java:217) ~[armeria-0.99.7.jar:?]
	at com.linecorp.armeria.internal.shaded.guava.net.InternetDomainName.<init>(InternetDomainName.java:149) ~[armeria-0.99.7.jar:?]
	at com.linecorp.armeria.internal.shaded.guava.net.InternetDomainName.from(InternetDomainName.java:210) ~[armeria-0.99.7.jar:?]
	at com.linecorp.armeria.client.Endpoint.create(Endpoint.java:129) ~[armeria-0.99.7.jar:?]
	at com.linecorp.armeria.client.Endpoint.parse(Endpoint.java:84) ~[armeria-0.99.7.jar:?]
	at com.linecorp.armeria.client.DefaultClientBuilderParams.<init>(DefaultClientBuilderParams.java:55) ~[armeria-0.99.7.jar:?]
	at com.linecorp.armeria.client.ClientBuilderParams.of(ClientBuilderParams.java:40) ~[armeria-0.99.7.jar:?]
	at com.linecorp.armeria.client.ClientBuilder.build(ClientBuilder.java:109) ~[armeria-0.99.7.jar:?]
```

**Comment by trustin** [comment]
Hey, thanks for reporting. Agreed that userinfo part should be ignored automatically.

**Comment by ghkim3221** [comment]
Let me check 😄
