### ISSUE TITLE
NoSuchMethodException while requesting server.builder()

### ISSUE THREAD

**Issue by jfrojo** [line/armeria#2903]
A simple call to Server.builder() causes this exception (can't tell when did this happend as I was handled a code and upgraded from 0.77.0 to 0.99.8)

code to generate the issue:
Server.builder()

Full stacktrace:
Exception in thread "main" java.lang.NoSuchMethodError: 'void io.netty.util.concurrent.SingleThreadEventExecutor.<init>(io.netty.util.concurrent.EventExecutorGroup, java.util.concurrent.Executor, boolean, java.util.Queue, io.netty.util.concurrent.RejectedExecutionHandler)'
	at io.netty.channel.SingleThreadEventLoop.<init>(SingleThreadEventLoop.java:65)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:138)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:146)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:37)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:86)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:81)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:68)
	at com.linecorp.armeria.internal.common.util.TransportType.newEventLoopGroup(TransportType.java:169)
	at com.linecorp.armeria.common.util.EventLoopGroups.newEventLoopGroup(EventLoopGroups.java:108)
	at com.linecorp.armeria.common.util.EventLoopGroups.newEventLoopGroup(EventLoopGroups.java:92)
	at com.linecorp.armeria.common.CommonPools.<clinit>(CommonPools.java:47)
	at com.linecorp.armeria.server.ServerBuilder.<init>(ServerBuilder.java:167)
	at com.linecorp.armeria.server.Server.builder(Server.java:102)

JDK (just in case): OpenJDK 14.0.2

**Comment by ikhoon** [comment]
When I tested it locally with Java 14, I could not reproduce `NoSuchMethodError` on `SingleThreadEventExecutor`. And the constructor was added in Netty 4.1.37.Final https://github.com/netty/netty/pull/9247

Could you check the Netty version of your project? If you are using a lower version of Netty, we recommend using the latest version of Netty. FYI, [Maven BOM](https://armeria.dev/docs/setup/#using-maven-bom-for-simpler-dependency-management) is a good way to manage dependencies.

**Comment by jfrojo** [comment]
> When I tested it locally with Java 14, I could not reproduce `NoSuchMethodError` on `SingleThreadEventExecutor`. And the constructor was added in Netty 4.1.37.Final [netty/netty#9247](https://github.com/netty/netty/pull/9247)
> 
> Could you check the Netty version of your project? If you are using a lower version of Netty, we recommend using the latest version of Netty. FYI, [Maven BOM](https://armeria.dev/docs/setup/#using-maven-bom-for-simpler-dependency-management) is a good way to manage dependencies.

The issue was a specified dependency I missed, the Netty version was quite old as well. Thanks for the quick response and sorry for the trouble.

**Comment by ikhoon** [comment]
Don't care. :-) If you have any trouble on using Armeria, you can also ask anythings to [our slack channel](https://armeria.dev/s/slack).
