### ISSUE TITLE
Flaky test: `ServerMaxConnectionAgeTest > [1] protocol=H2C`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3026]
https://ci.appveyor.com/project/line/armeria/builds/34795094/job/fmv8a3081al4njdf#L489
```
com.linecorp.armeria.server.ServerMaxConnectionAgeTest > [1] protocol=H2C FAILED
    java.util.concurrent.CompletionException: com.linecorp.armeria.client.UnprocessedRequestException: com.linecorp.armeria.client.SessionProtocolNegotiationException: expected: h2c, reason: previously failed negotiation
        at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412)
        at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2115)
        at com.linecorp.armeria.common.util.EventLoopCheckingFuture.join(EventLoopCheckingFuture.java:88)
        at com.linecorp.armeria.server.ServerMaxConnectionAgeTest.http2MaxConnectionAge(ServerMaxConnectionAgeTest.java:222)
        Caused by:
        com.linecorp.armeria.client.UnprocessedRequestException: com.linecorp.armeria.client.SessionProtocolNegotiationException: expected: h2c, reason: previously failed negotiation
            at com.linecorp.armeria.client.UnprocessedRequestException.of(UnprocessedRequestException.java:45)
            at com.linecorp.armeria.client.HttpChannelPool.notifyConnect(HttpChannelPool.java:543)
            at com.linecorp.armeria.client.HttpChannelPool.connect(HttpChannelPool.java:372)
            at com.linecorp.armeria.client.HttpChannelPool.acquireLater(HttpChannelPool.java:327)
            at com.linecorp.armeria.client.HttpClientDelegate.acquireConnectionAndExecute(HttpClientDelegate.java:164)
            at com.linecorp.armeria.client.HttpClientDelegate.lambda$acquireConnectionAndExecute$1(HttpClientDelegate.java:137)
            at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:479)
            at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
            at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
            at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
            at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
            at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
            at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
            at java.base/java.lang.Thread.run(Thread.java:830)
            Caused by:
            com.linecorp.armeria.client.SessionProtocolNegotiationException: expected: h2c, reason: previously failed negotiation
                at com.linecorp.armeria.client.HttpChannelPool.connect(HttpChannelPool.java:372)
                ... 11 more
```

**Comment by minwoox** [comment]
```
ServerMaxConnectionAgeTest > http2MaxConnectionAge(SessionProtocol) > com.linecorp.armeria.server.ServerMaxConnectionAgeTest.http2MaxConnectionAge(SessionProtocol)[2] FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a com.linecorp.armeria.server.ServerMaxConnectionAgeTest 
    Expecting actual not to be null within 10 seconds.
        at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:166)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:939)
        at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:723)
        at com.linecorp.armeria.server.ServerMaxConnectionAgeTest.http2MaxConnectionAge(ServerMaxConnectionAgeTest.java:229)

        Caused by:
        java.lang.AssertionError: 
        Expecting actual not to be null
            at com.linecorp.armeria.server.ServerMaxConnectionAgeTest.lambda$http2MaxConnectionAge$6(ServerMaxConnectionAgeTest.java:245)
```
