### ISSUE TITLE
Show Liveness and Readiness from actuator in k8s instances

### ISSUE THREAD

**Issue by minwoox** [line/armeria#3031]
If a Spring Boot instance is deployed in k8s, the actuator gathers the "Liveness" and "Readiness" information from the `ApplicationAvailability` interface and shows it.

https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-kubernetes-probes

**Comment by policeman-kh** [comment]
I checked if spring-boot-actuator `/actuator/health` with the latest Armeria (1.13.4) has "Liveness" and "Readiness" information on k8s.

For the global health endpoint `/actuator/health`, the response has `livenessState` and `readinessState` attribute without setting `management.health.probes.enabled=true` in the property. So it seems to work well.

But for endpoint `/actuator/health/liveness` and `/actuator/health/readiness` return 500 error.  The endpoint return correct response with only spring-boot-actuator without Armeria. So I guess that armeria integration has an issue. 🤔
The issue can be reproduced on my local by adding `management.health.probes.enabled=true` in the property.

And I can see the following stack trace when this 500 error occurs.
```
org.springframework.boot.actuate.endpoint.invoke.MissingParametersException: Failed to invoke operation because the following required parameters were missing: path of type [Ljava.lang.String;
	at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.validateRequiredParameters(ReflectiveOperationInvoker.java:81) ~[spring-boot-actuator-2.6.1.jar:2.6.1]
	at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:70) ~[spring-boot-actuator-2.6.1.jar:2.6.1]
	at org.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:60) ~[spring-boot-actuator-2.6.1.jar:2.6.1]
	at com.linecorp.armeria.spring.actuate.WebOperationService.lambda$invoke$0(WebOperationService.java:151) ~[armeria-spring-boot2-actuator-autoconfigure-1.13.4.jar:na]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[na:na]
	at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:547) ~[armeria-1.13.4.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.70.Final.jar:4.1.70.Final]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:an]
```

For this check, I used [my project](https://github.com/policeman-kh/armeria_k8s).

**Comment by policeman-kh** [comment]
It's additional information.
The [argument of InvocationContext](https://github.com/line/armeria/blob/master/spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/WebOperationService.java#L184) seems be wrong.
When requesting to `"/actuator/health/liveness"`, the arrgument is `"*path" -> "liveness"`.
But the name `"*path"` should be `"path"`. So  `MissingParametersException` occurred.
And `"*path"` comes from [WebOperationRequestPredicate#path](https://github.com/line/armeria/blob/master/spring/boot2-actuator-autoconfigure/src/main/java/com/linecorp/armeria/spring/actuate/ArmeriaSpringActuatorAutoConfiguration.java#L211) 🤔
