### ISSUE TITLE
Un-relevant exception while enable LoggingService decorator.

### ISSUE THREAD

**Issue by eonezhang** [line/armeria#3053]
One of my `AnnotatedService` method thrown customized exception, and the exception was handled by the customized exception handler, but the `LoggingService` still log the error, and the logged error didn’t provide relevant info about the cause of the error, it seems weired.
here is the exception log. How can I disable the log entry of that stuff.
```
[07:09:20,226Z][armeria-common-worker-nio-2-2][ERROR][][//][LoggingService]-[sreqId=e97b3a29, chanId=7ffdd632, raddr=0:0:0:0:0:0:0:1:56576, laddr=0:0:0:0:0:0:0:1:8080][h1c://eonezhang.local/user#GET] Response: {startTime=2020-09-08T07:09:20.226Z(1599548960226000), length=37B, duration=0ns, totalDuration=1316µs(1316815ns), cause=com.linecorp.armeria.server.HttpResponseException, headers=[:status=200, content-type=text/plain; charset=utf-8, content-length=37]}
com.linecorp.armeria.server.HttpResponseException: null
	at com.linecorp.armeria.server.HttpResponseException.of(HttpResponseException.java:60)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService$ExceptionFilteredHttpResponse.beforeError(AnnotatedService.java:481)
	at com.linecorp.armeria.common.stream.FilteredStreamMessage$FilteringSubscriber.onError(FilteredStreamMessage.java:196)
	at com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:280)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:264)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:256)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:436)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:368)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.doRequest(DefaultStreamMessage.java:239)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.request(DefaultStreamMessage.java:224)
	at com.linecorp.armeria.common.stream.AbstractStreamMessage$SubscriptionImpl.request(AbstractStreamMessage.java:223)
	at com.linecorp.armeria.common.stream.DeferredStreamMessage$ForwardingSubscriber.onSubscribe(DeferredStreamMessage.java:334)
	at com.linecorp.armeria.common.stream.FilteredStreamMessage$FilteringSubscriber.onSubscribe(FilteredStreamMessage.java:182)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:139)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:126)
	at com.linecorp.armeria.common.stream.AbstractStreamMessage.subscribe(AbstractStreamMessage.java:73)
	at com.linecorp.armeria.common.stream.AbstractStreamMessage.subscribe(AbstractStreamMessage.java:64)
	at com.linecorp.armeria.common.stream.FilteredStreamMessage.subscribe(FilteredStreamMessage.java:139)
	at com.linecorp.armeria.common.stream.FilteredStreamMessage.subscribe(FilteredStreamMessage.java:134)
	at com.linecorp.armeria.common.stream.DeferredStreamMessage.safeOnSubscribeToUpstream(DeferredStreamMessage.java:281)
	at com.linecorp.armeria.common.stream.DeferredStreamMessage.subscribe(DeferredStreamMessage.java:259)
	at com.linecorp.armeria.common.stream.DeferredStreamMessage.subscribe(DeferredStreamMessage.java:239)
	at com.linecorp.armeria.common.stream.AbstractStreamMessage.subscribe(AbstractStreamMessage.java:73)
	at com.linecorp.armeria.common.stream.AbstractStreamMessage.subscribe(AbstractStreamMessage.java:64)
	at com.linecorp.armeria.server.HttpServerHandler.handleRequest(HttpServerHandler.java:465)
	at com.linecorp.armeria.server.HttpServerHandler.channelRead(HttpServerHandler.java:249)
```
the whole demo stuff to reproduce that scenario.
```java
package armeria.demo;
import java.util.Random;
import com.linecorp.armeria.common.HttpRequest;
import com.linecorp.armeria.common.HttpResponse;
import com.linecorp.armeria.common.logging.LogLevel;
import com.linecorp.armeria.server.Server;
import com.linecorp.armeria.server.ServiceRequestContext;
import com.linecorp.armeria.server.annotation.ExceptionHandler;
import com.linecorp.armeria.server.annotation.ExceptionHandlerFunction;
import com.linecorp.armeria.server.annotation.Get;
import com.linecorp.armeria.server.annotation.ProducesJson;
import com.linecorp.armeria.server.logging.LoggingService;
import reactor.core.publisher.Mono;
public class App {
    public static void main(String[] args) {
        final Server server = Server.builder()
                                    .http(8080)
                                    .annotatedService(new UserRestApi())
                                    .decorator(LoggingService
                                                     .builder()
                                                     .requestLogLevel(LogLevel.INFO)
                                                     .failureResponseLogLevel(LogLevel.ERROR)
                                                     .successfulResponseLogLevel(LogLevel.INFO)
                                                     .newDecorator())
                                    .build();
        server.start();
    }
    public static class SystemException extends RuntimeException {
        public SystemException(String message) {
            super(message);
        }
    }
    @ExceptionHandler(value = DemoExceptionHandler.class)
    static class UserRestApi {
        Random random = new Random();
        @Get("/user")
        @ProducesJson
        public Mono<User> user() {
            final int number = random.nextInt();
            if (number > 10) {
                return Mono.error(new SystemException(number + ""));
            }
            return Mono.just(new User("eone", "zhang"));
        }
    }
    static class DemoExceptionHandler implements ExceptionHandlerFunction {
        @Override
        public HttpResponse handleException(ServiceRequestContext ctx, HttpRequest req, Throwable cause) {
            if (cause instanceof SystemException) {
                return HttpResponse.of("system exception of number: %s", cause.getMessage());
            }
            return ExceptionHandlerFunction.fallthrough();
        }
    }
    private static class User {
        String username;
        String password;
        public User(String username, String password) {
            this.username = username;
            this.password = password;
        }
        public String getUsername() {
            return username;
        }
        public void setUsername(String username) {
            this.username = username;
        }
        public String getPassword() {
            return password;
        }
        public void setPassword(String password) {
            this.password = password;
        }
    }
}
```

**Comment by minwoox** [comment]
Thanks a lot @eonezhang for the report. Let me handle this.

While I'm working on this I found out that we don't have `requestCauseSanitizer` which means that we don't treat the request cause as we do for response cause.
@trustin Do you have any idea about this? 🤔

**Comment by minwoox** [comment]
Ah, never mind. 😅  We don't need the stacktrace of the request cause. Let me add a comment for that. 😉
