### ISSUE TITLE
NumberFormatException while reading an HTTP chunk

### ISSUE THREAD

**Issue by trustin** [line/armeria#3100]
In a certain situation we do not know exactly yet, a `NumberFormatException` is triggered while reading HTTP request body:

```
java.lang.NumberFormatException.forInputString
    at java.lang.Integer.parseInt
    at io.netty.handler.codec.http.HttpObjectDecoder.getChunkSize(HttpObjectDecoder.java:792)
    at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:357)
    at io.netty.handler.codec.http.HttpServerCodec$HttpServerRequestDecoder.decode(HttpServerCodec.java:123)
    ...
```

A workaround is to switch to HTTP/2, which never uses chunked encoding.

So far we could not reproduce it or observe it in production at all. I'd be nice if we have a standalone reproducer for this issue.

**Comment by trustin** [comment]
From Premraj Motling:

> The configuration goes like this :
>
>     client (H1) -> AWS NLB (SSL termination) -> Nginx proxy (http route) -> Armeria Server (HTTP)
>
> Interestingly we did not see this in old armeria 0.94 version and only experiencing this with armeria 1.0 - anything particularly can cause this?
