### ISSUE TITLE
Message is sent before header is sent?

### ISSUE THREAD

**Issue by minwoox** [line/armeria#3127]
```java
java.lang.IllegalStateException: sendHeaders has not been called
	at com.linecorp.armeria.internal.shaded.guava.base.Preconditions.checkState(Preconditions.java:508)
	at com.linecorp.armeria.server.grpc.ArmeriaServerCall.doSendMessage(ArmeriaServerCall.java:245)
	at com.linecorp.armeria.server.grpc.ArmeriaServerCall.lambda$sendMessage$4(ArmeriaServerCall.java:240)
	at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:479)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
It happened in Armeria 1.1.0

**Comment by m50d** [comment]
I suspect that the `sendMessage` call is coming from grpc-stub 1.32.1 `ServerCallStreamObserverImpl#onNext`. There is logic in that class to ensure that `sendHeaders` is always called. Since both `sendHeaders` and `sendMessage` create async tasks to be run by the event loop, I wonder if somehow these tasks were executed in the wrong order?

**Comment by ikhoon** [comment]
Another stack trace shared from @m50d 
```java
ava.lang.IllegalStateException: call is closed
	at com.linecorp.armeria.internal.shaded.guava.base.Preconditions.checkState(Preconditions.java:508)
	at com.linecorp.armeria.server.grpc.ArmeriaServerCall.doSendHeaders(ArmeriaServerCall.java:205)
	at com.linecorp.armeria.server.grpc.ArmeriaServerCall.lambda$sendHeaders$2(ArmeriaServerCall.java:199)
	at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:479)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Based the stack trace, the headers failed to be sent is the call is closed already.
It was checked by
https://github.com/line/armeria/blob/6e24e7817f8be94ab21ddba7879e9f84ca840229/grpc/src/main/java/com/linecorp/armeria/server/grpc/ArmeriaServerCall.java#L205

**Comment by m50d** [comment]
Could we include more details about the request in that `checkState` error message? At the moment it's hard to even tell what request the exception comes from (although that may not help if we can't tell what might have closed it).

**Comment by ikhoon** [comment]
We got a report that is similar to this error from [Armeria slack channel](https://line-armeria.slack.com/archives/C1NGPBUH2/p1604070308229600). I'm sure this is the same case or not yet.
Let me investigate on the reported issue. 
On the otherhand, we can sample the original stacktrace that called `ArmeriaServerCall.close()` with `-Dcom.linecorp.armeria.verboseExceptions=...`  if `-Dcom.linecorp.armeria.verboseResponses=true` is set. 
/cc @okue

**Comment by ikhoon** [comment]
@m50d In my opinion #3153 PR might resolve the issue too. If a call is closed by a remote peer, you no longer see `sendHeaders has not been called` error message.

**Comment by m50d** [comment]
Sadly that PR doesn't seem to have resolved things - we've deployed armeria 1.3.0 but have still seen this error happen occasionally.

**Comment by ikhoon** [comment]
Hmm.. Are the error stacks exactly the same?
Let me check possible cases.

**Comment by m50d** [comment]
Line numbers have changed, but other than that it looks exactly the same:

````
java.lang.IllegalStateException: sendHeaders has not been called 	at com.linecorp.armeria.internal.shaded.guava.base.Preconditions.checkState(Preconditions.java:508) 	at com.linecorp.armeria.server.grpc.ArmeriaServerCall.doSendMessage(ArmeriaServerCall.java:274) 	at com.linecorp.armeria.server.grpc.ArmeriaServerCall.lambda$sendMessage$4(ArmeriaServerCall.java:265) 	at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:502) 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 	at java.base/java.lang.Thread.run(Thread.java:834)
````

**Comment by ikhoon** [comment]
The logs havean error message like `java.lang.IllegalStateException: call is closed` before warning the `java.lang.IllegalStateException: sendHeaders has not been called`?

**Comment by m50d** [comment]
Ah yes, sorry. The exceptions always come in pairs, with the first one being:

````
java.lang.IllegalStateException: call is closed
 	at com.linecorp.armeria.internal.shaded.guava.base.Preconditions.checkState(Preconditions.java:508)
 	at com.linecorp.armeria.server.grpc.ArmeriaServerCall.doSendHeaders(ArmeriaServerCall.java:230)
 	at com.linecorp.armeria.server.grpc.ArmeriaServerCall.lambda$sendHeaders$2(ArmeriaServerCall.java:220)
 	at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:502)
 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 	at java.base/java.lang.Thread.run(Thread.java:834)
````

**Comment by ikhoon** [comment]
Thanks! That is good information. 🙇‍♂️

**Comment by ikhoon** [comment]
@m50d Are you using blocking task executors for your gRPC service?

**Comment by ikhoon** [comment]
I got feedback from @m50d. A blocking IO executed in an event loop. The problem was fixed by `useBlockingTaskExecutor` in `GrpcServiceBuilder`.
