### ISSUE TITLE
Test failure: `DefaultSplitHttpResponseTest.cancelResponse()`

### ISSUE THREAD

**Issue by trustin** [line/armeria#3186]
```
> :core:shadedTest > 1973 tests completed, 14 skipped
DefaultSplitHttpResponseTest > cancelResponse() FAILED
    org.opentest4j.AssertionFailedError: 
    Expecting:
     <[:status=0]>
    to be equal to:
     <[:status=200]>
    but was not.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at com.linecorp.armeria.common.DefaultSplitHttpResponseTest.cancelResponse(DefaultSplitHttpResponseTest.java:147)
```

**Comment by ikhoon** [comment]
Oops... let me take a look.

**Comment by trustin** [comment]
Test reports: https://file.io/0y81vDZ10wci
