### ISSUE TITLE
NPE when retrying RPC requests with armeria-client (suspect race condition around `NonWrappingRequestContext#rpcReq`)

### ISSUE THREAD

**Issue by m50d** [line/armeria#3248]
Hi,

We're seeing exceptions like:

````
io.grpc.StatusRuntimeException: UNKNOWN
        at io.grpc.Status.asRuntimeException(Status.java:533)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
        at com.linecorp.armeria.internal.client.grpc.ArmeriaClientCall.close(ArmeriaClientCall.java:464)
        at com.linecorp.armeria.internal.client.grpc.ArmeriaClientCall.transportReportStatus(ArmeriaClientCall.java:416)
        at com.linecorp.armeria.internal.common.grpc.TransportStatusListener.transportReportStatus(TransportStatusListener.java:28)
        at com.linecorp.armeria.internal.common.grpc.HttpStreamDeframerHandler.processOnError(HttpStreamDeframerHandler.java:124)
        at com.linecorp.armeria.common.stream.DefaultHttpDeframer.onError0(DefaultHttpDeframer.java:281)
        at com.linecorp.armeria.common.stream.DefaultHttpDeframer.onError(DefaultHttpDeframer.java:272)
        at com.linecorp.armeria.common.stream.DeferredStreamMessage$ForwardingSubscriber.onError(DeferredStreamMessage.java:346)
        at com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:281)
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:264)
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:256)
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:436)
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:368)
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.doRequest(DefaultStreamMessage.java:239)
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.request(DefaultStreamMessage.java:224)
        at com.linecorp.armeria.common.stream.AbstractStreamMessage$SubscriptionImpl.request(AbstractStreamMessage.java:224)
        at com.linecorp.armeria.common.stream.DeferredStreamMessage$ForwardingSubscriber.onSubscribe(DeferredStreamMessage.java:334)
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:139)
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.lambda$subscribe$0(DefaultStreamMessage.java:129)
        at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:502)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException: rpcReq
        at java.base/java.util.Objects.requireNonNull(Objects.java:246)
        at com.linecorp.armeria.client.DefaultClientRequestContext.<init>(DefaultClientRequestContext.java:361)
        at com.linecorp.armeria.client.DefaultClientRequestContext.newDerivedContext(DefaultClientRequestContext.java:410)
        at com.linecorp.armeria.client.retry.AbstractRetryingClient.newDerivedContext(AbstractRetryingClient.java:268)
        at com.linecorp.armeria.client.retry.RetryingClient.doExecute0(RetryingClient.java:282)
        at com.linecorp.armeria.client.retry.RetryingClient.doExecute(RetryingClient.java:241)
        at com.linecorp.armeria.client.retry.RetryingClient.doExecute(RetryingClient.java:56)
        at com.linecorp.armeria.client.retry.AbstractRetryingClient.execute(AbstractRetryingClient.java:96)
        at com.linecorp.armeria.client.limit.AbstractConcurrencyLimitingClient$PendingTask.run(AbstractConcurrencyLimitingClient.java:237)
        at com.linecorp.armeria.client.limit.AbstractConcurrencyLimitingClient.drain(AbstractConcurrencyLimitingClient.java:184)
        at com.linecorp.armeria.client.limit.AbstractConcurrencyLimitingClient$PendingTask.lambda$run$0(AbstractConcurrencyLimitingClient.java:240)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
        ... 7 common frames omitted
````

`RetryingClient#doExecute0` passes `ctx.rpcRequest()` to `newDerivedContext`, so I think this can only happen if `ctx.rpcReq` is `null` on this line but then becomes non-null when the constructor of `DefaultClientRequestContext` is executed. However that does seem entirely possible: `rpcReq` is `volatile` and `DefaultRequestLog#requestContent` calls `ctx.updateRpcRequest` if `ctx.rpcRequest()` is `null`. `DefaultRequestLog#requestContent` is called from several places; while I don't have a specific scenario for why it would be called at the same time as `AbstractRetryingClient#execute`, there doesn't seem to be any synchronisation is place to prevent that.

Under what circumstances is it permitted for `ctx.rpcReq` to change from `null` to non-`null`, and does `newDerivedContext` handle all of those cases correctly? Or is there some other reason for this exception?

**Comment by ikhoon** [comment]
`ctx.updateRpcRequest` seems to be executed in a non-event loop thread. 🧐

**Comment by m50d** [comment]
Is there an invariant that that should never happen? It looks like `DefaultRequestLog#requestContent` gets called from various future callbacks; I didn't trace any further than that.
