### ISSUE TITLE
Support proto version 2

### ISSUE THREAD

**Issue by wickedev** [line/armeria#3273]
When using proto version 2 with required field in Armeria, try to support `gjson` or `gjson-web`, an error occurred when initializing `FramedGrpcService` and cannot be executed as below

```
2021-01-11 13:27:59.655 ERROR 6513 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start reactive web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.linecorp.armeria.server.grpc.GrpcService#0': Unexpected exception during bean creation; nested exception is com.google.protobuf.UninitializedMessageException: Message missing required fields: message
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:81) ~[spring-boot-2.4.0.jar:2.4.0]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:582) ~[spring-context-5.3.1.jar:5.3.1]
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:63) ~[spring-boot-2.4.0.jar:2.4.0]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[spring-boot-2.4.0.jar:2.4.0]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-2.4.0.jar:2.4.0]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[spring-boot-2.4.0.jar:2.4.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[spring-boot-2.4.0.jar:2.4.0]
        at org.springframework.fu.kofu.KofuApplication.run(KofuApplication.kt:50) ~[spring-fu-kofu-0.5.0-patch-context.jar:na]
        at org.springframework.fu.kofu.KofuApplication.run$default(KofuApplication.kt:34) ~[spring-fu-kofu-0.5.0-patch-context.jar:na]
        at org.novonetworks.app.ApplicationKt.main(Application.kt:21) ~[main/:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.linecorp.armeria.server.grpc.GrpcService#0': Unexpected exception during bean creation; nested exception is com.google.protobuf.UninitializedMessageException: Message missing required fields: message
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:544) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:233) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1235) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:494) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:349) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1179) ~[spring-context-5.3.1.jar:5.3.1]
        at org.novonetworks.app.ArmeriaServerConfigKt$armeriaServerConfig$1$1$$special$$inlined$bean$4.get(BeanDefinitionDsl.kt:1160) ~[main/:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1233) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1175) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:571) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213) ~[spring-beans-5.3.1.jar:5.3.1]
        at com.linecorp.armeria.spring.web.reactive.ArmeriaReactiveWebServerFactory.lambda$findBeans$6(ArmeriaReactiveWebServerFactory.java:302) ~[armeria-spring-boot2-webflux-autoconfigure-1.3.0.jar:na]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
        at com.linecorp.armeria.spring.web.reactive.ArmeriaReactiveWebServerFactory.findBeans(ArmeriaReactiveWebServerFactory.java:303) ~[armeria-spring-boot2-webflux-autoconfigure-1.3.0.jar:na]
        at com.linecorp.armeria.spring.web.reactive.ArmeriaReactiveWebServerFactory.getWebServer(ArmeriaReactiveWebServerFactory.java:207) ~[armeria-spring-boot2-webflux-autoconfigure-1.3.0.jar:na]
        at org.springframework.boot.web.reactive.context.WebServerManager.<init>(WebServerManager.java:49) ~[spring-boot-2.4.0.jar:2.4.0]
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.createWebServer(ReactiveWebServerApplicationContext.java:93) ~[spring-boot-2.4.0.jar:2.4.0]
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:78) ~[spring-boot-2.4.0.jar:2.4.0]
        ... 9 common frames omitted
Caused by: com.google.protobuf.UninitializedMessageException: Message missing required fields: message
        at com.google.protobuf.AbstractMessage$Builder.newUninitializedMessageException(AbstractMessage.java:477) ~[protobuf-java-3.12.0.jar:na]
        at greeting.GreetingProto$Greeting$Builder.build(GreetingProto.java:483) ~[main/:na]
        at greeting.GreetingProto$Greeting$Builder.build(GreetingProto.java:425) ~[main/:na]
        at org.curioswitch.common.protobuf.json.ProtoFieldInfo.valuePrototype(ProtoFieldInfo.java:133) ~[protobuf-jackson-1.1.0.jar:na]
        at org.curioswitch.common.protobuf.json.TypeSpecificMarshaller.buildOrFindMarshaller(TypeSpecificMarshaller.java:237) ~[protobuf-jackson-1.1.0.jar:na]
        at org.curioswitch.common.protobuf.json.TypeSpecificMarshaller.buildAndAdd(TypeSpecificMarshaller.java:160) ~[protobuf-jackson-1.1.0.jar:na]
        at org.curioswitch.common.protobuf.json.MessageMarshaller$Builder.build(MessageMarshaller.java:425) ~[protobuf-jackson-1.1.0.jar:na]
        at com.linecorp.armeria.common.grpc.GrpcJsonUtil.jsonMarshaller(GrpcJsonUtil.java:62) ~[armeria-grpc-1.3.0.jar:na]
        at com.linecorp.armeria.common.grpc.GrpcJsonMarshallerBuilder.build(GrpcJsonMarshallerBuilder.java:71) ~[armeria-grpc-1.3.0.jar:na]
        at com.linecorp.armeria.common.grpc.GrpcJsonMarshaller.of(GrpcJsonMarshaller.java:45) ~[armeria-grpc-1.3.0.jar:na]
        at com.linecorp.armeria.internal.shaded.guava.collect.CollectCollectors.lambda$toImmutableMap$1(CollectCollectors.java:61) ~[armeria-1.3.0.jar:na]
        at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[na:na]
        at java.base/java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
        at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747) ~[na:na]
        at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
        at com.linecorp.armeria.server.grpc.FramedGrpcService.<init>(FramedGrpcService.java:131) ~[armeria-grpc-1.3.0.jar:na]
        at com.linecorp.armeria.server.grpc.GrpcServiceBuilder.build(GrpcServiceBuilder.java:584) ~[armeria-grpc-1.3.0.jar:na]
        at org.novonetworks.app.ArmeriaServerConfigKt.grpcService(ArmeriaServerConfig.kt:51) ~[main/:na]
        at org.novonetworks.app.ArmeriaServerConfigKt$armeriaServerConfig$1$1$$special$$inlined$bean$2.get(BeanDefinitionDsl.kt:1163) ~[main/:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1233) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1175) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:571) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[spring-beans-5.3.1.jar:5.3.1]
        ... 40 common frames omitted


FAILURE: Build failed with an exception.
```

**Comment by wickedev** [comment]
https://github.com/curioswitch/curiostack/pull/604 merged. When new version of protobuf-jackson released is released, could bump up dependency.

**Comment by wickedev** [comment]
protobuf-jackson new version released https://github.com/curioswitch/curiostack/releases/tag/protobuf-jackson-1.2.0

**Comment by ikhoon** [comment]
> protobuf-jackson new version released [curioswitch/curiostack@`protobuf-jackson-1.2.0` (release)](https://github.com/curioswitch/curiostack/releases/tag/protobuf-jackson-1.2.0)

Nice. We are going to upgrade `protobuf-jackson-1.2.0` before releasing the next version of Armeria.
