### ISSUE TITLE
`ClosedStreamException` triggered by `ArmeriaServerCall.doSendMessage()` not handled by Armeria

### ISSUE THREAD

**Issue by trustin** [line/armeria#3452]
We got the following exception report from a user at our Slack workspace:

```
2021-04-12 14:14:02.858  WARN 8324 --- [-worker-nio-2-8] i.n.u.concurrent.AbstractEventExecutor   : A task raised an exception. Task: com.linecorp.armeria.common.RequestContext$$Lambda$1068/66855464@6d21f471
com.linecorp.armeria.common.stream.ClosedStreamException: null
	at com.linecorp.armeria.common.stream.ClosedStreamException.get(ClosedStreamException.java:37) ~[armeria-1.5.0.jar:na]
	at com.linecorp.armeria.common.stream.StreamWriter.write(StreamWriter.java:71) ~[armeria-1.5.0.jar:na]
	at com.linecorp.armeria.server.grpc.ArmeriaServerCall.doSendMessage(ArmeriaServerCall.java:287) ~[armeria-grpc-1.5.0.jar:na]
	at com.linecorp.armeria.server.grpc.ArmeriaServerCall.lambda$sendMessage$4(ArmeriaServerCall.java:270) ~[armeria-grpc-1.5.0.jar:na]
	at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:522) ~[armeria-1.5.0.jar:na]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [netty-common-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497) [netty-transport-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.55.Final.jar:4.1.55.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_281]
```

According to the user, the exception is triggered when a server attempts to write something to the stream cancelled by a client. The stack trace shows that we did not catch the exception but just left it propagated to Netty. We should instead let it go to a `RequestLog` or discard it if that makes sense.

**Comment by ikhoon** [comment]
Slack thread: https://line-armeria.slack.com/archives/C1NGPBUH2/p1618229844143500
