### ISSUE TITLE
Test failure: PropertiesEndpointGroupTest

### ISSUE THREAD

**Issue by minwoox** [line/armeria#3474]
```
PropertiesEndpointGroupTest > endpointChangePropagatesToListeners FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in com.linecorp.armeria.client.endpoint.PropertiesEndpointGroupTest that uses com.linecorp.armeria.client.endpoint.EndpointGroup
    Expected size:<1> but was:<2> in:
    <[Endpoint{127.0.0.1:8080, weight=1000}, Endpoint{127.0.0.1:8081, weight=1000}]> within 1 minutes.
        at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
        at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:679)
        at com.linecorp.armeria.client.endpoint.PropertiesEndpointGroupTest.endpointChangePropagatesToListeners(PropertiesEndpointGroupTest.java:275)

        Caused by:
        java.lang.AssertionError:
        Expected size:<1> but was:<2> in:
        <[Endpoint{127.0.0.1:8080, weight=1000}, Endpoint{127.0.0.1:8081, weight=1000}]>
            at com.linecorp.armeria.client.endpoint.PropertiesEndpointGroupTest.lambda$endpointChangePropagatesToListeners$7(PropertiesEndpointGroupTest.java:275)
```

**Comment by kojilin** [comment]
Is it possible that event comes too fast and read file not reflect the latest change?
