### ISSUE TITLE
Test failure: `ArmeriaSpringActuatorAutoConfigurationSecureTest.normal()`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3491]
```
ArmeriaSpringActuatorAutoConfigurationSecureTest > normal() FAILED
    org.opentest4j.AssertionFailedError: 
    Expecting:
     <404>
    to be equal to:
     <200>
    but was not.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at com.linecorp.armeria.spring.actuate.ArmeriaSpringActuatorAutoConfigurationSecureTest.assertStatus(ArmeriaSpringActuatorAutoConfigurationSecureTest.java:86)
        at com.linecorp.armeria.spring.actuate.ArmeriaSpringActuatorAutoConfigurationSecureTest.lambda$normal$1(ArmeriaSpringActuatorAutoConfigurationSecureTest.java:75)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.linecorp.armeria.spring.actuate.ArmeriaSpringActuatorAutoConfigurationSecureTest.normal(ArmeriaSpringActuatorAutoConfigurationSecureTest.java:69)
```

**Comment by kojilin** [comment]
Hard to reproduce at my local env, do we have failed test report or more context to check.

**Comment by ikhoon** [comment]
I found the failed test from GitHub Actions log. https://github.com/line/armeria/runs/2466066386?check_suite_focus=true#step:7:1647
We have encountered new flaky tests after using GitHub Actions. 😭

**Comment by ikhoon** [comment]
I finally found out that this is caused by my stupid mistake. 🙊
We have to build `docs-client` module first to test `DocService`. However I added `-PnoWeb` option while trying to improve CI build speed.

This will be fixed by https://github.com/line/armeria/pull/3498/commits/769209b4a28ab9eb9e10f48dbd65c928dfb309f4
