### ISSUE TITLE
Test failure: `ConsulEndpointGroupTest`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3514]
https://github.com/line/armeria/pull/3498/checks?check_run_id=2489966810#step:7:2262
```
ConsulEndpointGroupTest > testConsulEndpointGroupWithUrl() FAILED
    java.util.concurrent.CompletionException: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
        at java.base/java.util.concurrent.CompletableFuture.reportJoin(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.join(Unknown Source)
        at com.linecorp.armeria.common.util.EventLoopCheckingFuture.join(EventLoopCheckingFuture.java:88)
        at com.linecorp.armeria.client.consul.ConsulEndpointGroupTest.testConsulEndpointGroupWithUrl(ConsulEndpointGroupTest.java:108)

        Caused by:
        io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
```
```
ConsulEndpointGroupTest > testConsulEndpointGroupWithClient() FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in com.linecorp.armeria.client.consul.ConsulEndpointGroupTest that uses com.linecorp.armeria.client.consul.ConsulEndpointGroup 
    Actual and expected should have same size but actual size is:
     <2>
    while expected size is:
     <3>
    Actual was:
     [Endpoint{10.240.33.21:30659, weight=1000},
        Endpoint{10.240.33.21:50991, weight=1000}]
    Expected was:
     [Endpoint{localhost:52274, weight=2},
        Endpoint{127.0.0.1:50991, weight=4},
        Endpoint{127.0.0.1:30659, weight=2}] within 3 seconds.
        at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
        at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:679)
        at com.linecorp.armeria.client.consul.ConsulEndpointGroupTest.testConsulEndpointGroupWithClient(ConsulEndpointGroupTest.java:76)

        Caused by:
        java.lang.AssertionError: 
        Actual and expected should have same size but actual size is:
         <2>
        while expected size is:
         <3>
        Actual was:
         [Endpoint{10.240.33.21:30659, weight=1000},
            Endpoint{10.240.33.21:50991, weight=1000}]
        Expected was:
         [Endpoint{localhost:52274, weight=2},
            Endpoint{127.0.0.1:50991, weight=4},
            Endpoint{127.0.0.1:30659, weight=2}]
            at com.linecorp.armeria.client.consul.ConsulEndpointGroupTest.lambda$testConsulEndpointGroupWithClient$0(ConsulEndpointGroupTest.java:77)
```

**Comment by ikhoon** [comment]
```
ConsulUpdatingListenerTest > testHealthyServiceWithAdditionalCheckRule() FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a com.linecorp.armeria.server.consul.ConsulUpdatingListenerTest 
    Actual and expected should have same size but actual size is:
     <2>
    while expected size is:
     <3>
    Actual was:
     [Endpoint{127.0.0.1:13213, weight=1000}, Endpoint{127.0.0.1:34648, weight=1000}]
    Expected was:
     [Endpoint{localhost:20458, weight=2},
        Endpoint{127.0.0.1:34648, weight=4},
        Endpoint{127.0.0.1:13213, weight=2}] within 10 seconds.
        at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
        at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:679)
        at com.linecorp.armeria.server.consul.ConsulUpdatingListenerTest.testHealthyServiceWithAdditionalCheckRule(ConsulUpdatingListenerTest.java:137)

        Caused by:
        java.lang.AssertionError: 
        Actual and expected should have same size but actual size is:
         <2>
        while expected size is:
         <3>
        Actual was:
         [Endpoint{127.0.0.1:13213, weight=1000}, Endpoint{127.0.0.1:34648, weight=1000}]
        Expected was:
         [Endpoint{localhost:20458, weight=2},
            Endpoint{127.0.0.1:34648, weight=4},
            Endpoint{127.0.0.1:13213, weight=2}]
            at com.linecorp.armeria.server.consul.ConsulUpdatingListenerTest.lambda$testHealthyServiceWithAdditionalCheckRule$4(ConsulUpdatingListenerTest.java:138)
```

**Comment by ikhoon** [comment]
```
ConsulUpdatingListenerTest > testThatDefaultCheckMethodIsHead() FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a com.linecorp.armeria.server.consul.ConsulUpdatingListenerTest 
    Expecting:
     <0>
    to be equal to:
     <1>
    but was not within 10 seconds.
        at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
        at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:679)
        at com.linecorp.armeria.server.consul.ConsulUpdatingListenerTest.testThatDefaultCheckMethodIsHead(ConsulUpdatingListenerTest.java:103)

        Caused by:
        org.opentest4j.AssertionFailedError: 
        Expecting:
         <0>
        to be equal to:
         <1>
        but was not.
            at jdk.internal.reflect.GeneratedConstructorAccessor17.newInstance(Unknown Source)
            at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
            at com.linecorp.armeria.server.consul.ConsulUpdatingListenerTest.lambda$testThatDefaultCheckMethodIsHead$0(ConsulUpdatingListenerTest.java:105)
```

**Comment by minwoox** [comment]
https://github.com/line/armeria/issues/3514#issuecomment-831123029 this case is not fixed yet.
https://github.com/line/armeria/pull/3588/checks?check_run_id=2673445503#step:7:1003
