### ISSUE TITLE
Test failure: `HelloServiceTest.getLotsOfReplies()`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3518]
https://github.com/line/armeria/pull/3515/checks?check_run_id=2491260395#step:7:1931
```
> Task :examples:grpc-example:test

HelloServiceTest > getLotsOfReplies() FAILED
    org.awaitility.core.ConditionTimeoutException: org.awaitility.core.ConditionFactory expected (<true> or <true>) but was <false> within 10 seconds.
        at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
        at org.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:86)
        at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
        at org.awaitility.core.ConditionFactory.untilAtomic(ConditionFactory.java:736)
        at org.awaitility.core.ConditionFactory.untilTrue(ConditionFactory.java:746)
        at example.armeria.grpc.HelloServiceTest.getLotsOfReplies(HelloServiceTest.java:120)
```

**Comment by ikhoon** [comment]
https://github.com/line/armeria/runs/4879715589?check_suite_focus=true#step:6:1493

A similar failure:
```
HelloServiceTest > lotsOfReplies(SerializationFormat) > com.linecorp.armeria.server.scalapb.HelloServiceTest.lotsOfReplies(SerializationFormat)[1] FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a com.linecorp.armeria.server.scalapb.HelloServiceTest 
    Expecting value to be true but was false within 10 seconds.
        at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:164)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:939)
        at app//org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:723)
        at app//com.linecorp.armeria.server.scalapb.HelloServiceTest.lotsOfReplies(HelloServiceTest.scala:80)
```

**Comment by kojilin** [comment]
About this, shorten the helloservice interval or making the await time longer? And also show the message with sequence to help checking ?

**Comment by ikhoon** [comment]
> await time longer?

Sounds good. It would be better to increase the timeout. JFYI, the corresponding service takes 5 seconds to respond without additional delays.
https://github.com/line/armeria/blob/67c25e242e8604331bdd8696a97d26604eb114af/scalapb/scalapb_2.13/src/test/scala/com/linecorp/armeria/server/scalapb/HelloServiceImpl.scala#L59-L62

**Comment by kojilin** [comment]
Yeah, I'm thinking it may good to add error message with sequence at `await().untilAsserted(()...`, maybe it still get 5 or :thinking: 
https://github.com/line/armeria/blob/master/scalapb/scalapb_2.13/src/test/scala/com/linecorp/armeria/server/scalapb/HelloServiceTest.scala#L75
