### ISSUE TITLE
Test failure: `CuratorServiceDiscoveryCompatibilityTest.registeredInstancesAreSameWhenUsingServiceDiscoveryImplAndUpdatingListener()`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3519]
```
CuratorServiceDiscoveryCompatibilityTest > registeredInstancesAreSameWhenUsingServiceDiscoveryImplAndUpdatingListener() FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in com.linecorp.armeria.common.zookeeper.ZooKeeperTestUtil that uses com.linecorp.armeria.server.Server 
    Expecting code not to raise a throwable but caught
      <"java.util.concurrent.CompletionException: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
    	at java.base/java.util.concurrent.CompletableFuture.reportJoin(Unknown Source)
    	at java.base/java.util.concurrent.CompletableFuture.join(Unknown Source)
    	at com.linecorp.armeria.common.util.EventLoopCheckingFuture.join(EventLoopCheckingFuture.java:88)
    	at com.linecorp.armeria.common.zookeeper.ZooKeeperTestUtil.lambda$startServerWithRetries$0(ZooKeeperTestUtil.java:72)
    	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:62)
    	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:877)
    	at org.assertj.core.api.AssertionsForClassTypes.assertThatCode(AssertionsForClassTypes.java:848)
    	at org.assertj.core.api.Assertions.assertThatCode(Assertions.java:1255)
    	at com.linecorp.armeria.common.zookeeper.ZooKeeperTestUtil.lambda$startServerWithRetries$1(ZooKeeperTestUtil.java:72)
    	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
    	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:222)
    	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:209)
    	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    	at org.awaitility.core.SameThreadExecutorService.execute(SameThreadExecutorService.java:79)
    	at java.base/java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
    	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:99)
    	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
    	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
    	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
    	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:679)
    	at com.linecorp.armeria.common.zookeeper.ZooKeeperTestUtil.startServerWithRetries(ZooKeeperTestUtil.java:71)
```

**Comment by ikhoon** [comment]
This is also fixed by https://github.com/line/armeria/pull/3515/files#diff-99355a4c7f349dbf1c806998ba9928bca2d490e1283e544bedbc9c72d2cbd924
