### ISSUE TITLE
Test failure: `KeepAliveHandlerTest.testMaxConnectionAge`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3529]
https://github.com/line/armeria/pull/3483/checks?check_run_id=2514877061#step:7:1122
```
KeepAliveHandlerTest > testMaxConnectionAge() FAILED
    org.opentest4j.AssertionFailedError: 
    Expecting:
     <false>
    to be equal to:
     <true>
    but was not.
        at jdk.internal.reflect.GeneratedConstructorAccessor33.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at com.linecorp.armeria.internal.common.KeepAliveHandlerTest.testMaxConnectionAge(KeepAliveHandlerTest.java:231)
```

**Comment by trustin** [comment]
This occurred recently at: https://github.com/line/armeria/pull/3533/checks?check_run_id=2540487123
