### ISSUE TITLE
Test failure: `GracefulShutdownIntegrationTest.testBaseline()`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3554]
GracefulShutdownIntegrationTest > testBaseline() FAILED
    java.lang.AssertionError: 
    Expecting:
     <4152826200L>
    to be between:
     [2682290400L, 3482290400L]
        at com.linecorp.armeria.it.server.GracefulShutdownIntegrationTest.testBaseline(GracefulShutdownIntegrationTest.java:156)

**Comment by ikhoon** [comment]
```
GracefulShutdownIntegrationTest > testBaseline() FAILED
    java.lang.AssertionError: 
    Expecting:
     <3587462600L>
    to be between:
     [2638880000L, 3438880000L]
        at com.linecorp.armeria.it.server.GracefulShutdownIntegrationTest.testBaseline(GracefulShutdownIntegrationTest.java:156)
```

**Comment by minwoox** [comment]
```
GracefulShutdownIntegrationTest > interruptsSlowRequests() FAILED
    java.lang.AssertionError: 
    Expecting:
     <4960509200L>
    to be between:
     [3635689850L, 4835689850L]
        at com.linecorp.armeria.it.server.GracefulShutdownIntegrationTest.interruptsSlowRequests(GracefulShutdownIntegrationTest.java:226)
```
https://github.com/line/armeria/runs/2682355027?check_suite_focus=true#step:7:1457
Found a similar failure in another test
