### ISSUE TITLE
Test failure: `KeepAliveHandlerTest`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3560]
```
KeepAliveHandlerTest > [1] connectionIdleTimeout=2000, pingInterval=0, mode=CONNECTION_IDLE FAILED
    java.lang.AssertionError: 
    Expecting <AtomicInteger(1)> to have value:
      <0>
    but did not.
        at com.linecorp.armeria.internal.common.KeepAliveHandlerTest.testKeepAlive(KeepAliveHandlerTest.java:295)
```

**Comment by minwoox** [comment]
```
KeepAliveHandlerTest > shouldNotWritePingIfConnectionIsActive() FAILED
    java.lang.AssertionError: 
    Expecting AtomicInteger(1) to have value:
      0
    but did not.
        at com.linecorp.armeria.internal.common.KeepAliveHandlerTest.shouldNotWritePingIfConnectionIsActive(KeepAliveHandlerTest.java:287)
```

**Comment by minwoox** [comment]
```

**Comment by trustin** [comment]
Marked it as `@Flaky` and we're not seeing the failure anymore.
