### ISSUE TITLE
Test failure: HttpServerTest

### ISSUE THREAD

**Issue by minwoox** [line/armeria#3586]
```
HttpServerTest > [1] client=DefaultWebClient(FunctionalDecoratingHttpClient(com.linecorp.armeria.client.HttpClientDelegate@56adf8d5, com.linecorp.armeria.server.HttpServerTest$ClientAndProtocolProvider$$Lambda$1723/0x00000008014461a8@6b4912ff)) FAILED
    java.lang.AssertionError: 
    Expecting code to raise a throwable.
        at com.linecorp.armeria.server.HttpServerTest.testTooLargeContentToNonExistentService(HttpServerTest.java:613)
```
https://github.com/line/armeria/pull/3583/checks?check_run_id=2640909050#step:7:1080

**Comment by minwoox** [comment]
```
HttpServerTest > testTooLargeContentToNonExistentService(WebClient) > com.linecorp.armeria.server.HttpServerTest.testTooLargeContentToNonExistentService(WebClient)[2] FAILED
    java.lang.AssertionError: 
    Expecting code to raise a throwable.
        at com.linecorp.armeria.server.HttpServerTest.testTooLargeContentToNonExistentService(HttpServerTest.java:613)
```
