### ISSUE TITLE
Cannot use SelfSignedCertificateExtension on Java 16

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#3673]
Trying to run a build's tests against Java 16, I get this stack trace

```java
        Caused by:
        java.lang.RuntimeException: failed to create a self signed certificate
            at com.linecorp.armeria.server.VirtualHostBuilder.build(VirtualHostBuilder.java:1022)
            at com.linecorp.armeria.server.ServerBuilder.build(ServerBuilder.java:1537)
            at com.linecorp.armeria.internal.testing.ServerRuleDelegate.start(ServerRuleDelegate.java:90)
            at com.linecorp.armeria.internal.testing.ServerRuleDelegate.before(ServerRuleDelegate.java:59)
            at com.linecorp.armeria.testing.junit5.server.ServerExtension.before(ServerExtension.java:68)
            ... 63 more

            Caused by:
            java.security.cert.CertificateException: No provider succeeded to generate a self-signed certificate. See debug log for the root cause.
                at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:250)
                at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:167)
                at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:126)
                at com.linecorp.armeria.server.VirtualHostBuilder.selfSignedCertificate(VirtualHostBuilder.java:1065)
                at com.linecorp.armeria.server.VirtualHostBuilder.build(VirtualHostBuilder.java:1020)
                ... 67 more

                Caused by:
                java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
                    at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:246)
                    ... 71 more

                    Caused by:
                    java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.BouncyCastleProvider
                        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
                        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
                        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
```

Bouncycastle seems to indicate support is only up to 1.5-1.15. Not sure what they intend for 1.16, but is there a way to skip bouncycastle on Java 16 here for something that works best-effort?

**Comment by anuraaga** [comment]
Found Netty issue https://github.com/netty/netty/issues/10317 which was closed. If there's no way to get it to work with modern vanilla JDK than it's too bad, but it seems a bit surprising for just generating a self signed certificate, I'd be surprised if the ability to do that with the Sun provider was just completely removed...

**Comment by anuraaga** [comment]
I suppose one option is to vendor in the SelfSignedCertificate code to access from the SelfSignedCertificateExtension using Armeria's shaded bouncycastle

**Comment by trustin** [comment]
Oh, that's too bad. Yeah, using the shaded BouncyCastle sounds like a good idea to me.
