### ISSUE TITLE
Test failure: `ThriftOverHttpClientTest.testHelloServiceSync` and `testMessageLogsForException`

### ISSUE THREAD

**Issue by trustin** [line/armeria#3684]
```
> Task :thrift0.13:shadedTest FAILED

ThriftOverHttpClientTest > testHelloServiceSync(ClientOptions, SerializationFormat, SessionProtocol) > com.linecorp.armeria.client.thrift.ThriftOverHttpClientTest.testHelloServiceSync(ClientOptions, SerializationFormat, SessionProtocol)[15] FAILED
    java.lang.IllegalArgumentException: expectedSize cannot be negative but was: -1
        at com.linecorp.armeria.internal.shaded.guava.collect.CollectPreconditions.checkNonnegative(CollectPreconditions.java:39)
        at com.linecorp.armeria.internal.shaded.guava.collect.ImmutableList.builderWithExpectedSize(ImmutableList.java:731)
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.drainAll(DefaultStreamMessage.java:233)
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.collectAll(DefaultStreamMessage.java:213)
        at com.linecorp.armeria.common.stream.DefaultStreamMessage.lambda$collect$1(DefaultStreamMessage.java:192)
        at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:546)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

ThriftOverHttpClientTest > testMessageLogsForException(ClientOptions, SerializationFormat, SessionProtocol) > com.linecorp.armeria.client.thrift.ThriftOverHttpClientTest.testMessageLogsForException(ClientOptions, SerializationFormat, SessionProtocol)[40] FAILED
    java.lang.AssertionError: 
    Expecting:
      <java.lang.IllegalArgumentException: expectedSize cannot be negative but was: -1>
    to be an instance of:
      <org.apache.thrift.TApplicationException>
    but was:
      <"java.lang.IllegalArgumentException: expectedSize cannot be negative but was: -1
    	at com.linecorp.armeria.internal.shaded.guava.collect.CollectPreconditions.checkNonnegative(CollectPreconditions.java:39)
    	at com.linecorp.armeria.internal.shaded.guava.collect.ImmutableList.builderWithExpectedSize(ImmutableList.java:731)
    	at com.linecorp.armeria.common.stream.DefaultStreamMessage.drainAll(DefaultStreamMessage.java:233)
    	at com.linecorp.armeria.common.stream.DefaultStreamMessage.collectAll(DefaultStreamMessage.java:213)
    	at com.linecorp.armeria.common.stream.DefaultStreamMessage.lambda$collect$1(DefaultStreamMessage.java:192)
    	at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:546)
    	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
    	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
    	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
    	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    	at java.lang.Thread.run(Thread.java:748)
    ">
        at com.linecorp.armeria.client.thrift.ThriftOverHttpClientTest.testMessageLogsForException(ThriftOverHttpClientTest.java:684)
```

**Comment by mauhiz** [comment]
Just to report that this error happens in the wild with 1.9.2

**Comment by ikhoon** [comment]
Sorry about that. 😭 I am preparing to release a new version.
