### ISSUE TITLE
`NullPointerException` in `client.HttpResponseDecoder`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3729]
I got reported a NPE issue from [a Armeria Slack thread](https://line-armeria.slack.com/archives/C1NGPBUH2/p1627494312253700?thread_ts=1626604451.208400&cid=C1NGPBUH2).
```
Caused by:java.lang.NullPointerException: Cannot invoke "com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(java.lang.Throwable)" because "res" is null(Cannot invoke "com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(java.lang.Throwable)" because "res" is null)
  at com.linecorp.armeria.client.HttpResponseDecoder.failUnfinishedResponses(HttpResponseDecoder.java:131)
  at com.linecorp.armeria.client.HttpSessionHandler.channelInactive(HttpSessionHandler.java:415)
```

**Comment by ikhoon** [comment]
`HttpResponseDecoder` MUST be executed in an event loop. The NPE might be caused by recursive calls of `failUnfinishedResponses()`.
Even though we use `Iterator`, a null reference could be returned.
```java
private final IntObjectMap<String> intObjectHashMap = new IntObjectHashMap<>();
private final Map<Integer, String> hashMap = new HashMap<>();

@Test
void intObjectHashMap() {
    intObjectHashMap.put(1, "A");
    intObjectHashMap.put(2, "B");
    intObjectHashMap.put(3, "C");
    intObjectHashMap.put(4, "D");
    intObjectHashMap.put(5, "E");
    // java.lang.AssertionError: null is not a legitimate internal value. Concurrent Modification?
    removeAll(intObjectHashMap);
}

@Test
void jdkHashMap() {
    hashMap.put(1, "A");
    hashMap.put(2, "B");
    hashMap.put(3, "C");
    hashMap.put(4, "D");
    hashMap.put(5, "E");
    // java.util.ConcurrentModificationException
    removeAll(hashMap);
}

void removeAll(Map<Integer, String> strings) {
    for (final Iterator<String> iterator = strings.values().iterator();
         iterator.hasNext();) {
        final String res = iterator.next();
        System.out.println("removed: " + res);
        // To avoid calling removeResponse by res.close(cause), remove before closing.
        iterator.remove();
        removeAll(strings);
    }
```

**Comment by kojilin** [comment]
Just curious there is a possibility that calling `failUnfinishedResponses` recursively?

**Comment by ikhoon** [comment]
> Just curious there is a possibility that calling `failUnfinishedResponses` recursively(didn't see the stacktrace and it should be in the same thread)?

My words were wrong. `failUnfinishedResponses` will not be recursively called. However, the problem is still reproduced if `Map.remove()` is invoked while iterating a `Map`.
```java
private final IntObjectMap<String> intObjectHashMap = new IntObjectHashMap<>();

@Test
void intObjectHashMap() {
    intObjectHashMap.put(1, "A");
    intObjectHashMap.put(2, "B");
    // java.lang.AssertionError: null is not a legitimate internal value. Concurrent Modification?
    removeAll(intObjectHashMap);
}

void removeAll(Map<Integer, String> strings) {
    for (final Iterator<String> iterator = strings.values().iterator();
         iterator.hasNext(); ) {
        final String item = iterator.next();
        iterator.remove();
        removeOne(strings);
    }
}

void removeOne(Map<Integer, String> strings) {
    strings.remove(2);
}
```
