### ISSUE TITLE
`NoSuchElementException` raised by `RampingUpEndpointWeightSelector`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#3776]
```
  java.util.NoSuchElementException: null
    at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:413)
    at com.linecorp.armeria.client.endpoint.WeightRampingUpStrategy$RampingUpEndpointWeightSelector.updateEndpoints(WeightRampingUpStrategy.java:188)
    at com.linecorp.armeria.client.endpoint.WeightRampingUpStrategy$RampingUpEndpointWeightSelector.lambda$new$0(WeightRampingUpStrategy.java:143)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:835)
```

I got a report from @m50d 
> I think this was during a restart, not hugely important but it seems like a bug somehow? AFAICS that can only happen if RampingUpEndpointWeightSelector#close ran and updateEndpoints  ran afterwards or in parallel, but they're supposed to only run on the same single-threaded executor and close should only be called after the EndpointGroup (which is the only place that calls updateEndpoints) has closed. Looking at the code I can't see exactly how that scenario would occur, but maybe there's an EndpointGroup implementation that doesn't close properly?

**Comment by mauhiz** [comment]
Is it known whether the endpoint / endpoint group recovers from this?
