### ISSUE TITLE
@LocalArmeriaPort not working after upgrade to 1.11.0

### ISSUE THREAD

**Issue by eisig** [line/armeria#3831]
@LocalArmeriaPort not working after upgrade to 1.11.0 (from 1.9.2)  
seems relative to https://github.com/line/armeria/pull/3762

```
    @LocalArmeriaPort
    Integer localPort;
```
```
Caused by: java.lang.IllegalStateException: no active local ports for http: []
	at com.linecorp.armeria.server.Server.lambda$activeLocalPort0$2(Server.java:243) ~[armeria-1.11.0.jar:na]
	at java.base/java.util.Optional.orElseThrow(Optional.java:408) ~[na:na]
	at com.linecorp.armeria.server.Server.activeLocalPort0(Server.java:240) ~[armeria-1.11.0.jar:na]
	at com.linecorp.armeria.server.Server.activeLocalPort(Server.java:231) ~[armeria-1.11.0.jar:na]
	at com.linecorp.armeria.spring.AbstractArmeriaBeanPostProcessor$LocalArmeriaPortElement.<init>(AbstractArmeriaBeanPostProcessor.java:175) ~[armeria-spring-boot2-autoconfigure-1.11.0.jar:na]
	at com.linecorp.armeria.spring.AbstractArmeriaBeanPostProcessor$LocalArmeriaPortElement.<init>(AbstractArmeriaBeanPostProcessor.java:159) ~[armeria-spring-boot2-autoconfigure-1.11.0.jar:na]
	at com.linecorp.armeria.spring.AbstractArmeriaBeanPostProcessor.lambda$buildLocalArmeriaPortMetadata$0(AbstractArmeriaBeanPostProcessor.java:103) ~[armeria-spring-boot2-autoconfigure-1.11.0.jar:na]
	at org.springframework.util.ReflectionUtils.doWithLocalFields(ReflectionUtils.java:673) ~[spring-core-5.3.10.jar:5.3.10]
	at com.linecorp.armeria.spring.AbstractArmeriaBeanPostProcessor.buildLocalArmeriaPortMetadata(AbstractArmeriaBeanPostProcessor.java:96) ~[armeria-spring-boot2-autoconfigure-1.11.0.jar:na]
	at com.linecorp.armeria.spring.AbstractArmeriaBeanPostProcessor.findLocalArmeriaPortMetadata(AbstractArmeriaBeanPostProcessor.java:81) ~[armeria-spring-boot2-autoconfigure-1.11.0.jar:na]
	at com.linecorp.armeria.spring.ArmeriaBeanPostProcessor.postProcessProperties(ArmeriaBeanPostProcessor.java:44) ~[armeria-spring-boot2-autoconfigure-1.11.0.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619) ~[spring-beans-5.3.10.jar:5.3.10]
	... 14 common frames omitted


Process finished with exit code 1

````

**Comment by heowc** [comment]
Hmm... Can you give us some code to reproduce?🤔

We are using the annotation in our test code, but no problem was found.

**Comment by eisig** [comment]
@heowc https://github.com/eisig/armeria-localport-issue
This is simple demo.

**Comment by heowc** [comment]
It seems to be related to [this comment](https://github.com/line/armeria/pull/3226#discussion_r549201175).

See https://github.com/line/armeria/pull/3226, https://github.com/line/armeria/pull/3245

**Comment by eisig** [comment]
@heowc Thanks. 
If not use in beans, it works find.
