### ISSUE TITLE
Received a `Maximum active streams violated for this endpoint.` from client side

### ISSUE THREAD

**Issue by jrhee17** [line/armeria#3858]
armeria version: 1.8.0
verified client-side isn't changing `MAX_CONCURRENT_STREAMS`

```
 java.util.concurrent.CompletionException: com.linecorp.armeria.client.UnprocessedRequestException: io.netty.handler.codec.http2.Http2Exception$StreamException: Maximum active streams violated for this endpoint.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at com.linecorp.armeria.internal.common.HttpObjectAggregator.fail(HttpObjectAggregator.java:145)
	at com.linecorp.armeria.internal.common.HttpObjectAggregator.onError(HttpObjectAggregator.java:61)
	at com.linecorp.armeria.common.stream.DeferredStreamMessage$ForwardingSubscriber.onError(DeferredStreamMessage.java:347)
	at com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:276)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:284)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:276)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:448)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:391)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.doRequest(DefaultStreamMessage.java:259)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.request(DefaultStreamMessage.java:242)
	at com.linecorp.armeria.common.stream.AbstractStreamMessage$SubscriptionImpl.request(AbstractStreamMessage.java:218)
	at com.linecorp.armeria.common.stream.DeferredStreamMessage$ForwardingSubscriber.onSubscribe(DeferredStreamMessage.java:335)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:147)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:130)
	at com.linecorp.armeria.common.stream.AbstractStreamMessage.subscribe(AbstractStreamMessage.java:67)
	at com.linecorp.armeria.common.stream.DeferredStreamMessage.safeOnSubscribeToUpstream(DeferredStreamMessage.java:282)
	at com.linecorp.armeria.common.stream.DeferredStreamMessage.delegate(DeferredStreamMessage.java:121)
	at com.linecorp.armeria.common.DeferredHttpResponse.delegate(DeferredHttpResponse.java:48)
	at com.linecorp.armeria.common.DeferredHttpResponse.lambda$delegateWhenComplete$0(DeferredHttpResponse.java:59)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at com.linecorp.armeria.client.retry.RetryingClient.lambda$handleBackoff$9(RetryingClient.java:398)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:946)
	at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2266)
	at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:143)
	at com.linecorp.armeria.client.retry.RetryingClient.lambda$handleResponse$6(RetryingClient.java:352)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
	at com.linecorp.armeria.client.retry.RetryingClient.handleResponse(RetryingClient.java:312)
	at com.linecorp.armeria.client.retry.RetryingClient.doExecute0(RetryingClient.java:297)
	at com.linecorp.armeria.client.retry.RetryingClient.lambda$handleBackoff$8(RetryingClient.java:392)
	at com.linecorp.armeria.common.RequestContext.lambda$makeContextAware$3(RequestContext.java:546)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.linecorp.armeria.client.UnprocessedRequestException: io.netty.handler.codec.http2.Http2Exception$StreamException: Maximum active streams violated for this endpoint.
	at com.linecorp.armeria.client.UnprocessedRequestException.of(UnprocessedRequestException.java:45)
	at com.linecorp.armeria.client.HttpRequestSubscriber.operationComplete(HttpRequestSubscriber.java:134)
	at com.linecorp.armeria.client.HttpRequestSubscriber.operationComplete(HttpRequestSubscriber.java:54)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
	at com.linecorp.armeria.client.HttpRequestSubscriber.writeFirstHeader(HttpRequestSubscriber.java:205)
	at com.linecorp.armeria.client.HttpRequestSubscriber.onSubscribe(HttpRequestSubscriber.java:181)
	at com.linecorp.armeria.common.stream.DefaultStreamMessageDuplicator$DownstreamSubscription.invokeOnSubscribe0(DefaultStreamMessageDuplicator.java:672)
	at com.linecorp.armeria.common.stream.DefaultStreamMessageDuplicator$DownstreamSubscription.invokeOnSubscribe(DefaultStreamMessageDuplicator.java:663)
	at com.linecorp.armeria.common.stream.DefaultStreamMessageDuplicator$StreamMessageProcessor.doSubscribe(DefaultStreamMessageDuplicator.java:292)
	at com.linecorp.armeria.common.stream.DefaultStreamMessageDuplicator$StreamMessageProcessor.subscribe(DefaultStreamMessageDuplicator.java:272)
	at com.linecorp.armeria.common.stream.DefaultStreamMessageDuplicator$ChildStreamMessage.subscribe0(DefaultStreamMessageDuplicator.java:537)
	at com.linecorp.armeria.common.stream.DefaultStreamMessageDuplicator$ChildStreamMessage.subscribe(DefaultStreamMessageDuplicator.java:525)
	at com.linecorp.armeria.common.stream.DefaultStreamMessageDuplicator$ChildStreamMessage.subscribe(DefaultStreamMessageDuplicator.java:515)
	at com.linecorp.armeria.common.stream.StreamMessageWrapper.subscribe(StreamMessageWrapper.java:80)
	at com.linecorp.armeria.client.HttpSessionHandler.invoke(HttpSessionHandler.java:203)
	at com.linecorp.armeria.client.HttpClientDelegate.doExecute(HttpClientDelegate.java:276)
	at com.linecorp.armeria.client.HttpClientDelegate.acquireConnectionAndExecute(HttpClientDelegate.java:162)
	at com.linecorp.armeria.client.HttpClientDelegate.finishResolve(HttpClientDelegate.java:123)
	at com.linecorp.armeria.client.HttpClientDelegate.execute(HttpClientDelegate.java:106)
	at com.linecorp.armeria.client.HttpClientDelegate.execute(HttpClientDelegate.java:51)
	at com.linecorp.armeria.client.metric.AbstractMetricCollectingClient.execute(AbstractMetricCollectingClient.java:62)
	at com.linecorp.armeria.internal.client.ClientUtil.pushAndExecute(ClientUtil.java:150)
	at com.linecorp.armeria.internal.client.ClientUtil.executeWithFallback(ClientUtil.java:138)
	at com.linecorp.armeria.client.retry.RetryingClient.doExecute0(RetryingClient.java:286)
	... 11 common frames omitted
Caused by: io.netty.handler.codec.http2.Http2Exception$StreamException: Maximum active streams violated for this endpoint.
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:152)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.checkNewStreamAllowed(DefaultHttp2Connection.java:896)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:748)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:668)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders0(DefaultHttp2ConnectionEncoder.java:201)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:151)
	at io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writeHeaders(DecoratingHttp2FrameWriter.java:45)
	at com.linecorp.armeria.client.ClientHttp2ObjectEncoder.doWriteHeaders(ClientHttp2ObjectEncoder.java:73)
	at com.linecorp.armeria.client.ClientHttpObjectEncoder.writeHeaders(ClientHttpObjectEncoder.java:41)
	at com.linecorp.armeria.client.HttpRequestSubscriber.writeFirstHeader(HttpRequestSubscriber.java:204)
	... 30 common frames omitted
```

**Comment by jrhee17** [comment]
Reported by @techno 🙇‍♂️

**Comment by jrhee17** [comment]
> I'm also looking into ways where we can notify the user when the maxConcurrentStreams limit has been changed (perhaps we can catch and re-throw with more details, or fix the exception message upstream in netty) to confirm whether server-side is actually changing the maxConcurrentStreams setting.

It seems like this was fixed with https://github.com/netty/netty/pull/11644 and included in `4.1.68.FINAL`. If this version is applied, at least we can verify if the server-side is actually changing the `maxConcurrentStreams` value.

**Comment by jrhee17** [comment]
Additional note: Rather than trying to fix the issue for users, maybe we can start with providing metrics s.t. users can understand why they are incurring this problem.

Possibly we may be able to record metrics on `numActiveStreams`, `maxActiveStreams` for each endpoint (note that each connection may be configured differently, so we should think of how to provide such metrics).

Another alternative may be to add a callback s.t. users can be notified whenever HTTP/2 settings are changed. (i.e. something like `ConnectionPoolListener`)

**Comment by ks-yim** [comment]
Got the same error in a seemingly different scenario.

This happened when a `WebClient` has a decorator which makes a request to the `same host` as the client it is decorating.
Diagram to better describe the scenario..:
![image](https://user-images.githubusercontent.com/35995647/140905463-4e5b61c2-4ade-4585-a06a-aefcb788d7ee.png)


```
java.util.concurrent.CompletionException: com.linecorp.armeria.client.UnprocessedRequestException: io.netty.handler.codec.http2.Http2Exception$StreamException: Maximum active streams violated for this endpoint: 20
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2158)
	at com.linecorp.armeria.internal.shaded.futures.CompletableFutures.lambda$allAsList$0(CompletableFutures.java:89)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2158)
	at com.linecorp.armeria.common.util.UnmodifiableFuture.doCompleteExceptionally(UnmodifiableFuture.java:139)
	at com.linecorp.armeria.common.util.UnmodifiableFuture.lambda$wrap$0(UnmodifiableFuture.java:98)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2158)
	at com.linecorp.armeria.common.stream.DeferredStreamMessage.lambda$delegate$0(DeferredStreamMessage.java:132)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2158)
	at com.linecorp.armeria.common.stream.StreamMessageCollector.onError(StreamMessageCollector.java:80)
	at com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:267)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:288)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:280)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:417)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:360)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.doRequest(DefaultStreamMessage.java:263)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.request(DefaultStreamMessage.java:246)
	at com.linecorp.armeria.common.stream.AbstractStreamMessage$SubscriptionImpl.request(AbstractStreamMessage.java:209)
	at com.linecorp.armeria.common.stream.StreamMessageCollector.onSubscribe(StreamMessageCollector.java:52)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:148)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.lambda$subscribe$0(DefaultStreamMessage.java:134)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: com.linecorp.armeria.client.UnprocessedRequestException: io.netty.handler.codec.http2.Http2Exception$StreamException: Maximum active streams violated for this endpoint: 20
	at app//com.linecorp.armeria.client.UnprocessedRequestException.of(UnprocessedRequestException.java:45)
	at app//com.linecorp.armeria.client.HttpRequestSubscriber.operationComplete(HttpRequestSubscriber.java:133)
	at app//com.linecorp.armeria.client.HttpRequestSubscriber.operationComplete(HttpRequestSubscriber.java:53)
	at app//io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at app//io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at app//io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at app//io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)
	at app//io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
	at app//io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
	at app//com.linecorp.armeria.client.HttpRequestSubscriber.writeFirstHeader(HttpRequestSubscriber.java:205)
	at app//com.linecorp.armeria.client.HttpRequestSubscriber.onSubscribe(HttpRequestSubscriber.java:180)
	at app//com.linecorp.armeria.common.stream.FixedStreamMessage.subscribe0(FixedStreamMessage.java:131)
	at app//com.linecorp.armeria.common.stream.FixedStreamMessage.subscribe(FixedStreamMessage.java:119)
	at app//com.linecorp.armeria.common.stream.EmptyFixedStreamMessage.subscribe(EmptyFixedStreamMessage.java:29)
	at app//com.linecorp.armeria.common.HeaderOverridingHttpRequest.subscribe(HeaderOverridingHttpRequest.java:94)
	at app//com.linecorp.armeria.client.HttpSessionHandler.invoke(HttpSessionHandler.java:201)
	at app//com.linecorp.armeria.client.HttpClientDelegate.doExecute(HttpClientDelegate.java:239)
	at app//com.linecorp.armeria.client.HttpClientDelegate.acquireConnectionAndExecute0(HttpClientDelegate.java:172)
	at app//com.linecorp.armeria.client.HttpClientDelegate.acquireConnectionAndExecute(HttpClientDelegate.java:141)
	at app//com.linecorp.armeria.client.HttpClientDelegate.lambda$execute$0(HttpClientDelegate.java:99)
	at app//com.linecorp.armeria.client.HttpClientDelegate.resolveAddress(HttpClientDelegate.java:124)
	at app//com.linecorp.armeria.client.HttpClientDelegate.execute(HttpClientDelegate.java:95)
	at app//com.linecorp.armeria.client.HttpClientDelegate.execute(HttpClientDelegate.java:47)
	at app//com.linecorp.channel.auth.client.AuthenticatingClient.lambda$execute$0(AuthenticatingClient.java:32)
	at java.base@16.0.1/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base@16.0.1/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base@16.0.1/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2143)
	at app//com.linecorp.channel.auth.client.strategy.AbstractTokenStrategy.lambda$accessToken$1(AbstractTokenStrategy.java:78)
	at java.base@16.0.1/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base@16.0.1/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base@16.0.1/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base@16.0.1/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2143)
	at app//com.linecorp.armeria.common.util.UnmodifiableFuture.doComplete(UnmodifiableFuture.java:124)
	at app//com.linecorp.armeria.common.util.UnmodifiableFuture.lambda$wrap$0(UnmodifiableFuture.java:100)
	at java.base@16.0.1/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base@16.0.1/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base@16.0.1/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base@16.0.1/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2143)
	at app//com.linecorp.armeria.common.stream.DeferredStreamMessage.lambda$delegate$0(DeferredStreamMessage.java:130)
	at java.base@16.0.1/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base@16.0.1/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base@16.0.1/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base@16.0.1/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2143)
	at app//com.linecorp.armeria.common.stream.StreamMessageCollector.onComplete(StreamMessageCollector.java:67)
	at app//com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:256)
	at app//com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:288)
	at app//com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:280)
	at app//com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:417)
	at app//com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:360)
	at app//com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:316)
	at app//com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:302)
	at app//com.linecorp.armeria.common.stream.DefaultStreamMessage.close(DefaultStreamMessage.java:424)
	at app//com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.closeAction(HttpResponseDecoder.java:338)
	at app//com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.cancelTimeoutOrLog(HttpResponseDecoder.java:371)
	at app//com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:321)
	at app//com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:310)
	at app//com.linecorp.armeria.client.Http2ResponseDecoder.onDataRead(Http2ResponseDecoder.java:273)
	at app//io.netty.handler.codec.http2.Http2FrameListenerDecorator.onDataRead(Http2FrameListenerDecorator.java:36)
	at app//io.netty.handler.codec.http2.Http2EmptyDataFrameListener.onDataRead(Http2EmptyDataFrameListener.java:49)
	at app//io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:307)
	at app//io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
	at app//io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:415)
	at app//io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:250)
	at app//io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159)
	at app//io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at app//io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:173)
	at app//io.netty.handler.codec.http2.DecoratingHttp2ConnectionDecoder.decodeFrame(DecoratingHttp2ConnectionDecoder.java:63)
	at app//io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
	at app//io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	at app//io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at app//io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at app//io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at app//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at app//io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at app//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at app//io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1372)
	at app//io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1246)
	at app//io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1286)
	at app//io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at app//io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at app//io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at app//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at app//io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at app//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at app//io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at app//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at app//io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at app//io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at app//io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at app//io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	... 4 more
Caused by: io.netty.handler.codec.http2.Http2Exception$StreamException: Maximum active streams violated for this endpoint: 20
	at app//io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:152)
	at app//io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.checkNewStreamAllowed(DefaultHttp2Connection.java:902)
	at app//io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:751)
	at app//io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:671)
	at app//io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders0(DefaultHttp2ConnectionEncoder.java:201)
	at app//io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:151)
	at app//com.linecorp.armeria.client.ClientHttp2ObjectEncoder.doWriteHeaders(ClientHttp2ObjectEncoder.java:70)
	at app//com.linecorp.armeria.client.ClientHttpObjectEncoder.writeHeaders(ClientHttpObjectEncoder.java:41)
	at app//com.linecorp.armeria.client.HttpRequestSubscriber.writeFirstHeader(HttpRequestSubscriber.java:204)
	... 95 more
```

**Comment by ks-yim** [comment]
Demonstration..:
https://github.com/ks-yim/max-stream-violated/blob/main/src/test/java/MaxStreamViolatedTest.java

It turns out that I was wrong about the cause in the above comment. It's not related to decorator or 2 different clients with the same host.

The exception occurs when requests are made in a callback of another request like...:
```java
 // exception
client.get("/resource").aggregate().thenRun(() -> concurrentReqToSameHost());

// but exception is not thrown if `concurrentReqToSameHost()` is called in async callback;
client.get("/resource").aggregate().thenRunAsync(() -> concurrentReqToSameHost(), ctx.eventLoop());
```

More on this in the demo code.

**Comment by jrhee17** [comment]
Thanks for the detailed analysis!

I think I understand why the exception occurs for the first case consistently.

The callback in `thenRun()` is run from the eventloop where the response is closed. At this point, `unfinishedResponses` has been decremented, but netty's `numActiveStreams` hasn't been decremented yet.

So I believe the flow is as follows:

1. The first request succeeds and `unfinishedResponses == 0`, but `numActiveStreams == 1`.
2. 10 new requests are queued (since `MAX_CONCURRENT_STREAMS = 10`)
3. The last request fails, since `unfinishedResponses == 9`, but `numActiveStreams == 10`.
4. All subsequent requests try to use the same connection, but fail due to `MAX_CONCURRENT_STREAMS` violation.

I've also verified that the test code passes for the branch #3908

**Comment by ks-yim** [comment]
> I've also verified that the test code passes for the branch

Good to hear that, thanks for the nice work!!

Just 1 more question..:
* Would it be a reliable workaround to use `...Async` callback like in the 2nd case? I am asking this since the `AuthDecorator` that I mentioned in the first place should work with `armeria <= 1.14.0`.

**Comment by jrhee17** [comment]
If this bug is blocking development, then I think the above workaround is fine (assuming that the additional cost for rescheduling the task via `thenRunAsync` is acceptable)

I would also like to note though that the `Maximum active streams..` exception can't be 100% avoided since there are other edge cases where the exception can be thrown until the fix is merged. (although I also think the bug should occur with a very low probability in practice)

I'm unsure how `AuthDecorator` works, but I think calling `execute()` from a decorator shouldn't be very different from calling `execute()` directly on the `WebClient`

**Comment by ks-yim** [comment]
Thanks again.
I've consulted with ikhoon and got almost the same answer. (can't be avoided in some edge cases though I use async callback).

I am thinking about giving a different `ClientFactory` to the `WebClient` used within the decorator rather than using the default.
