### ISSUE TITLE
Intermittent test failure: FlowAnnotatedServiceTest

### ISSUE THREAD

**Issue by minwoox** [line/armeria#3901]
```
FlowAnnotatedServiceTest > test_customDispatcher() FAILED
    org.opentest4j.AssertionFailedError: 
    expected: 200 OK
     but was: 503 Service Unavailable
        at java.base@16.0.2/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base@16.0.2/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
        at java.base@16.0.2/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base@16.0.2/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at app//com.linecorp.armeria.server.kotlin.FlowAnnotatedServiceTest$test_customDispatcher$1.invokeSuspend(FlowAnnotatedServiceTest.kt:103)
        at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at app//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at app//kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at app//kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at app//kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app//com.linecorp.armeria.server.kotlin.FlowAnnotatedServiceTest.test_customDispatcher(FlowAnnotatedServiceTest.kt:101)
```
https://github.com/line/armeria/runs/4016595918?check_suite_focus=true#step:6:1245

**Comment by ks-yim** [comment]
Let me handle this. Seems like a short timeout to test the cancellation behavior may have resulted in this error.
