### ISSUE TITLE
Intermittent test failure: HealthCheckedEndpointGroupLongPollingTest

### ISSUE THREAD

**Issue by minwoox** [line/armeria#3911]
```
HealthCheckedEndpointGroupLongPollingTest > keepEndpointHealthinessWhenLongPollingTimeout() FAILED
    java.lang.AssertionError: 
    Expecting actual:
      1102L
    to be less than or equal to:
      1100L 
        at com.linecorp.armeria.client.endpoint.healthcheck.HealthCheckedEndpointGroupLongPollingTest.keepEndpointHealthinessWhenLongPollingTimeout(HealthCheckedEndpointGroupLongPollingTest.java:198)
```

**Comment by ikhoon** [comment]
Reproduced: https://github.com/line/armeria/runs/4823823566?check_suite_focus=true#step:6:1170 
```
 HealthCheckedEndpointGroupLongPollingTest > keepEndpointHealthinessWhenLongPollingTimeout() FAILED
    java.lang.AssertionError: 
    Expecting actual:
      1126L
    to be less than or equal to:
      1100L 
        at com.linecorp.armeria.client.endpoint.healthcheck.HealthCheckedEndpointGroupLongPollingTest.keepEndpointHealthinessWhenLongPollingTimeout(HealthCheckedEndpointGroupLongPollingTest.java:201)
```

**Comment by minwoox** [comment]
```
HealthCheckedEndpointGroupLongPollingTest > longPollingDisabledOnStop() FAILED
    java.lang.AssertionError: 
    Expecting actual:
      2359L
    to be greater than:
      2400L
        at com.linecorp.armeria.client.endpoint.healthcheck.HealthCheckedEndpointGroupLongPollingTest.longPollingDisabledOnStop(HealthCheckedEndpointGroupLongPollingTest.java:143)
```
