### ISSUE TITLE
`Nothing` in Kotlin annotated rest method throws exception

### ISSUE THREAD

**Issue by tobias-** [line/armeria#3961]
Having a rest method returning `Nothing` throws an Exception with during init with Armeria 1.13.3. It used to work fine with Armeria 1.9.2. The problem can easily be circumvented by returning `Unit` or `String`.

The method is used to assert that our exception mappers works correctly.

```Kotlin
@PathPrefix("/test/")
class ArmeriaExceptionThrowTestRest {
    @Public
    @Get("/throw/armeria/{exceptionClass}")
    suspend fun armeriaThrow(@Param("exceptionClass") exceptionClass: String): Nothing {
        throw Class.forName(exceptionClass).getConstructor(String::class.java).newInstance("This was Armeria throwing") as Throwable
    }
}
```

The whole stack:
```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.linecorp.armeria.internal.server.annotation.KotlinUtil.kFunctionGenericReturnType(KotlinUtil.java:203)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.getActualReturnType(AnnotatedService.java:236)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.responseConverter(AnnotatedService.java:202)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.<init>(AnnotatedService.java:159)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedServiceFactory.lambda$create$4(AnnotatedServiceFactory.java:326)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedServiceFactory.create(AnnotatedServiceFactory.java:331)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedServiceFactory.lambda$find$0(AnnotatedServiceFactory.java:184)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedServiceFactory.find(AnnotatedServiceFactory.java:187)
	at com.linecorp.armeria.server.AnnotatedServiceBindingBuilder.buildServiceConfigBuilder(AnnotatedServiceBindingBuilder.java:286)
	at com.linecorp.armeria.server.VirtualHostBuilder.lambda$build$8(VirtualHostBuilder.java:1034)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.linecorp.armeria.server.VirtualHostBuilder.build(VirtualHostBuilder.java:1046)
	at com.linecorp.armeria.server.ServerBuilder.buildServerConfig(ServerBuilder.java:1711)
	at com.linecorp.armeria.server.ServerBuilder.build(ServerBuilder.java:1695)
        at Redacted(Redacted.kt:1)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at Redacted(Redacted.kt:1)
	at org.glassfish.jersey.test.RestTest$client$2.invoke(RestTest.kt:61)
	at org.glassfish.jersey.test.RestTest$client$2.invoke(RestTest.kt:49)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.glassfish.jersey.test.RestTest.getClient(RestTest.kt)
	at org.glassfish.jersey.test.RestTest.target(RestTest.kt:76)
	at org.glassfish.jersey.test.RestTest.target$default(RestTest.kt:76)
	at org.glassfish.jersey.test.RestTest.newResource(RestTest.kt:109)
        at Redacted(Redacted.kt:1)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.util.NoSuchElementException: Array is empty.
	at kotlin.collections.ArraysKt___ArraysKt.first(_Arrays.kt:1013)
	at kotlin.reflect.jvm.internal.KCallableImpl.extractContinuationArgument(KCallableImpl.kt:213)
	at kotlin.reflect.jvm.internal.KCallableImpl.access$extractContinuationArgument(KCallableImpl.kt:23)
	at kotlin.reflect.jvm.internal.KCallableImpl$_returnType$1$1.invoke(KCallableImpl.kt:77)
	at kotlin.reflect.jvm.internal.KCallableImpl$_returnType$1$1.invoke(KCallableImpl.kt:23)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
	at kotlin.reflect.jvm.internal.KTypeImpl.getJavaType(KTypeImpl.kt:48)
	at kotlin.reflect.jvm.ReflectJvmMapping.getJavaType(ReflectJvmMapping.kt:81)
	at com.linecorp.armeria.internal.common.kotlin.ArmeriaKotlinUtil.kFunctionGenericReturnType(ArmeriaKotlinUtil.kt:57)
	... 90 more`

**Comment by ikhoon** [comment]
@jupiny Are you interested in this?

**Comment by jupiny** [comment]
Let me take it!
