### ISSUE TITLE
Test failure: HealthCheckedEndpointGroupIntegrationTest

### ISSUE THREAD

**Issue by minwoox** [line/armeria#3974]
```
HealthCheckedEndpointGroupIntegrationTest > endpoints_containsUnhealthyServer(SessionProtocol) > com.linecorp.armeria.client.endpoint.healthcheck.HealthCheckedEndpointGroupIntegrationTest.endpoints_containsUnhealthyServer(SessionProtocol)[2] FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a com.linecorp.armeria.client.endpoint.healthcheck.HealthCheckedEndpointGroupIntegrationTest 
    Expecting map:
      {"armeria.client.endpoint.group.count#value{name=bar,state=healthy}"=1.0, "armeria.client.endpoint.group.count#value{name=bar,state=unhealthy}"=1.0, "armeria.client.endpoint.group.healthy#value{authority=127.0.0.1:1,ip=127.0.0.1,name=bar}"=0.0, "armeria.client.endpoint.group.healthy#value{authority=127.0.0.1:51442,ip=127.0.0.1,name=bar}"=0.0}
    to contain entries:
      ["armeria.client.endpoint.group.healthy#value{authority=127.0.0.1:51442,ip=127.0.0.1,name=bar}"=1.0]
    but the following map entries had different values:
      ["armeria.client.endpoint.group.healthy#value{authority=127.0.0.1:51442,ip=127.0.0.1,name=bar}"=0.0 (expected: 1.0)] within 10 seconds.
        at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:164)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:939)
        at app//org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:723)
        at app//com.linecorp.armeria.client.endpoint.healthcheck.HealthCheckedEndpointGroupIntegrationTest.endpoints_containsUnhealthyServer(HealthCheckedEndpointGroupIntegrationTest.java:190)

        Caused by:
        java.lang.AssertionError: 
        Expecting map:
          {"armeria.client.endpoint.group.count#value{name=bar,state=healthy}"=1.0, "armeria.client.endpoint.group.count#value{name=bar,state=unhealthy}"=1.0, "armeria.client.endpoint.group.healthy#value{authority=127.0.0.1:1,ip=127.0.0.1,name=bar}"=0.0, "armeria.client.endpoint.group.healthy#value{authority=127.0.0.1:51442,ip=127.0.0.1,name=bar}"=0.0}
        to contain entries:
          ["armeria.client.endpoint.group.healthy#value{authority=127.0.0.1:51442,ip=127.0.0.1,name=bar}"=1.0]
        but the following map entries had different values:
          ["armeria.client.endpoint.group.healthy#value{authority=127.0.0.1:51442,ip=127.0.0.1,name=bar}"=0.0 (expected: 1.0)]
            at com.linecorp.armeria.client.endpoint.healthcheck.HealthCheckedEndpointGroupIntegrationTest.lambda$endpoints_containsUnhealthyServer$4(HealthCheckedEndpointGroupIntegrationTest.java:198)
```

**Comment by ikhoon** [comment]
Let me take a look.

**Comment by minwoox** [comment]
I think this is the reason:
https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/client/endpoint/healthcheck/HealthCheckedEndpointGroupMetrics.java#L57-L58
```java        
listener.accept(endpointGroup.endpoints());
endpointGroup.addListener(listener);
```
`endpointGroup` can be set after `endpointGroup.endpoints()` is called and before `endpointGroup.addListener(listener);` is called.
