### ISSUE TITLE
HTTP JSON transcoding doesn't work with recursive types

### ISSUE THREAD

**Issue by wasifaleem** [line/armeria#3986]
Using `google.protobuf.Struct` in a proto file and enabling transcoding via `.enableHttpJsonTranscoding(true)` prevents the server from starting. I believe HttpJsonTranscodingService#buildFields is being called infinitely overflowing the call stack.

```
Caused by: java.lang.StackOverflowError: null
	at java.base/java.lang.StringBuilder.<init>(StringBuilder.java:102) ~[na:na]
	at com.linecorp.armeria.server.grpc.HttpJsonTranscodingService.lambda$buildFields$4(HttpJsonTranscodingService.java:291) ~[armeria-grpc-1.13.4.jar:na]
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204) ~[na:na]
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[na:na]
	at com.linecorp.armeria.server.grpc.HttpJsonTranscodingService.buildFields(HttpJsonTranscodingService.java:279) ~[armeria-grpc-1.13.4.jar:na]
	at com.linecorp.armeria.server.grpc.HttpJsonTranscodingService.lambda$buildFields$4(HttpJsonTranscodingService.java:323) ~[armeria-grpc-1.13.4.jar:na]
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204) ~[na:na]
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[na:na]
	at com.linecorp.armeria.server.grpc.HttpJsonTranscodingService.buildFields(HttpJsonTranscodingService.java:279) ~[armeria-grpc-1.13.4.jar:na]
	at com.linecorp.armeria.server.grpc.HttpJsonTranscodingService.lambda$buildFields$4(HttpJsonTranscodingService.java:323) ~[armeria-grpc-1.13.4.jar:na]
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204) ~[na:na]
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[na:na]
	at com.linecorp.armeria.server.grpc.HttpJsonTranscodingService.buildFields(HttpJsonTranscodingService.java:279) ~[armeria-grpc-1.13.4.jar:na]
	at com.linecorp.armeria.server.grpc.HttpJsonTranscodingService.lambda$buildFields$4(HttpJsonTranscodingService.java:323) ~[armeria-grpc-1.13.4.jar:na]
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204) ~[na:na]
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[na:na]
	at com.linecorp.armeria.server.grpc.HttpJsonTranscodingService.buildFields(HttpJsonTranscodingService.java:279) ~[armeria-grpc-1.13.4.jar:na]
	at com.linecorp.armeria.server.grpc.HttpJsonTranscodingService.lambda$buildFields$4(HttpJsonTranscodingService.java:323) ~[armeria-grpc-1.13.4.jar:na]
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204) ~[na:na]
....
```

```proto
syntax = "proto3";

import "google/api/annotations.proto";
import "google/protobuf/descriptor.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/struct.proto";

message Request {
  google.protobuf.Struct payload = 1;
}

message Response {
  google.protobuf.Struct payload = 2;
}

service SayHelloService {
  rpc SayHello (Request) returns (Response) {
    option (google.api.http) = {get:"/hello"};
  }
}
```

**Comment by hyangtack** [comment]
@wasifaleem Thanks for reporting. I thought I missed considering Struct and Any. Let me try to fix it.

**Comment by shubhamsinha** [comment]
@hyangtack thanks for addressing this bug. Is there an ETA for when the fix will be released? Thanks

**Comment by ikhoon** [comment]
>  Is there an ETA for when the fix will be released?

We are preparing for releasing a new version. After some ongoing reviews are done, it is expected to be released at the end of this week or early next week.
Please stay tuned. 🙇‍♂️
