### ISSUE TITLE
Armeria client does not work with HTTP1 servers when using upgrade.

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#4]
Currently it seems armeria client does not work when using HTTP upgrade and the server rejects upgrade. When forcing HTTP1 without upgrade using h1c://, it works fine.

Example failing integration test: https://github.com/anuraaga/armeria/pull/1

The stacktrace seems to indicate that the issue is the upgrade user event handler is triggered inline, meaning that the session listener is triggered right away and the actual RPC request is sent - however, this is before HttpClientUpgradeHandler has had a chance to remove itself from the pipeline, which happens after the user event is triggered. The RPC request goes through HttpClientUpgradeHandler once again, where it fails since the failed upgrade is still in progress (just a couple of lines of code left to run though...).

I tried moving the markConnectionFinished call in HttpConfigurator from userEventTriggered to channelRead or channelReadCompleted but couldn't figure out a resulting "connection reset by peer".

```
java.lang.IllegalStateException: Attempting to write HTTP request with upgrade in progress
	at io.netty.handler.codec.http.HttpClientUpgradeHandler.write(HttpClientUpgradeHandler.java:161)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeWriteNow(ChannelHandlerInvokerUtil.java:157)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeWrite(DefaultChannelHandlerInvoker.java:337)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:265)
	at io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:284)
	at com.linecorp.armeria.client.HttpClientIdleTimeoutHandler.write(HttpClientIdleTimeoutHandler.java:69)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeWriteNow(ChannelHandlerInvokerUtil.java:157)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeWrite(DefaultChannelHandlerInvoker.java:337)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:265)
	at com.linecorp.armeria.client.HttpSessionHandler.write(HttpSessionHandler.java:126)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeWriteNow(ChannelHandlerInvokerUtil.java:157)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeWrite(DefaultChannelHandlerInvoker.java:337)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1049)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:283)
	at com.linecorp.armeria.client.HttpRemoteInvoker.writeRequest(HttpRemoteInvoker.java:216)
	at com.linecorp.armeria.client.HttpRemoteInvoker.invoke0(HttpRemoteInvoker.java:166)
	at com.linecorp.armeria.client.HttpRemoteInvoker.lambda$invoke$53(HttpRemoteInvoker.java:135)
	at com.linecorp.armeria.client.HttpRemoteInvoker$$Lambda$17/1021436681.operationComplete(Unknown Source)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:567)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at com.linecorp.armeria.client.pool.DefaultKeyedChannelPool.notifyConnect(DefaultKeyedChannelPool.java:154)
	at com.linecorp.armeria.client.pool.DefaultKeyedChannelPool.lambda$acquireHealthyFromPoolOrNew$35(DefaultKeyedChannelPool.java:125)
	at com.linecorp.armeria.client.pool.DefaultKeyedChannelPool$$Lambda$21/100945895.operationComplete(Unknown Source)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:567)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at com.linecorp.armeria.client.HttpSessionChannelFactory$3.userEventTriggered(HttpSessionChannelFactory.java:137)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeUserEventTriggeredNow(ChannelHandlerInvokerUtil.java:75)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeUserEventTriggered(DefaultChannelHandlerInvoker.java:135)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:149)
	at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeUserEventTriggeredNow(ChannelHandlerInvokerUtil.java:75)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeUserEventTriggered(DefaultChannelHandlerInvoker.java:135)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:149)
	at com.linecorp.armeria.client.HttpSessionChannelFactory$DefaultSessionListener.sessionActivated(HttpSessionChannelFactory.java:152)
	at com.linecorp.armeria.client.HttpConfigurator.markHttpConnectionFinished(HttpConfigurator.java:170)
	at com.linecorp.armeria.client.HttpConfigurator.access$300(HttpConfigurator.java:67)
	at com.linecorp.armeria.client.HttpConfigurator$3.userEventTriggered(HttpConfigurator.java:195)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeUserEventTriggeredNow(ChannelHandlerInvokerUtil.java:75)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeUserEventTriggered(DefaultChannelHandlerInvoker.java:135)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:149)
	at io.netty.handler.codec.http.HttpClientUpgradeHandler.decode(HttpClientUpgradeHandler.java:213)
	at io.netty.handler.codec.http.HttpClientUpgradeHandler.decode(HttpClientUpgradeHandler.java:38)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:946)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
```

**Comment by trustin** [comment]
@inch772 You want to take a look, since it looks like a client-side issue?
