### ISSUE TITLE
`AnnotatedService` can't use wildcard type for parameters

### ISSUE THREAD

**Issue by ghkim3221** [line/armeria#4007]
When I use a wildcard type for parameter like as follows, `AnnotatedService` is failed to initialize due to `Unsupported or invalid parameter type: ?`:

```java
@Get("/wildcard")
public String wildcard(RequestContext ctx, @Param List<? extends Object> container) {
    return ctx.path();
}
```

It'd be ok for Java users since they may not use like the above. However, for Kotlin, it isn't when they use an interface as a generic type. IMHO, this is because Kotlin changes the type to the upper-bounded wildcard type. This is the reproducible code:
```kotlin
class AnnotatedService {
    @Get("/")
    fun foo(@Param("values") values: List<MyInterface>): String {
        return "Hello, $values!";
    }
}

interface MyInterface
```

Here's the stack trace:

```
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported or invalid parameter type: ? extends MyInterface
	at com.linecorp.armeria.internal.server.annotation.AnnotatedValueResolver$Builder.toRawType(AnnotatedValueResolver.java:1254)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedValueResolver$Builder.getElementType(AnnotatedValueResolver.java:1216)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedValueResolver$Builder.build(AnnotatedValueResolver.java:1090)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedValueResolver$Builder.access$800(AnnotatedValueResolver.java:924)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedValueResolver.ofQueryParam(AnnotatedValueResolver.java:524)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedValueResolver.of(AnnotatedValueResolver.java:420)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedValueResolver.of(AnnotatedValueResolver.java:378)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedValueResolver.lambda$of$3(AnnotatedValueResolver.java:319)
```

**Comment by ghkim3221** [comment]
I guess we need to handle `WildcardType` at this point:
https://github.com/line/armeria/blob/4ac50f017f0599e4b6e10675c575e8daedc0a07a/core/src/main/java/com/linecorp/armeria/internal/server/annotation/AnnotatedValueResolver.java#L1246-L1255

But I'm not sure we need to consider both upper bound and lower.

**Comment by ikhoon** [comment]
I don't think we need to handle `super` because that is used for an input type of a function. 
JFYI, https://stackoverflow.com/questions/2723397/what-is-pecs-producer-extends-consumer-super.
The type parameter for a collection type should be either a concrete type or upper bound with `extends`.

**Comment by minwoox** [comment]
I never expected that `List<? extends CustomizedType>` because we usually use collections of primitive types(which you don't need `? extends ...`) in annotated service. 😅 
Yeah, we need to definitely handle `WildcardType` especially. 😅

**Comment by ikhoon** [comment]
Ah, it is a `@Param`. I thought he wanted to use a custom `RequestConverterFunction`.
@ghkim3221 Is there a use case that you need to use an interface for `@Param`?
