### ISSUE TITLE
Handle ignorable localized IOException messages

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4027]
If a locale of JVM is not set to English, an `IOException` message could have a non-English message.

For example, the following conditions are set on Windows:
- `Socket.setSoLinger(true, 0)` is specified in a client
- Locale is set to `ko_KR` in a server
The server will warn the following message after a request was finished successfully on both sides.
```java
2022-01-13 15:10:05 [WARN ] [armeria-common-worker-nio-2-2] [Exceptions.java]logIfUnexpected(112) : [id: 0x0c91af74, L:/127.0.0.1:9500 - R:/127.0.0.1:56964][h1c] Unexpected exception:
java.io.IOException: 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
This non-English error message can not be regarded as an expected message by `IGNORABLE_SOCKET_ERROR_MESSAGE`.
https://github.com/line/armeria/blob/5b384fbe27e7e6f9225d6db91cbb684d09dfbb5e/core/src/main/java/com/linecorp/armeria/common/util/Exceptions.java#L60-L61

I think we need to allow users to add additional expected message patterns.
```java
class Exceptions{

    public static synchronized void addExpectedException(Class<? extends Throwable> exception, Pattern ignorablePattern) {
        ...
    }
```

**Comment by trustin** [comment]
How many language and OS combinations should we support? Should we just stick to English-only and leave it as a known issue? :thinking:

**Comment by ikhoon** [comment]
>  Should we just stick to English-only and leave it as a known issue?

I thought we stick to English and provide a customization point to let users append their own exception pattern to the default patterns.

**Comment by trustin** [comment]
We could probably allow customizing the pattern via `Flags`, which could be a regular expression or a predicate (by using the upcoming SPI feature).
