### ISSUE TITLE
Test failures when running locally, but not on CI

### ISSUE THREAD

**Issue by anuraaga** [line/armeria#403]
These tests always fail for me on a macbook pro when run from ```./gradlew :core:test```

```
ServerTest.testIdleTimeoutByContentSent: FAILURE

com.linecorp.armeria.server.ServerTest > testIdleTimeoutByContentSent FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 2500 milliseconds
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:204)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at com.linecorp.armeria.server.ServerTest.testIdleTimeoutByContentSent(ServerTest.java:204)
.....
com.linecorp.armeria.server.ServerTest > testIdleTimeoutByNoContentSent FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 2500 milliseconds
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:204)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at com.linecorp.armeria.server.ServerTest.testIdleTimeoutByNoContentSent(ServerTest.java:188)
ServerTest.testBuggyService: FAILURE

com.linecorp.armeria.server.ServerTest > testBuggyService FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 2500 milliseconds
        at java.net.InetAddress.getLocalHost(InetAddress.java:1486)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:204)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at com.linecorp.armeria.server.ServerTest.testBuggyService(ServerTest.java:231)
```

**Comment by trustin** [comment]
That's interesting. I never saw such failures so far from my laptop, although it's Linux. Let me review the offending test case.
