### ISSUE TITLE
Test failure: `ArmeriaSslConfigurationTest.http`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4096]
https://github.com/line/armeria/runs/5212528552?check_suite_focus=true#step:6:2655
```
ArmeriaSslConfigurationTest > http FAILED
    java.util.concurrent.CompletionException: com.linecorp.armeria.client.UnprocessedRequestException: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: unexpected message type: LastHttpContent$1, state: 0
        at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
        at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
        at com.linecorp.armeria.common.util.EventLoopCheckingFuture.join(EventLoopCheckingFuture.java:87)
        at com.linecorp.armeria.spring.ArmeriaSslConfigurationTest.verify(ArmeriaSslConfigurationTest.java:83)
        at com.linecorp.armeria.spring.ArmeriaSslConfigurationTest.http(ArmeriaSslConfigurationTest.java:100)

        Caused by:
        com.linecorp.armeria.client.UnprocessedRequestException: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: unexpected message type: LastHttpContent$1, state: 0
            at app//com.linecorp.armeria.client.UnprocessedRequestException.of(UnprocessedRequestException.java:45)
            at app//com.linecorp.armeria.client.HttpRequestSubscriber.operationComplete(HttpRequestSubscriber.java:133)
            at app//com.linecorp.armeria.client.HttpRequestSubscriber.operationComplete(HttpRequestSubscriber.java:53)
            at app//io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
            at app//io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
            at app//io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
            at app//io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)
            at app//io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
            at app//io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
            at app//com.linecorp.armeria.client.HttpRequestSubscriber.writeFirstHeader(HttpRequestSubscriber.java:205)
            at app//com.linecorp.armeria.client.HttpRequestSubscriber.onSubscribe(HttpRequestSubscriber.java:180)
            at app//com.linecorp.armeria.common.stream.FixedStreamMessage.subscribe0(FixedStreamMessage.java:131)
            at app//com.linecorp.armeria.common.stream.FixedStreamMessage.subscribe(FixedStreamMessage.java:119)
            at app//com.linecorp.armeria.common.stream.EmptyFixedStreamMessage.subscribe(EmptyFixedStreamMessage.java:29)
            at app//com.linecorp.armeria.common.HeaderOverridingHttpRequest.subscribe(HeaderOverridingHttpRequest.java:94)
            at app//com.linecorp.armeria.client.HttpSessionHandler.invoke(HttpSessionHandler.java:201)
            at app//com.linecorp.armeria.client.HttpClientDelegate.doExecute(HttpClientDelegate.java:239)
            at app//com.linecorp.armeria.client.HttpClientDelegate.lambda$acquireConnectionAndExecute0$3(HttpClientDelegate.java:177)
            at java.base@17.0.2/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
            at java.base@17.0.2/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
            at java.base@17.0.2/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
            at java.base@17.0.2/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
            at app//com.linecorp.armeria.client.HttpChannelPool$ChannelAcquisitionFuture.complete(HttpChannelPool.java:830)
            at app//com.linecorp.armeria.client.HttpChannelPool.notifyConnect(HttpChannelPool.java:509)
            at app//com.linecorp.armeria.client.HttpChannelPool.lambda$connect$4(HttpChannelPool.java:378)
            at app//io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
            at app//io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
            at app//io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
            at app//io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
            at app//io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
            at app//io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
            at app//com.linecorp.armeria.client.HttpSessionHandler.tryCompleteSessionPromise(HttpSessionHandler.java:392)
            at app//com.linecorp.armeria.client.HttpSessionHandler.userEventTriggered(HttpSessionHandler.java:358)
```

**Comment by kojilin** [comment]
Because state is 0, looks like error happened at https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/internal/common/Http1ObjectEncoder.java#L113 already. Not sure the root cause but do you think if it's good idea to provide `allOf(ChannelPromise resultPromise, List<ChannelFuture> futures) ` to collect all the error(e.g. using addSuppressed)?

**Comment by ikhoon** [comment]
> Not sure the root cause but do you think if it's good idea to provide allOf(ChannelPromise resultPromise, List<ChannelFuture> futures) to collect all the error(e.g. using addSuppressed)?

Could we sample the exception using `Flags.verboseExceptionSampler()` to avoid additional overhead?
