### ISSUE TITLE
Test failure: EurekaEndpointGroupFailoverTest

### ISSUE THREAD

**Issue by minwoox** [line/armeria#4217]
```
EurekaEndpointGroupFailoverTest > shouldRefreshEndpointsAfterFailure() FAILED
    java.util.concurrent.CompletionException: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
        at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
        at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
        at com.linecorp.armeria.common.util.EventLoopCheckingFuture.join(EventLoopCheckingFuture.java:87)
        at com.linecorp.armeria.client.eureka.EurekaEndpointGroupFailoverTest.lambda$shouldRefreshEndpointsAfterFailure$1(EurekaEndpointGroupFailoverTest.java:72)

        Caused by:
        io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
```

**Comment by minwoox** [comment]
Let me close this issue because https://github.com/line/armeria/pull/4212 handles this.
