### ISSUE TITLE
Exception flooding in ZooKeeperRegistrationTest

### ISSUE THREAD

**Issue by trustin** [line/armeria#431]
https://travis-ci.org/line/armeria/builds/206876098#L1240

```
05:14:02.621 [Executors-Default-1-SendThread(127.0.0.1:45011)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x15a8d7038580016 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
...
```

Probably some race condition? Could you take a look, @jonefeewang ?

**Comment by jonefeewang** [comment]
ok, will check it
