### ISSUE TITLE
Http1ObjectEncoder.combine may fail if both futures fail for the same reason

### ISSUE THREAD

**Issue by mauhiz** [line/armeria#4749]
With Armeria 1.22.1, on an unstable connection with many timeouts, I am observing the following issue once in a while

```
java.lang.IllegalArgumentException: Self-suppression not permitted
	at java.base/java.lang.Throwable.addSuppressed(Throwable.java:1064)
	at com.linecorp.armeria.internal.common.Http1ObjectEncoder$1.operationComplete(Http1ObjectEncoder.java:156)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
```

Root cause, which is likely not relevant to this issue, is :
```
Caused by: io.netty.handler.ssl.SslClosedEngineException: SSLEngine closed already
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:861)
	... 53 common frames omitted
```

I suppose that `addSuppressed` should be skipped if `firstCause == secondCause`

**Comment by jrhee17** [comment]
> Caused by: io.netty.handler.ssl.SslClosedEngineException: SSLEngine closed already
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:861)
	... 53 common frames omitted

I'm curious how often this occurs and which version this warning log started to appear 🤔 
May I ask what the previous version was before upgrading?

**Comment by mauhiz** [comment]
It didn't appear on an upgrade, but when using a particularly bad HTTPS endpoint. I couldn't reproduce.
