### ISSUE TITLE
Test failure: `example.armeria.server.sse.MainTest.testServerSentEventsShort()`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4777]
```
java.lang.AssertionError: expectation "expectNext(id:3
data:3
retry:5000)" failed (expected value: id:3
data:3
retry:5000; actual value: id:4
data:3
retry:5000)
	at reactor.test.MessageFormatter.assertionError(MessageFormatter.java:115)
	at reactor.test.MessageFormatter.failPrefix(MessageFormatter.java:104)
	at reactor.test.MessageFormatter.fail(MessageFormatter.java:73)
	at reactor.test.MessageFormatter.failOptional(MessageFormatter.java:88)
	at reactor.test.DefaultStepVerifierBuilder.lambda$addExpectedValue$10(DefaultStepVerifierBuilder.java:512)
	at reactor.test.DefaultStepVerifierBuilder$SignalEvent.test(DefaultStepVerifierBuilder.java:2289)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.onSignal(DefaultStepVerifierBuilder.java:1529)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.onExpectation(DefaultStepVerifierBuilder.java:1477)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.onNext(DefaultStepVerifierBuilder.java:1146)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberWithElements(DefaultStreamMessage.java:406)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:384)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:331)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:317)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.addObject(DefaultStreamMessage.java:245)
	at com.linecorp.armeria.common.stream.AbstractStreamWriter.tryWrite(AbstractStreamWriter.java:64)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.tryWrite(DefaultStreamMessage.java:70)
	at com.linecorp.armeria.internal.common.stream.DecodedStreamMessage.add(DecodedStreamMessage.java:111)
	at example.armeria.server.sse.MainTest$SimpleServerSentMessageDecoder.process(MainTest.java:110)
	at com.linecorp.armeria.internal.common.stream.DecodedStreamMessage$DecodingSubscriber.onNext(DecodedStreamMessage.java:231)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberWithElements(DefaultStreamMessage.java:406)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:384)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1589)

```

**Comment by seonwoo960000** [comment]
Oh~ looks interesting. May I take this issue ?

**Comment by ikhoon** [comment]
Sure. :-)

**Comment by seonwoo960000** [comment]
Hmm, it works on my machine. Let me know how to reproduce the problem 🙇

**Comment by ikhoon** [comment]
It is a flaky test that occasionally fails. There is no standard way to reproduce flaky tests.
I usually modify the test configuration using IntelliJ to repeat the tests until failure. But it doesn't make sure the tests are failed.
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/1866157/228405873-fe36d69e-944c-4351-9a20-f6e4ffc0bece.png">

**Comment by seonwoo960000** [comment]
Still not able to produce the same error, hmm... I think it will take some time 😢

**Comment by ikhoon** [comment]
To be honest, it is not a trivial issue to resolve.
I guess `onBackpressureDrop()` might perform in the failed situation.
https://github.com/line/armeria/blob/5ed3cacc8e5a5ec14e5b850e4c23b260b0468334/examples/server-sent-events/src/main/java/example/armeria/server/sse/Main.java#L70

`Flux.interval()` emits numbers with a fixed interval. If the downstream is busy and does not consume the data within the interval, the number (3) is skipped by `onBackpressureDrop()` and the next number will be injected as `id` of `map()`.
https://github.com/line/armeria/blob/5ed3cacc8e5a5ec14e5b850e4c23b260b0468334/examples/server-sent-events/src/main/java/example/armeria/server/sse/Main.java#L73

It may be possible to reproduce the situation by 1) adding a custom channel handler to control the traffic and 2) increase `eventCount`.
1) https://github.com/line/armeria/blob/f427f0e655d7595bec46a849c746df4848569e7f/core/src/test/java/com/linecorp/armeria/client/WriteTimeoutTest.java#L43 
https://github.com/line/armeria/blob/8af33b00e11e85862b3e2634c162e86f0b748507/examples/server-sent-events/src/test/java/example/armeria/server/sse/MainTest.java#L41

I believe we can fix the flaky test by increasing the interval.

**Comment by seonwoo960000** [comment]
Wow .. that's a great insight. I'll test this and check what might be the best `interval` for this case
