### ISSUE TITLE
Test failure: `com.linecorp.armeria.spring.actuate.ArmeriaSpringActuatorAutoConfigurationSslTest.usingSsl()`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4807]
```
java.lang.IllegalStateException: Failed to load ApplicationContext
at ....
at com.linecorp.armeria.spring.ArmeriaServerGracefulShutdownLifecycle.lambda$start$0(ArmeriaServerGracefulShutdownLifecycle.java:49)

at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)

... 22 more

Caused by: java.net.BindException: Address already in use: bind

at java.base/sun.nio.ch.Net.bind0(Native Method)

at java.base/sun.nio.ch.Net.bind(Net.java:555)

at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:344)

at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:301)

at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:141)

at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)

at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)

at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:600)

at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:579)

at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)

at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)

at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)

at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)

at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)

at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)

at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)

at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
```

**Comment by mitrofmep** [comment]
Can you assign me?

**Comment by ikhoon** [comment]
Of course. It's all yours.

**Comment by ikhoon** [comment]
It looks like the flaky test is a regression that I made while adding Spring Boot 3 module.
`RetryableArmeriaServerGracefulShutdownLifecycle` was added to automatically restart if a server fails to start #4453
`RetryableArmeriaServerGracefulShutdownLifecycle` is a bean that is automatically loaded by 
https://github.com/line/armeria/blob/8af33b00e11e85862b3e2634c162e86f0b748507/spring/boot3-autoconfigure/src/test/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports#L1-L1
The file was in Spring Boot 2 autoconfigure and moved to Spring Boot 3 modules. I realized that `boot2-actuator-autoconfigure` does not contain or refer to the `AutoConfiguration.imports` for `RetryableArmeriaServerGracefulShutdownLifecycle`.
https://github.com/line/armeria/blob/57295d3ed82748dc6949f825910705a6c17d098f/spring/boot2-actuator-autoconfigure/build.gradle#L30
The code should be changed to:
```
-tasks.processTestResources.from "${boot3ActuatorProjectDir}/src/test/resources"
+tasks.processTestResources.from "${boot3ActuatorProjectDir}/src/test/resources", "${boot3ActuatorProjectDir}/gen-src/test/resources"
```

Could you check if other modules correctly copy or refer to AutoConfiguration.imports for testing?
