### ISSUE TITLE
Test failure: `PortBasedVirtualHostTest`

### ISSUE THREAD

**Issue by trustin** [line/armeria#4828]
From: https://github.com/line/armeria/actions/runs/4640061056/jobs/8211591879
```
PortBasedVirtualHostTest > testNormalPort() FAILED
    org.opentest4j.AssertionFailedError: 
    expected: 404 Not Found
     but was: 200 OK
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at com.linecorp.armeria.server.PortBasedVirtualHostTest.testNormalPort(PortBasedVirtualHostTest.java:82)

PortBasedVirtualHostTest > testVirtualHostNameWithoutPort() FAILED
    org.opentest4j.AssertionFailedError: 
    expected: 404 Not Found
     but was: 200 OK
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at com.linecorp.armeria.server.PortBasedVirtualHostTest.testVirtualHostNameWithoutPort(PortBasedVirtualHostTest.java:145)
```

**Comment by thachlp** [comment]
I tried to reproduce the issue by switching to Java 8, but I can not run the test by `:core:compileJava` fail:
```
java.lang.UnsupportedClassVersionError: com/google/errorprone/ErrorProneJavacPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```
Any suggestion to bypass this? 🙇

**Comment by ikhoon** [comment]
We complie our project with Java 19 and test with Java 8. You can use the following command to use Java 8 to test. 
```
./gradlew build -PbuildJdkVersion=19 -PtestJavaVersion=8
```
