### ISSUE TITLE
`FieldMetaData.getStructMetaDataMap()` returns null

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#4905]
[`FieldMetaData.getStructMetaDataMap()`](https://github.com/apache/thrift/blob/285e39c2422935d80442c0952d88315354f2ac64/lib/java/src/main/java/org/apache/thrift/meta_data/FieldMetaData.java#L87-L103) returned null while `ThriftFunction` is initiated. 
https://github.com/line/armeria/blob/274929f5af1649b7c743a2deccbd584c1f4a67a0/thrift/thrift0.13/src/main/java/com/linecorp/armeria/internal/common/thrift/ThriftFunction.java#L100-L102

```java
java.lang.IllegalArgumentException: failed to retrieve function metadata: x.y.z.MyService$Iface.getXXX()
	at com.linecorp.armeria.internal.common.thrift.ThriftServiceMetadata.registerFunction(ThriftServiceMetadata.java:239)
	at com.linecorp.armeria.internal.common.thrift.ThriftServiceMetadata.lambda$init$2(ThriftServiceMetadata.java:117)
	at java.base/java.util.HashMap.forEach(HashMap.java:1337)
	at java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1505)
	at com.linecorp.armeria.internal.common.thrift.ThriftServiceMetadata.init(ThriftServiceMetadata.java:116)
	at com.linecorp.armeria.internal.common.thrift.ThriftServiceMetadata.<init>(ThriftServiceMetadata.java:85)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.linecorp.armeria.internal.client.thrift.THttpClientDelegate.metadata(THttpClientDelegate.java:216)
	at com.linecorp.armeria.internal.client.thrift.THttpClientDelegate.execute(THttpClientDelegate.java:122)
	... omitted
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException: null
	at com.linecorp.armeria.internal.common.thrift.ThriftFunction.<init>(ThriftFunction.java:104)
	at com.linecorp.armeria.internal.common.thrift.ThriftFunction.<init>(ThriftFunction.java:66)
	at com.linecorp.armeria.internal.common.thrift.ThriftServiceMetadata.registerFunction(ThriftServiceMetadata.java:229)
	... 33 common frames omitted
```

`FieldMetaData.getStructMetaDataMap()` should return non-null metadata, but a null value is somehow returned.

**Comment by ikhoon** [comment]
This problem occurred in libthrift 0.9.1 and has already been patched. This was resolved by upgrading to 0.9.3-1.
