### ISSUE TITLE
Error using abstract namespace socket path with Unix Domain Socket setup.

### ISSUE THREAD

**Issue by chris-ryan-square** [line/armeria#5014]
I'm trying to get the Unix Domain Socket Support support from 1.24.0 working.  I'm having trouble specifying a socket that's in the abstract namespace (e.g. "@foo.sock").  My previous uds proxy server used null in the socket path ("\u0000foo.sock") and this worked fine.  Now if I do it, I get something like:

```
java.nio.file.InvalidPathException: Nul character not allowed: \u0000foo.sock
 at java.base/sun.nio.fs.UnixPath.checkNotNul(UnixPath.java:90)
 at java.base/sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:80) 
 at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:68)
 at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
 at java.base/java.nio.file.Path.of(Path.java:147)
 at java.base/java.nio.file.Paths.get(Paths.java:69)
 at com.linecorp.armeria.common.util.DomainSocketAddress.of(DomainSocketAddress.java:59)

```

The call I used to generate the above:

`serverBuilder.http(DomainSocketAddress.of(io.netty.channel.unix.DomainSocketAddress(socketPath) )`

**Comment by minwoox** [comment]
Discord link:
https://discord.com/channels/1087271586832318494/1087272728177942629/1125302155725787177
