### ISSUE TITLE
Test failure: `com.linecorp.armeria.server.FallbackServiceTest.[1] protocol=H1C`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#5044]
```java
java.util.concurrent.CompletionException: com.linecorp.armeria.common.ClosedSessionException
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
	at com.linecorp.armeria.server.FallbackServiceTest.maxContentLengthWithLateResponse(FallbackServiceTest.java:168)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131
```

**Comment by minwoox** [comment]
Let's see if it still happens after merging #5227
