### ISSUE TITLE
Upgrading from version 1.23.1 to 1.24.3 causing NoSuchMethodError 

### ISSUE THREAD

**Issue by rpotnuru** [line/armeria#5094]
Hello, 

We tried upgrading the armeria version in our JAVA app from 1.23.1 to 1.24.3  and started facing below error, is there a solution available for this issue?

Closing: [id: 0xca73bc36, L:/192.168.12.87:8443 - R:/192.168.12.87:41492]
java.lang.NoSuchMethodError: 'void io.netty.handler.ssl.SniHandler.<init>(io.netty.util.Mapping, int, long)'
    at com.linecorp.armeria.server.HttpServerPipelineConfigurator.configureHttps(HttpServerPipelineConfigurator.java:235) ~[armeria-1.24.3.jar!/:?]
    at com.linecorp.armeria.server.HttpServerPipelineConfigurator.configurePipeline(HttpServerPipelineConfigurator.java:172) ~[armeria-1.24.3.jar!/:?]
    at com.linecorp.armeria.server.HttpServerPipelineConfigurator.initChannel(HttpServerPipelineConfigurator.java:160) ~[armeria-1.24.3.jar!/:?]
    at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) ~[netty-transport-4.1.86.Final.jar!/:4.1.86.Final]
    at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) ~[netty-transport-4.1.86.Final.jar!/:4.1.86.Final]
    at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114) ~[netty-transport-4.1.86.Final.jar!/:4.1.86.Final]
    at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) ~[netty-transport-4.1.86.Final.jar!/:4.1.86.Final]

**Comment by ikhoon** [comment]
`SniHandler.(io.netty.util.Mapping, int, long)` is newly added at Netty 4.1.94.Final
https://github.com/netty/netty/commit/535da17e45201ae4278c0479e6162bb4127d4c32#diff-fc17884fef04eaabfaec52238a49d5f06a8471a8f44f0f72e07a22f59e4c94c2R62
I guess there is a Netty version inconsistency in your dependency.

**Comment by jrhee17** [comment]
Hi, I believe this is because we are using the new API added by netty. (https://github.com/netty/netty/security/advisories/GHSA-6mjq-h674-j845)
I would recommend using netty `version >=4.1.94` with the newest `armeria` version.

The netty version used to test/release armeria can be found here:
https://github.com/line/armeria/blob/195e1670218caf1ec00fa0ab631486d6224b72c2/dependencies.toml#L87

**Comment by rpotnuru** [comment]
Thank you for a quick response guys, appreciate it. I will give it a try.
