### ISSUE TITLE
NoClassDefFoundError in DropwizardRequestMetrics

### ISSUE THREAD

**Issue by mauhiz** [line/armeria#510]
ProGuard is a prime suspect.

Version: `armeria-0.35.1`
`metrics-core-3.1.2` is also on the classpath

Relevant stack trace:

```
java.lang.NoClassDefFoundError: java/util/concurrent/locks/ReentrantReadWriteLock$WriteLock
	at com.codahale.metrics.ExponentiallyDecayingReservoir.lockForRescale(ExponentiallyDecayingReservoir.java:189)
	at com.codahale.metrics.ExponentiallyDecayingReservoir.rescale(ExponentiallyDecayingReservoir.java:163)
	at com.codahale.metrics.ExponentiallyDecayingReservoir.rescaleIfNeeded(ExponentiallyDecayingReservoir.java:121)
	at com.codahale.metrics.ExponentiallyDecayingReservoir.update(ExponentiallyDecayingReservoir.java:93)
	at com.codahale.metrics.ExponentiallyDecayingReservoir.update(ExponentiallyDecayingReservoir.java:83)
	at com.codahale.metrics.Histogram.update(Histogram.java:39)
	at com.codahale.metrics.Timer.update(Timer.java:149)
	at com.codahale.metrics.Timer.update(Timer.java:86)
	at com.linecorp.armeria.internal.logging.DropwizardRequestMetrics.updateTime(DropwizardRequestMetrics.java:52)
	at com.linecorp.armeria.internal.logging.DropwizardMetricCollector.onResponse(DropwizardMetricCollector.java:71)
	at com.linecorp.armeria.common.logging.RequestLogListenerInvoker.invokeOnRequestLog(RequestLogListenerInvoker.java:39)
```

**Comment by trustin** [comment]
I'm not sure if ProGuard is related with this yet. Shall we revisit this once we upgrade to the latest Armeria?

**Comment by imasahiro** [comment]
I updated armeria version from 0.35.1 to 0.43.0 and NoClassDefFoundError was disappeared.
