### ISSUE TITLE
Compatibility issue between ZooKeeper version 3.4.6 and armeria-zookeeper3 

### ISSUE THREAD

**Issue by wang-qijia** [line/armeria#5189]
My current environment is using ZooKeeper version 3.4.6, and I have found that the version required by armeria-zookeeper3 is too high and incompatible with my current environment. The reason is that Curator only supports ZooKeeper 3.5.x. How can I resolve this issue?

**Comment by ikhoon** [comment]
Did you try to override the versions of ZooKeeper to 3.4.6 and the corresponding Curator version forcibly? armeria-zookeeper3 uses a limited set of ZooKeeper and Curator APIs which may be compatible with the old versions.

**Comment by wang-qijia** [comment]
compile("com.linecorp.armeria:armeria-zookeeper3") {
        exclude group: 'org.apache.zookeeper', module: 'zookeeper'
        exclude group: 'org.apache.curator', module: 'curator-framework'
        exclude group: 'org.apache.curator', module: 'curator-x-discovery'
        exclude group: 'org.apache.curator', module: 'curator-recipes'
    }
    compile('org.apache.curator:curator-recipes:4.2.0') {
        exclude group: 'org.apache.zookeeper', module: 'zookeeper'
    }
    compile 'org.apache.zookeeper:zookeeper:3.4.6'
    compile 'org.apache.curator:curator-x-discovery:4.2.0'
```
Caused by: java.lang.NoSuchMethodError: org.apache.curator.framework.recipes.cache.PathChildrenCache.getListenable()Lorg/apache/curator/framework/listen/Listenable;
	at com.linecorp.armeria.client.zookeeper.ZooKeeperEndpointGroup.pathChildrenCache(ZooKeeperEndpointGroup.java:138) ~[armeria-zookeeper3-1.25.2.jar:?]
	at com.linecorp.armeria.client.zookeeper.ZooKeeperEndpointGroup.<init>(ZooKeeperEndpointGroup.java:129) ~[armeria-zookeeper3-1.25.2.jar:?]
	at com.linecorp.armeria.client.zookeeper.ZooKeeperEndpointGroupBuilder.build(ZooKeeperEndpointGroupBuilder.java:71) ~[armeria-zookeeper3-1.25.2.jar:?]
```

**Comment by ikhoon** [comment]
Thanks for checking the difference. We may need to add an integration test to verify if armeria-zookeeper3 is compatible with ZooKeeper 3.4.6.

If there is an alternative API that we can use directly or via reflection, we can add the workaround for that. Are you interested in sending a PR?

**Comment by minwoox** [comment]
> The reason is that Curator only supports ZooKeeper 3.5.x. How can I resolve this issue?

Hi! Did you have a chance to upgrade the Curator to 5.5.0 by the way?
https://mvnrepository.com/artifact/org.apache.curator/curator-client/5.5.0
It uses ZooKeeper 3.7.1 that `armeria-zookeeper3` uses.

**Comment by wang-qijia** [comment]
> > 原因是Curator只支持ZooKeeper 3.5.x。我该如何解决这个问题？
> 
> 你好！顺便问一下，您有机会将 Curator 升级到 5.5.0 吗？ https://mvnrepository.com/artifact/org.apache.curator/curator-client/5.5.0 它使用使用的ZooKeeper 3.7.1 `armeria-zookeeper3`。

I am unable to upgrade at the moment as many of the services I depend on are using version 3.4.x, and upgrading carries significant risks for me.

**Comment by ikhoon** [comment]
`PathChildrenCache.getListenable()` in Curator 4.2 returns `ListenerContainer` whose super interface is `Listenable`. https://github.com/apache/curator/blob/dc6e78513aa076545552b2661940f6ed4bcc5e75/curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/PathChildrenCache.java#L397
A small reflection would be acceptable to invoke the method while avoiding incompatibility. @wang-qijia Are you interested in sending a PR?
