### ISSUE TITLE
Test failure: `com.linecorp.armeria.client.ClientCertificateMetricsTest.shouldMeasureClientCertValidityInClientFactory()`

### ISSUE THREAD

**Issue by minwoox** [line/armeria#5247]
```
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a com.linecorp.armeria.client.ClientCertificateMetricsTest null within 10 seconds.
	at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
	at app//org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:769)
	at app//com.linecorp.armeria.client.ClientCertificateMetricsTest.shouldMeasureClientCertValidityInClientFactory(ClientCertificateMetricsTest.java:51)
	at java.base@19.0.2/java.lang.reflect.Method.invoke(Method.java:578)
	at java.base@19.0.2/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base@19.0.2/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:101)
	at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:81)
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:103)
	... 8 more

```

**Comment by ikhoon** [comment]
Oops... 😅 Let me take a closer look soon.
