### ISSUE TITLE
Hope to get help on `NativeIoException: recvAddress(..)`

### ISSUE THREAD

**Issue by Lincong** [line/armeria#5299]
Hi, we are using gRPC client in Armeria 1.16.3 + Netty 4.1.86.Final. We observed below exception at runtime. It is transient and we have not managed to reproduce it. The exception is similar to the one reported [here](https://github.com/netty/netty/issues/8801) (to Netty community). My questions are:

1. Is this exception has the exactly same root cause as described [here](https://github.com/netty/netty/issues/8801#issuecomment-459275165) in the Netty issue? If so, I think it makes sense to bubble this exception all the way up to the application-layer caller because there is nothing Netty layer or Armeria layer can do about it. Furthermore, the application-layer logic can only retry on this exception if the endpoint is idempotent, otherwise, there is nothing the application-layer logic can do either. Please correct my understanding if it is wrong or inaccurate.

2. We enabled TCP keep-alive by doing the blow, does that make this exception more or less likely to occur? or does it matter at all?
```java
    clientFactoryBuilder
      .channelOption(ChannelOption.SO_KEEPALIVE, java.lang.Boolean.valueOf(true))
```

3. Is there any specific settings or configs we can leverage in Armeria gRPC client to make this exception less likely to occur?

```
internalStackTrace: grpc_shaded.io.grpc.StatusRuntimeException: UNKNOWN
	at grpc_shaded.io.grpc.Status.asRuntimeException(Status.java:535)
	at grpc_shaded.io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
	at grpc_shaded.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at grpc_shaded.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at grpc_shaded.com.linecorp.armeria.internal.client.grpc.ArmeriaClientCall.close(ArmeriaClientCall.java:506)
	at grpc_shaded.com.linecorp.armeria.internal.client.grpc.ArmeriaClientCall.transportReportStatus(ArmeriaClientCall.java:445)
	at grpc_shaded.com.linecorp.armeria.internal.common.grpc.HttpStreamDeframer.processOnError(HttpStreamDeframer.java:145)
	at grpc_shaded.com.linecorp.armeria.internal.common.stream.DecodedStreamMessage$DecodingSubscriber.onError(DecodedStreamMessage.java:274)
	at grpc_shaded.com.linecorp.armeria.common.stream.FuseableStreamMessage$FuseableSubscriber.onError(FuseableStreamMessage.java:302)
	at grpc_shaded.com.linecorp.armeria.common.stream.DeferredStreamMessage$ForwardingSubscriber.onError(DeferredStreamMessage.java:398)
	at grpc_shaded.com.linecorp.armeria.common.stream.FuseableStreamMessage$FuseableSubscriber.onError(FuseableStreamMessage.java:304)
	at grpc_shaded.com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:269)
	at grpc_shaded.com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:300)
	at grpc_shaded.com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:292)
	at grpc_shaded.com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:429)
	at grpc_shaded.com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:372)
	at grpc_shaded.com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:328)
	at grpc_shaded.com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:314)
	at grpc_shaded.com.linecorp.armeria.common.stream.DefaultStreamMessage.tryClose(DefaultStreamMessage.java:458)
	at grpc_shaded.com.linecorp.armeria.common.stream.DefaultStreamMessage.close(DefaultStreamMessage.java:447)
	at grpc_shaded.com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.closeAction(HttpResponseDecoder.java:331)
	at grpc_shaded.com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.cancelTimeoutOrLog(HttpResponseDecoder.java:371)
	at grpc_shaded.com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:319)
	at grpc_shaded.com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.close(HttpResponseDecoder.java:314)
	at grpc_shaded.com.linecorp.armeria.client.HttpResponseDecoder.failUnfinishedResponses(HttpResponseDecoder.java:140)
	at grpc_shaded.com.linecorp.armeria.client.HttpSessionHandler.channelInactive(HttpSessionHandler.java:417)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
	at grpc_shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:411)
	at grpc_shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376)
	at grpc_shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.channelInactive(Http2ConnectionHandler.java:430)
	at grpc_shaded.com.linecorp.armeria.client.Http2ClientConnectionHandler.channelInactive(Http2ClientConnectionHandler.java:128)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
	at grpc_shaded.io.netty.handler.logging.LoggingHandler.channelInactive(LoggingHandler.java:206)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
	at grpc_shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:411)
	at grpc_shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376)
	at grpc_shaded.io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1168)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
	at grpc_shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at grpc_shaded.io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at grpc_shaded.io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813)
	at grpc_shaded.io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at grpc_shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at grpc_shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at grpc_shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
	at grpc_shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at grpc_shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at grpc_shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: grpc_shaded.com.linecorp.armeria.common.ClosedSessionException
	at grpc_shaded.com.linecorp.armeria.client.HttpSessionHandler.exceptionCaught(HttpSessionHandler.java:441)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
	at grpc_shaded.io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
	at grpc_shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.exceptionCaught(Http2ConnectionHandler.java:582)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
	at grpc_shaded.io.netty.handler.logging.LoggingHandler.exceptionCaught(LoggingHandler.java:214)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
	at grpc_shaded.io.netty.handler.ssl.SslHandler.exceptionCaught(SslHandler.java:1198)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
	at grpc_shaded.io.netty.handler.flush.FlushConsolidationHandler.exceptionCaught(FlushConsolidationHandler.java:159)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
	at grpc_shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at grpc_shaded.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at grpc_shaded.io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907)
	at grpc_shaded.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.handleReadException(AbstractEpollStreamChannel.java:728)
	at grpc_shaded.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:826)
	at grpc_shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
	at grpc_shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
	... 4 more
Caused by: grpc_shaded.io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection timed out
```

**Comment by Lincong** [comment]
Discord discussion thread is [here](https://discord.com/channels/1087271586832318494/1087272728177942629/1173852653931986974)

**Comment by jrhee17** [comment]
> Does this exception have the exactly same root cause as described https://github.com/netty/netty/issues/8801#issuecomment-459275165 in the Netty issue? If so, I think it makes sense to bubble this exception all the way up to the application-layer because there is nothing Netty layer or Armeria layer can do about it. Furthermore, the application-layer logic can only retry on this exception if the endpoint is idempotent, otherwise, there is nothing the application-layer logic can do neither. Please correct my understanding if it is wrong or inaccurate.

If a request is retriable regardless of idempotency, then an `UnprocessedRequestException` will be thrown. Otherwise, a `ClosedSessionException` will be thrown which means an application can retry safely only for idempotent endpoints (this depends on the business requirements).

The type of exception depends on the timing. For instance, if the exception is thrown before an actual request is sent, then even if `NativeIoException` is thrown an `UnprocessedRequestException` will be thrown.

> We enabled TCP keep-alive by doing the blow, does that make this exception more or less likely to occur? or does it matter at all?

From my understanding, the option just lets the user know at an earlier timing that the TCP connection is unhealthy. I don't think the option will impact the frequency of the exception occurring.

> Is there any specific settings or configs we can leverage in Armeria gRPC client to make this exception less likely to occur?

How often does the error occur?  I think it is difficult to say unless we know what the cause is.

1. For instance, I think one cause could be a server shutting down uncleanly without closing tcp connections properly. I'm not sure if tuning parameters could help with for this kind of problem.
2. On the other hand, the cause could be that somewhere along the network path the connection is shut down uncleanly. (perhaps there is a proxy that closes inactive connections after a certain period) In this case, sending keepalive messages might help.

**Comment by Lincong** [comment]
> From my understanding, the option just lets the user know at an earlier timing that the TCP connection is unhealthy. I don't think the option will impact the frequency of the exception occurring.

Thanks for sharing your understanding. The reason why I expect TCP keep-alive to reduce the frequency of such exception is because in some cases, TCP keep-alive could detect and clean up dead TCP connections before socket operations or system calls issued by Netty get tripped over the dead connection. Let me know if this understanding is correct.

> How often does the error occur?

We observed this exception in our load test which has a setup of a client-side service sending gRPC requests to server-side service with no proxy in the middle.

> I think it is difficult to say unless we know what the cause is.

Yes, I agree.

> 1. For instance, I think one cause could be a server shutting down uncleanly without closing tcp connections properly. I'm not sure if tuning parameters could help with for this kind of problem.
> 2. On the other hand, the cause could be that somewhere along the network path the connection is shut down uncleanly. (perhaps there is a proxy that closes inactive connections after a certain period) In this case, sending keepalive messages might help.

Yes, I agree that some kind of "connection shut down uncleanly" could be the root cause. I have been trying to simulate unclean connection close on the server side by trying the following:
1. kill -9 <PID of my server-side Java application>
2. Force my server-side Java application to go OOM

However, I have not been able to repro it either because above approaches do not result in unclean connection close (because all TCP connections opened by the Java process could be gracefully closed by the OS, but I am not sure can I can verify it...) or timing is not right.

**Comment by jrhee17** [comment]
> The reason why I expect TCP keep-alive to reduce the frequency of such exception is because in some cases, TCP keep-alive could detect and clean up dead TCP connections before socket operations or system calls issued by Netty get tripped over the dead connection. Let me know if this understanding is correct.

Ah I see. I agree that detecting faster could reduce the number of requests that are affected by a dead connection.

> no proxy in the middle.
> However, I have not been able to repro it either because above approaches do not result in unclean connection close (because all TCP connections opened by the Java process could be gracefully closed by the OS, but I am not sure can I can verify it...) or timing is not right.

I see, I haven't actually tried it but perhaps modifying ip table rules could better simulate ungraceful close.

We also talked about this, but I don't think we had a better idea on ways to reduce this kind of exception. Hopefully if you can get a reproducer running, it can help us understand and debug the underlying issue

**Comment by Lincong** [comment]
>We also talked about this, but I don't think we had a better idea on ways to reduce this kind of exception. Hopefully if you can get a reproducer running, it can help us understand and debug the underlying issue

Thanks for the pointer, I will see how far I can get in reproducing it.
