### ISSUE TITLE
Compatibility with armeria and boot 3.2 versions is broken.

### ISSUE THREAD

**Issue by cj848** [line/armeria#5316]
The following exception occurs when linking with spring boot 3.2 version.
This is probably due to changes in the code specification in spring web 6.1 version.
[spring framework change commit link](https://github.com/spring-projects/spring-framework/commit/df7223f39c3bdc1a187a47443a8a34692280cb59#diff-80d003153fc35acd9545fb81c726d9aa41dffc39c507c590e03e07a2450ed1bfL83)

```
java.lang.NoSuchMethodError: 'void org.springframework.http.server.reactive.AbstractServerHttpRequest.<init>(java.net.URI, java.lang.String, org.springframework.http.HttpHeaders)'
    at com.linecorp.armeria.spring.web.reactive.ArmeriaServerHttpRequest.<init>(ArmeriaServerHttpRequest.java:64)
    at com.linecorp.armeria.spring.web.reactive.ArmeriaHttpHandlerAdapter.handle(ArmeriaHttpHandlerAdapter.java:53)
    at com.linecorp.armeria.spring.web.reactive.ArmeriaReactiveWebServerFactory.lambda$configureService$3(ArmeriaReactiveWebServerFactory.java:352)
    at com.linecorp.armeria.internal.server.RouteDecoratingService.serve(RouteDecoratingService.java:112)
    at com.linecorp.armeria.internal.server.RouteDecoratingService.serve(RouteDecoratingService.java:75)
    at com.linecorp.armeria.server.logging.LoggingService.serve(LoggingService.java:86)
    at com.linecorp.armeria.internal.server.RouteDecoratingService.serve(RouteDecoratingService.java:112)
...

```

**Comment by rogervinas** [comment]
Issue has been fixed in https://github.com/line/armeria/releases/tag/armeria-1.27.0
