### ISSUE TITLE
HttpFile.builder doesn't support spring boot nested jars

### ISSUE THREAD

**Issue by codefromthecrypt** [line/armeria#5390]
The below broke zipkin when we moved to spring boot 3 see https://github.com/openzipkin/zipkin/issues/3694

Not sure the workaround at the moment as the classes used under the builder are package-protected. cc @reta @minwoox @anuraaga 

```
java.lang.IllegalArgumentException: Unsupported URL: jar:nested:/Users/adrian/oss/zipkin/zipkin.jar/!BOOT-INF/lib/zipkin-lens-3.0.3.jar!/zipkin-lens/static/css/main.311b483b.css (must start with 'file:', 'jar:file', 'jrt:' or 'bundle:')
	at com.linecorp.armeria.server.file.HttpFile.builder(HttpFile.java:207) ~[armeria-1.26.4.jar!/:?]
	at com.linecorp.armeria.server.file.HttpFile.builder(HttpFile.java:231) ~[armeria-1.26.4.jar!/:?]
	at com.linecorp.armeria.server.file.ClassPathHttpVfs.blockingGet(ClassPathHttpVfs.java:58) ~[armeria-1.26.4.jar!/:?]
	at com.linecorp.armeria.server.file.AbstractBlockingHttpVfs.lambda$get$0(AbstractBlockingHttpVfs.java:82) ~[armeria-1.26.4.jar!/:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at com.linecorp.armeria.common.DefaultContextAwareRunnable.run(DefaultContextAwareRunnable.java:45) ~[armeria-1.26.4.jar!/:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.100.Final.jar!/:4.1.100.Final]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by codefromthecrypt** [comment]
(url.getPath().startsWith("file:")||url.getPath().startsWith("nested:"))  seems to pass...

**Comment by codefromthecrypt** [comment]
the diff is easy, the test is hard because this isn't something URL will pass in its constructor without a different loader

```diff
--- a/core/src/main/java/com/linecorp/armeria/server/file/HttpFile.java
+++ b/core/src/main/java/com/linecorp/armeria/server/file/HttpFile.java
@@ -199,7 +199,8 @@ public interface HttpFile {
             }
 
             return builder(f.toPath());
-        } else if ("jar".equals(url.getProtocol()) && url.getPath().startsWith("file:") ||
+        } else if ("jar".equals(url.getProtocol()) &&
+                   (url.getPath().startsWith("file:") || url.getPath().startsWith("nested:")) ||
                    "jrt".equals(url.getProtocol()) ||
                    "bundle".equals(url.getProtocol())) {
             return new ClassPathHttpFileBuilder(url);
```

**Comment by codefromthecrypt** [comment]
https://github.com/line/armeria/pull/5391 should fix this
