### ISSUE TITLE
Test failure: `com.linecorp.armeria.client.kubernetes.ArmeriaHttpHttpLoggingInterceptorTest.Interceptor doesn't consume response bytes`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#5428]
```
org.mockito.exceptions.misusing.UnnecessaryStubbingException: 
Unnecessary stubbings detected.
Clean & maintainable test code requires zero unnecessary code.
Following stubbings are unnecessary (click to navigate to relevant line of code):
  1. -> at io.fabric8.kubernetes.client.http.AbstractHttpLoggingInterceptorTest.setUp(AbstractHttpLoggingInterceptorTest.java:82)
Please remove unnecessary stubbings or use 'lenient' strictness. More info: javadoc for UnnecessaryStubbingException class.
	at app//org.mockito.junit.jupiter.MockitoExtension.afterEach(MockitoExtension.java:186)
	at java.base@19.0.2/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base@19.0.2/java.util.ArrayList.forEach(ArrayList.java:1511)

```

**Comment by minwoox** [comment]
Closed by #5598
