### ISSUE TITLE
Compatibility with armeria and grpc 4.26.0 versions is broken.

### ISSUE THREAD

**Issue by cj848** [line/armeria#5504]
The following exception occurred during application running:
When the grpc library was updated
GeneratedMessageV3 has been deprecated. [link](https://github.com/protocolbuffers/protobuf/releases/tag/v26.0)
[Java] The base class for generated messages will be GeneratedMessage, not GeneratedMessageV3.

please fix it
```
  Caused by:
             java.lang.NoClassDefFoundError: Could not initialize class com.linecorp.armeria.server.grpc.DefaultHttpJsonTranscodingOptions
                 at com.linecorp.armeria.server.grpc.HttpJsonTranscodingOptions.of(HttpJsonTranscodingOptions.java:42)
                 at com.linecorp.armeria.server.grpc.GrpcServiceBuilder.<init>(GrpcServiceBuilder.java:129)
                 at com.linecorp.armeria.server.grpc.GrpcService.builder(GrpcService.java:56)
                 at lasco.configuration.ArmeriaConfig.armeriaServerConfigurator$lambda$3(ArmeriaConfig.kt:42)
                 at com.linecorp.armeria.internal.spring.ArmeriaConfigurationUtil.lambda$configureServerWithArmeriaSettings$0(ArmeriaConfigurationUtil.java:140)
                 at com.linecorp.armeria.internal.shaded.guava.collect.ImmutableList.forEach(ImmutableList.java:423)
                 at com.linecorp.armeria.internal.spring.ArmeriaConfigurationUtil.configureServerWithArmeriaSettings(ArmeriaConfigurationUtil.java:140)
                 at com.linecorp.armeria.spring.web.reactive.ArmeriaReactiveWebServerFactory.getWebServer(ArmeriaReactiveWebServerFactory.java:161)
                 at org.springframework.boot.web.reactive.context.WebServerManager.<init>(WebServerManager.java:50)
                 at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.createWebServer(ReactiveWebServerApplicationContext.java:96)
                 at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:81)
                 ...98 more

                 Caused by:
                 java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3 [in thread "Test worker"]
                     at java.base/java.lang.ClassLoader.defineClass1(Native Method)
                     at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
                     at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
                    ... more
```

**Comment by jrhee17** [comment]
Armeria's gRPC module depends heavily on `grpc-java`. We'll probably move on to protobuf 26.0 once `grpc-java` also moves on.

https://github.com/grpc/grpc-java/blob/34e241a60e7dd54195daaec3a16decae0dd702cc/gradle/libs.versions.toml#L8

**Comment by friscoMad** [comment]
Even if staying in the same version that grpc-java uses please update the code to remove that GeneratedMessageV3 usage as recommended by grpc-java team here: https://github.com/grpc/grpc-java/issues/11015#issuecomment-2560196695

**Comment by minwoox** [comment]
I think there's no issue with the Protobuf4 and we are validating it using this it module:
https://github.com/line/armeria/tree/main/it/grpc/protobuf4

**Comment by ikhoon** [comment]
Fixed by #6135
