### ISSUE TITLE
Exception raised when closing a connection that exceeded maxNumConnections

### ISSUE THREAD

**Issue by trustin** [line/armeria#558]
Due to the following bug in Netty: https://github.com/netty/netty/issues/6770

It seems like the connection is closed. An exception will be logged by Netty, which is potentially expensive. It's probably OK to leave it as it is, but we should keep track of this.

```
05:53:55.405 [armeria-server-boss-epoll-26-1] WARN  io.netty.channel.AbstractChannel - Failed to close a channel.
java.lang.IllegalStateException: channel not registered to an event loop
	at io.netty.channel.AbstractChannel.eventLoop(AbstractChannel.java:158)
	at io.netty.channel.epoll.AbstractEpollChannel.doDeregister(AbstractEpollChannel.java:140)
	at io.netty.channel.epoll.AbstractEpollChannel.doClose(AbstractEpollChannel.java:117)
	at io.netty.channel.epoll.AbstractEpollStreamChannel.doClose(AbstractEpollStreamChannel.java:721)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.closeForcibly(AbstractChannel.java:703)
```

**Comment by trustin** [comment]
Fixed after upgrading to Netty 4.1.12.
