### ISSUE TITLE
Test failure: `com.linecorp.armeria.common.ContextPushHookTest.shouldRunHooksWhenContextIsPushed()`

### ISSUE THREAD

**Issue by minwoox** [line/armeria#5672]
```
org.opentest4j.AssertionFailedError: 
Expecting actual:
  ["ServerBuilder/push",
    "Service/push",
    "ServiceContext/push",
    "ClientBuilder/push",
    "ClientContext/push",
    "VirtualHost/push",
    "VirtualService/push"]
to contain exactly (and in same order):
  ["ClientBuilder/push",
    "ClientContext/push",
    "ServerBuilder/push",
    "VirtualHost/push",
    "VirtualService/push",
    "ServiceContext/push"]
but some elements were not expected:
  ["Service/push"]

	at java.base@17.0.10/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base@17.0.10/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base@17.0.10/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base@17.0.10/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at app//com.linecorp.armeria.common.ContextPushHookTest.shouldRunHooksWhenContextIsPushed(ContextPushHookTest.java:138)
	at java.base@17.0.10/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base@17.0.10/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base@17.0.10/java.util.ArrayList.forEach(ArrayList.java:1511)

```

**Comment by trustin** [comment]
[Build Scan](https://ge.armeria.dev/s/6n7adjy6f3uzc/tests/task/:core:shadedTest/details/com.linecorp.armeria.common.ContextPushHookTest/shouldRunHooksWhenContextIsPushed()?top-execution=1)
