### ISSUE TITLE
Test failure: `com.linecorp.armeria.server.InvalidPathWithDataTest.invalidPath()`

### ISSUE THREAD

**Issue by minwoox** [line/armeria#5681]
```
java.io.IOException: RST_STREAM received
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:964)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
	at com.linecorp.armeria.server.InvalidPathWithDataTest.invalidPath(InvalidPathWithDataTest.java:76)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.io.IOException: RST_STREAM received
	at java.net.http/jdk.internal.net.http.Stream.incoming_reset(Stream.java:586)
	at java.net.http/jdk.internal.net.http.Stream.otherFrame(Stream.java:501)
	at java.net.http/jdk.internal.net.http.Stream.incoming(Stream.java:494)
	at java.net.http/jdk.internal.net.http.Http2Connection.processFrame(Http2Connection.java:936)
	at java.net.http/jdk.internal.net.http.frame.FramesDecoder.decode(FramesDecoder.java:155)
	at java.net.http/jdk.internal.net.http.Http2Connection$FramesController.processReceivedData(Http2Connection.java:307)
	at java.net.http/jdk.internal.net.http.Http2Connection.asyncReceive(Http2Connection.java:778)
	at java.net.http/jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.processQueue(Http2Connection.java:1594)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:182)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

**Comment by minwoox** [comment]
I've seen this flaky test frequently so I've analyzed it.

`ServerHttp2ObjectEncoder` resets the stream after sending an invalid request path response if the client still sends something: https://github.com/line/armeria/blob/d398661d1c82244b7e727d74c6983ec29dfeb02d/core/src/main/java/com/linecorp/armeria/server/ServerHttp2ObjectEncoder.java#L132
If the client receives the response before receiving the RST_STREAM, the test doesn't fail. Otherwise, it fails.
I believe we can't avoid this flakiness so we need to mark it with the `@FlakyTest`.
