### ISSUE TITLE
Test failure: `com.linecorp.armeria.common.stream.InputStreamStreamMessageTest.thrownInputStream()`

### ISSUE THREAD

**Issue by minwoox** [line/armeria#5695]
```
org.opentest4j.AssertionFailedError: 
Expecting value to be false but was true
	at java.base@17.0.10/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base@17.0.10/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base@17.0.10/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base@17.0.10/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at app//com.linecorp.armeria.common.stream.InputStreamStreamMessageTest.thrownInputStream(InputStreamStreamMessageTest.java:450)
	at java.base@17.0.10/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base@17.0.10/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base@17.0.10/java.util.ArrayList.forEach(ArrayList.java:1511)

```

**Comment by kojilin** [comment]
Maybe due to downstream got result earlier than completionFuture at https://github.com/line/armeria/blob/0d94d0df85ba9b1184c79ffdd58d3e414b2f0c7d/core/src/main/java/com/linecorp/armeria/common/stream/InputStreamStreamMessage.java#L374-L380 ? I think it's ok to just add awaitility to wait for `open is false` case. WDYT?
