### ISSUE TITLE
Test failure: `com.linecorp.armeria.common.stream.StreamMessageCollectingTest.filteredStreamMessage_exception()`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#5866]
```
org.opentest4j.AssertionFailedError: 
expected: 0
 but was: 1
	at app//com.linecorp.armeria.common.stream.StreamMessageCollectingTest.assertRefCount(StreamMessageCollectingTest.java:390)
	at app//com.linecorp.armeria.common.stream.StreamMessageCollectingTest.filteredStreamMessage_exception(StreamMessageCollectingTest.java:168)
	at java.base@21.0.3/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base@21.0.3/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base@21.0.3/java.util.ArrayList.forEach(ArrayList.java:1596)

```

**Comment by ikhoon** [comment]
Fixed by #5867
