### ISSUE TITLE
Test failure: `com.linecorp.armeria.client.ContextCancellationTest.cancel_beforeWriteFinished(TestInfo)`

### ISSUE THREAD

**Issue by ikhoon** [line/armeria#5868]
```
java.lang.AssertionError: 
Expecting empty but was: [[creqId=5d73bf85][http://127.0.0.1:45623/#GET]]
	at com.linecorp.armeria.client.ContextCancellationTest.validateCallbackChecks(ContextCancellationTest.java:289)
	at com.linecorp.armeria.client.ContextCancellationTest.cancel_beforeWriteFinished(ContextCancellationTest.java:259)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

```

**Comment by jrhee17** [comment]
😿  Feel free to proceed with the release ignoring this test failure. Let me handle this once my backlog is a little less full

**Comment by jrhee17** [comment]
Closing this issue since the test was fixed
