### ISSUE TITLE
Early rejection for requests exceeding configured maxRequestLength

### ISSUE THREAD

**Issue by yzfeng2020** [line/armeria#5880]
It is is possible to implement early rejection of HTTP requests when the Content-Length header indicates a value larger than the maximum configured request length. This would be beneficial to avoid unnecessary processing of oversized requests.

The relevant code section is located at https://github.com/line/armeria/blob/d30dff0db75915e160b31a427f6f3c0c25fc003b/core/src/main/java/com/linecorp/armeria/server/Http1RequestDecoder.java#L211-L226 for H1 and https://github.com/line/armeria/blob/d30dff0db75915e160b31a427f6f3c0c25fc003b/core/src/main/java/com/linecorp/armeria/server/Http2RequestDecoder.java#L167-L180 for H2.

discord discussion: https://discord.com/channels/1087271586832318494/1087272728177942629/1275651316034699327

**Comment by jrhee17** [comment]
Hi, you can try sending a request without the `content-length` header to verify if the old behavior passes the test.

Let me also take a look at why the upgrade fails the test

**Comment by danicheg** [comment]
@jrhee17 Thanks! But it's not only about a failed test. It's about the ability to opt in/out the functionality overall.

**Comment by jrhee17** [comment]
> @jrhee17 Thanks! But it's not only about a failed test. It's about the ability to opt in/out the functionality overall.

If there is a scenario where users prefer not to abort early, then I'm all for providing a way to opt out.
Having said this, I doubt there are users who prefer not to abort too large requests depending on the header.

About the failure, I noticed the following error log

```
java.lang.Error: received subscription in invalid state [UpstreamError(com.linecorp.armeria.common.ContentTooLargeException: maxContentLength: 1024, contentLength: 1025, transferred: 0, earlyRejection: true)]
	at fs2.interop.reactivestreams.StreamSubscriber$.$anonfun$fsm$1(StreamSubscriber.scala:154)
	at fs2.interop.reactivestreams.StreamSubscriber$$anon$1.$anonfun$nextState$1(StreamSubscriber.scala:209)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at fs2.interop.reactivestreams.StreamSubscriber$$anon$1.nextState(StreamSubscriber.scala:208)
	at fs2.interop.reactivestreams.StreamSubscriber$$anon$1.onSubscribe(StreamSubscriber.scala:213)
	at fs2.interop.reactivestreams.StreamSubscriber.onSubscribe(StreamSubscriber.scala:54)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.subscribe(DefaultStreamMessage.java:152)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.lambda$subscribe$0(DefaultStreamMessage.java:138)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask$$$capture(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:300)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

I found that there armeria sometimes can violate reactive streams specification by invoking `onSubscribe` after `onError`.
This bug likely existed for a while, but was noticed due to the PR you mentioned.

I'm not too familiar with scala/cats/etc so I'm not sure how this causes the hang, but I was able to verify fixing applying the patch successfully completes the test.

**Comment by danicheg** [comment]
> If there is a scenario where users prefer not to abort early, then I'm all for providing a way to opt out.

In http4s, we [recently discussed](https://github.com/http4s/http4s/pull/7602) the potential hangs of external HTTP clients due to the eager behaviour of http4s' middleware that checks entity lengths (it doesn't fully consume or drain the request body). Some folks mentioned that there are cases where HTTP clients do indeed hang because of this. I haven't checked this myself, so take it for what it's worth.

> I found that there armeria sometimes can violate reactive streams specification by invoking onSubscribe after onError.
This bug likely existed for a while, but was noticed due to the PR you mentioned.

Yeah, I've seen this log too, but I thought it was related to how `fs2-reactive-streams` strictly handles `onSubscribe` when the state is already `UpstreamError`. Cool that you validated this and determined it's related to Armeria!

> I'm not too familiar with scala/cats/etc so I'm not sure how this causes the hang, but I was able to verify fixing applying the patch successfully completes the test.

Could you please open a PR with the mentioned fix in Armeria repo so that I can locally publish Armeria and validate the fix myself? 🙇‍♂

**Comment by jrhee17** [comment]
> Ah, perhaps, you already opened a PR (https://github.com/line/armeria/pull/6166), did you?

Yes, you can either run `./gradlew publishToMavenLocal` or wait for the snapshot version `1.32.4-SNAPSHOT` once the PR is merged to the main branch.
