### ISSUE TITLE
Test failure: `com.linecorp.armeria.xds.client.endpoint.DynamicHealthCheckTest.gracefulEndpointUpdate()`

### ISSUE THREAD

**Issue by minwoox** [line/armeria#5897]
```
org.opentest4j.AssertionFailedError: 
expected: /127.0.0.1:34782
 but was: /127.0.0.1:34794
	at app//com.linecorp.armeria.xds.client.endpoint.DynamicHealthCheckTest.gracefulEndpointUpdate(DynamicHealthCheckTest.java:272)
	at java.base@11.0.22/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base@11.0.22/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base@11.0.22/java.util.ArrayList.forEach(ArrayList.java:1541)

```

**Comment by jrhee17** [comment]
Looking at the logs, it seems like the connection was reset for some reason:
```
07:51:22.179 [armeria-common-worker-epoll-3-4] WARN  c.l.a.i.c.AbstractHttp2ConnectionHandler - [id: 0xfa43be94, L:/127.0.0.1:34782 - R:127.0.0.1/127.0.0.1:43087] HTTP/2 connection error:
io.netty.handler.codec.http2.Http2Exception: failed to consume a HEADERS frame
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:121)
	at com.linecorp.armeria.client.Http2ResponseDecoder.onHeadersRead(Http2ResponseDecoder.java:220)
```

To be honest, I don't think there's much that can be done for this case other than marking as flaky, or removing it.

Given that this test isn't really failing often compared to other tests, let me just monitor this case and remove if needed
