### ISSUE TITLE
Using fluent builder patterns can cause issues for Scala 3 users

### ISSUE THREAD

**Issue by jrhee17** [line/armeria#5947]
Running the following currently fails for scala 3 since 1.29.0 ([PR](https://github.com/line/armeria/pull/5733))

(The following can be run from `{root_dir}/scala/scala_3`)

```scala
@main
def main(): Unit = {
  DnsAddressEndpointGroup.builder("")
    .selectionTimeout(Duration.ofDays(1))
    .selectionTimeout(Duration.ofDays(1))
    .selectionTimeout(Duration.ofDays(1))
    .build()

  val server = Server.builder()
    .contextPath("/v1")
    .service("/", (ctx, req) => HttpResponse.of("Hello, world"))
    .and()
    .build()
    .start()

  println(s"server started = ${server}")
}
```

```
Exception in thread "main" java.lang.IllegalAccessError: failed to access class com.linecorp.armeria.client.endpoint.dns.DnsEndpointGroupBuilder from class TestSuite$package$
	at TestSuite$package$.main(TestSuite.scala:14)
	at main.main(TestSuite.scala:8)
```

It seems like when returning the SELF type, Scala3 tries to find the returned class AND superclasses for some reason.

It might be a better idea to steer clear of this pattern until Scala3 side applies a fix, or we decide to make builder superclasses public.

Link for reference: https://github.com/scala/scala3/issues/21797

**Comment by chungonn** [comment]
Hi, I have just confirmed that the issue is resolved since Scala version3.6.2. I have just tested on Scala version 3.6.3 and confirmed it is compiling without any exception thrown.

You may wish to close this issue.

Thanks again for keeping tap on this issue.

**Comment by ikhoon** [comment]
Thank you for letting us know. 🙇‍♂️
