### ISSUE TITLE
Fix assertion exception in DefaultDnsResolver

### ISSUE THREAD

**Issue by minwoox** [line/armeria#6003]
```
java.lang.AssertionError: null
	at com.linecorp.armeria.internal.client.dns.DefaultDnsResolver.resolveOne(DefaultDnsResolver.java:88)
	at com.linecorp.armeria.internal.client.dns.DefaultDnsResolver.resolve(DefaultDnsResolver.java:81)
	at com.linecorp.armeria.client.RefreshingAddressResolver.sendQueries(RefreshingAddressResolver.java:161)
	at com.linecorp.armeria.client.RefreshingAddressResolver.access$500(RefreshingAddressResolver.java:56)
	at com.linecorp.armeria.client.RefreshingAddressResolver$CacheEntry.refresh(RefreshingAddressResolver.java:356)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:300)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by minwoox** [comment]
Closed by #6092
