### ISSUE TITLE
Test failure: `com.linecorp.armeria.client.endpoint.healthcheck.HealthCheckedEndpointGroupTest.cacheReflectsAttributeChanges()`

### ISSUE THREAD

**Issue by minwoox** [line/armeria#6018]
```
java.lang.AssertionError: 
Expecting AtomicLong(2) to have value:
  1L
but did not.
	at com.linecorp.armeria.client.endpoint.healthcheck.HealthCheckedEndpointGroupTest.lambda$cacheReflectsAttributeChanges$15(HealthCheckedEndpointGroupTest.java:565)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

**Comment by trustin** [comment]
@hyunw9 👋 No one's working on this issue as far as I know. Please feel free to send a pull request!
