### ISSUE TITLE
Flaky test: THttpClientBadSeqIdTest.badSeqId

### ISSUE THREAD

**Issue by trustin** [line/armeria#624]
```
com.linecorp.armeria.client.thrift.THttpClientBadSeqIdTest > badSeqId FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 10000 milliseconds
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at com.linecorp.armeria.client.thrift.THttpClientBadSeqIdTest.badSeqId(THttpClientBadSeqIdTest.java:46)
```

**Comment by trustin** [comment]
Probably a bug in JaCoCo instrumentation:

```
com.linecorp.armeria.client.thrift.THttpClientBadSeqIdTest > badSeqId FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 10000 milliseconds
        at org.jacoco.agent.rt.internal_e5875b2.asm.Type.getType(Type.java:482)
        at org.jacoco.agent.rt.internal_e5875b2.asm.Type.getArgumentTypes(Type.java:344)
        at org.jacoco.agent.rt.internal_e5875b2.asm.commons.AnalyzerAdapter.<init>(AnalyzerAdapter.java:184)
        at org.jacoco.agent.rt.internal_e5875b2.asm.commons.AnalyzerAdapter.<init>(AnalyzerAdapter.java:144)
        at org.jacoco.agent.rt.internal_e5875b2.core.internal.flow.ClassProbesAdapter$2.visitEnd(ClassProbesAdapter.java:83)
        at org.jacoco.agent.rt.internal_e5875b2.asm.ClassReader.readMethod(ClassReader.java:1021)
        at org.jacoco.agent.rt.internal_e5875b2.asm.ClassReader.accept(ClassReader.java:693)
        at org.jacoco.agent.rt.internal_e5875b2.asm.ClassReader.accept(ClassReader.java:506)
        at org.jacoco.agent.rt.internal_e5875b2.core.instr.Instrumenter.instrument(Instrumenter.java:84)
        at org.jacoco.agent.rt.internal_e5875b2.core.instr.Instrumenter.instrument(Instrumenter.java:108)
        at org.jacoco.agent.rt.internal_e5875b2.CoverageTransformer.transform(CoverageTransformer.java:91)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.assertj.core.api.Assertions.assertThat(Assertions.java:266)
        at com.linecorp.armeria.client.thrift.THttpClientBadSeqIdTest.badSeqId(THttpClientBadSeqIdTest.java:44)
```

**Comment by trustin** [comment]
Didn't see this for a while.
