### ISSUE TITLE
Flaky test: HttpServerTest.testTooLargeContent

### ISSUE THREAD

**Issue by trustin** [line/armeria#630]
```
com.linecorp.armeria.server.http.HttpServerTest > testTooLargeContent[0: h1c] FAILED
    java.util.concurrent.ExecutionException: com.linecorp.armeria.common.ClosedSessionException
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at com.linecorp.armeria.server.http.HttpServerTest.testTooLargeContent(HttpServerTest.java:516)
        Caused by:
        com.linecorp.armeria.common.ClosedSessionException
```
https://ci.appveyor.com/project/trustin/armeria/build/master.591#L623

**Comment by anuraaga** [comment]
Have been seeing this a lot lately, and always on appveyor

**Comment by trustin** [comment]
Actually, the originally reported exception was `ClosedSessionException` which is not `AbortedStreamException`.
