### ISSUE TITLE
Flaky test: ServerTest.testIdleTimeoutByNoContentSent 

### ISSUE THREAD

**Issue by trustin** [line/armeria#636]
```
com.linecorp.armeria.server.ServerTest > testIdleTimeoutByNoContentSent FAILED
    java.lang.AssertionError: 
    Expected: is a value equal to or greater than <500L>
         but: <498L> was less than <500L>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at com.linecorp.armeria.server.ServerTest.testIdleTimeoutByNoContentSent(ServerTest.java:208)
```

https://travis-ci.org/line/armeria/builds/246949908

**Comment by trustin** [comment]
The measured duration can be smaller than the expected timeout because there is delay between `OutputStream.write()` and the actual server-side reception. Can be fixed by just relaxing the assertion a little bit.
