### ISSUE TITLE
Flaky test: RetryingHttpClientTest

### ISSUE THREAD

**Issue by trustin** [line/armeria#666]
```
RetryingHttpClientTest.differentResponseTimeout: FAILURE
--------------------------------------------------------
com.linecorp.armeria.client.retry.RetryingHttpClientTest > differentResponseTimeout FAILED
    java.util.concurrent.CompletionException: com.linecorp.armeria.client.ResponseTimeoutException
        at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
        at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
        at com.linecorp.armeria.client.retry.RetryingHttpClientTest.differentResponseTimeout(RetryingHttpClientTest.java:363)

        Caused by:
        com.linecorp.armeria.client.ResponseTimeoutException
```

```
RetryingHttpClientTest.consecutiveRequests: FAILURE
---------------------------------------------------
com.linecorp.armeria.client.retry.RetryingHttpClientTest > consecutiveRequests FAILED
    java.lang.AssertionError:
    Expecting:
     <499L>
    to be greater than or equal to:
     <500L>
        at com.linecorp.armeria.client.retry.RetryingHttpClientTest.consecutiveRequests(RetryingHttpClientTest.java:318)
```

```
RetryingHttpClientTest.timeoutWhenServerSendServiceUnavailable: FAILURE
-----------------------------------------------------------------------
com.linecorp.armeria.client.retry.RetryingHttpClientTest > timeoutWhenServerSendServiceUnavailable FAILED
    java.lang.AssertionError: 
    Expecting:
     <999L>
    to be greater than or equal to:
     <1000L> 
        at com.linecorp.armeria.client.retry.RetryingHttpClientTest.timeoutWhenServerSendServiceUnavailable(RetryingHttpClientTest.java:306)
```

**Comment by trustin** [comment]
Another:

```
RetryingHttpClientTest.consecutiveRequests: FAILURE
---------------------------------------------------
com.linecorp.armeria.client.retry.RetryingHttpClientTest > consecutiveRequests FAILED
    java.lang.AssertionError:
    Expecting:
     <499L>
    to be greater than or equal to:
     <500L>
        at com.linecorp.armeria.client.retry.RetryingHttpClientTest.consecutiveRequests(RetryingHttpClientTest.java:318)
```

**Comment by anuraaga** [comment]
Just saw this

```
om.linecorp.armeria.client.retry.RetryingHttpClientTest > timeoutWhenServerDoseNotResponse FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 10 seconds
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
        at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
        at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
        at com.linecorp.armeria.client.retry.RetryingHttpClientTest.lambda$timeoutWhenServerDoseNotResponse$4(RetryingHttpClientTest.java:298)
        at com.linecorp.armeria.client.retry.RetryingHttpClientTest$$Lambda$324/408191330.call(Unknown Source)
        at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:60)
        at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:713)
        at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1135)
        at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1061)
        at com.linecorp.armeria.client.retry.RetryingHttpClientTest.timeoutWhenServerDoseNotResponse(RetryingHttpClientTest.java:298)
08:39:18.539 [Thread-10] DEBUG c.l.armeria.client.ClientFactory - Closing the default ClientFactory
535 tests completed, 1 failed
:core:test FAILED
```

**Comment by minwoox** [comment]
I'm working on this. Sorry for the inconvenience. I will send another PR for HttpClientBuilder and it will contains implementation solving this issue...

**Comment by trustin** [comment]
#680 contains the fix to be specific.
