### ISSUE TITLE
Why   response  to  request   immediately,not execute  my business code ?

### ISSUE THREAD

**Issue by sunning9001** [line/armeria#739]
I sent 10 requests simultaneously, nine of which were executed successfully, but one of them returned immediately before the logic code was executed.

I set the timeout timeout of 30 seconds, but within one second, one of the requests returned immediately. My logical code was not yet running

1. The first black font section is the response received from one of the requests

2.The second black font part is the log for immediate response

Could you please help me to see what might have caused this ???  @minwoox @anuraaga 

the  client  side    log:

2017-08-23 09:26:31.927  INFO 19313 --- [orker-epoll-3-3] c.l.a.client.logging.LoggingClient       : [id: 0x63f1ab03, L:/192.168.1.25:40158 - R:192.168.1.25/192.168.1.25:8181][http://192.168.1.25:8181/rpc/#POST] Request: {startTime=2017-08-23T01:26:31.922Z(1503451591922), length=67B, duration=3728µs(3728273ns), scheme=gproto+h2c, host=192.168.1.25, headers=[:method=POST, content-type=application/grpc+proto, grpc-accept-encoding=gzip, grpc-timeout=30000000u, :authority=192.168.1.25:8181, :scheme=http, user-agent=armeria/0.52.0, :path=/rpc/MarketChargeService/marketCharge], content=DefaultRpcRequest{serviceType=GrpcLogUtil, method=MarketChargeService/marketCharge, params=[]}}
1 ------------------------
2017-08-23 09:26:31.929  INFO 19313 --- [orker-epoll-3-1] c.l.a.client.logging.LoggingClient       : [id: 0x27ae5be7, L:/192.168.1.25:40156 - R:192.168.1.25/192.168.1.25:8181][http://192.168.1.25:8181/rpc/#POST] Request: {startTime=2017-08-23T01:26:31.922Z(1503451591922), length=66B, duration=6532µs(6532253ns), scheme=gproto+h2c, host=192.168.1.25, headers=[:method=POST, content-type=application/grpc+proto, grpc-accept-encoding=gzip, grpc-timeout=30000000u, :authority=192.168.1.25:8181, :scheme=http, user-agent=armeria/0.52.0, :path=/rpc/BalanceFreezeService/BalanceFreeze], content=DefaultRpcRequest{serviceType=GrpcLogUtil, method=BalanceFreezeService/BalanceFreeze, params=[]}}
2--------------------------------
2017-08-23 09:26:31.930  INFO 19313 --- [rker-epoll-3-10] c.l.a.client.logging.LoggingClient       : [id: 0xed3b6cff, L:/192.168.1.25:40165 - R:192.168.1.25/192.168.1.25:8181][http://192.168.1.25:8181/rpc/#POST] Request: {startTime=2017-08-23T01:26:31.925Z(1503451591925), length=68B, duration=4557µs(4557678ns), scheme=gproto+h2c, host=192.168.1.25, headers=[:method=POST, content-type=application/grpc+proto, grpc-accept-encoding=gzip, grpc-timeout=30000000u, :authority=192.168.1.25:8181, :scheme=http, user-agent=armeria/0.52.0, :path=/rpc/BalanceFreezeService/BalanceFreeze], content=DefaultRpcRequest{serviceType=GrpcLogUtil, method=BalanceFreezeService/BalanceFreeze, params=[]}}

3--------------------------------
2017-08-23 09:26:31.930  INFO 19313 --- [orker-epoll-3-2] c.l.a.client.logging.LoggingClient       : [id: 0x162b58b9, L:/192.168.1.25:40157 - R:192.168.1.25/192.168.1.25:8181][http://192.168.1.25:8181/rpc/#POST] Request: {startTime=2017-08-23T01:26:31.925Z(1503451591925), length=67B, duration=4406µs(4406489ns), scheme=gproto+h2c, host=192.168.1.25, headers=[:method=POST, content-type=application/grpc+proto, grpc-accept-encoding=gzip, grpc-timeout=30000000u, :authority=192.168.1.25:8181, :scheme=http, user-agent=armeria/0.52.0, :path=/rpc/MarketChargeService/marketCharge], content=DefaultRpcRequest{serviceType=GrpcLogUtil, method=MarketChargeService/marketCharge, params=[]}}
4--------------------------------
2017-08-23 09:26:31.930  INFO 19313 --- [orker-epoll-3-8] c.l.a.client.logging.LoggingClient       : [id: 0x0b10107e, L:/192.168.1.25:40163 - R:192.168.1.25/192.168.1.25:8181][http://192.168.1.25:8181/rpc/#POST] Request: {startTime=2017-08-23T01:26:31.925Z(1503451591925), length=67B, duration=4493µs(4493467ns), scheme=gproto+h2c, host=192.168.1.25, headers=[:method=POST, content-type=application/grpc+proto, grpc-accept-encoding=gzip, grpc-timeout=30000000u, :authority=192.168.1.25:8181, :scheme=http, user-agent=armeria/0.52.0, :path=/rpc/BalanceFreezeService/BalanceFreeze], content=DefaultRpcRequest{serviceType=GrpcLogUtil, method=BalanceFreezeService/BalanceFreeze, params=[]}}
5--------------------------------
2017-08-23 09:26:31.932  INFO 19313 --- [orker-epoll-3-7] c.l.a.client.logging.LoggingClient       : [id: 0x0c41ec0e, L:/192.168.1.25:40162 - R:192.168.1.25/192.168.1.25:8181][http://192.168.1.25:8181/rpc/#POST] Request: {startTime=2017-08-23T01:26:31.925Z(1503451591925), length=67B, duration=6497µs(6497804ns), scheme=gproto+h2c, host=192.168.1.25, headers=[:method=POST, content-type=application/grpc+proto, grpc-accept-encoding=gzip, grpc-timeout=30000000u, :authority=192.168.1.25:8181, :scheme=http, user-agent=armeria/0.52.0, :path=/rpc/MarketChargeService/marketCharge], content=DefaultRpcRequest{serviceType=GrpcLogUtil, method=MarketChargeService/marketCharge, params=[]}}

6--------------------------------
2017-08-23 09:26:31.933  INFO 19313 --- [orker-epoll-3-4] c.l.a.client.logging.LoggingClient       : [id: 0x68548a21, L:/192.168.1.25:40159 - R:192.168.1.25/192.168.1.25:8181][http://192.168.1.25:8181/rpc/#POST] Request: {startTime=2017-08-23T01:26:31.925Z(1503451591925), length=67B, duration=7775µs(7775595ns), scheme=gproto+h2c, host=192.168.1.25, headers=[:method=POST, content-type=application/grpc+proto, grpc-accept-encoding=gzip, grpc-timeout=30000000u, :authority=192.168.1.25:8181, :scheme=http, user-agent=armeria/0.52.0, :path=/rpc/MarketChargeService/marketCharge], content=DefaultRpcRequest{serviceType=GrpcLogUtil, method=MarketChargeService/marketCharge, params=[]}}

7-----------------------------
2017-08-23 09:26:31.933  INFO 19313 --- [orker-epoll-3-5] c.l.a.client.logging.LoggingClient       : [id: 0xa9acd948, L:/192.168.1.25:40160 - R:192.168.1.25/192.168.1.25:8181][http://192.168.1.25:8181/rpc/#POST] Request: {startTime=2017-08-23T01:26:31.926Z(1503451591926), length=67B, duration=7479µs(7479765ns), scheme=gproto+h2c, host=192.168.1.25, headers=[:method=POST, content-type=application/grpc+proto, grpc-accept-encoding=gzip, grpc-timeout=30000000u, :authority=192.168.1.25:8181, :scheme=http, user-agent=armeria/0.52.0, :path=/rpc/MarketChargeService/marketCharge], content=DefaultRpcRequest{serviceType=GrpcLogUtil, method=MarketChargeService/marketCharge, params=[]}}
8----------------------------------
2017-08-23 09:26:31.934  INFO 19313 --- [orker-epoll-3-6] c.l.a.client.logging.LoggingClient       : [id: 0x95f74610, L:/192.168.1.25:40161 - R:192.168.1.25/192.168.1.25:8181][http://192.168.1.25:8181/rpc/#POST] Request: {startTime=2017-08-23T01:26:31.926Z(1503451591926), length=68B, duration=7936µs(7936793ns), scheme=gproto+h2c, host=192.168.1.25, headers=[:method=POST, content-type=application/grpc+proto, grpc-accept-encoding=gzip, grpc-timeout=30000000u, :authority=192.168.1.25:8181, :scheme=http, user-agent=armeria/0.52.0, :path=/rpc/BalanceFreezeService/BalanceFreeze], content=DefaultRpcRequest{serviceType=GrpcLogUtil, method=BalanceFreezeService/BalanceFreeze, params=[]}}
9---------------------------------------------
2017-08-23 09:26:31.936  INFO 19313 --- [orker-epoll-3-9] c.l.a.client.logging.LoggingClient       : [id: 0x2573ca57, L:/192.168.1.25:40164 - R:192.168.1.25/192.168.1.25:8181][http://192.168.1.25:8181/rpc/#POST] Request: {startTime=2017-08-23T01:26:31.928Z(1503451591928), length=67B, duration=7777µs(7777088ns), scheme=gproto+h2c, host=192.168.1.25, headers=[:method=POST, content-type=application/grpc+proto, grpc-accept-encoding=gzip, grpc-timeout=30000000u, :authority=192.168.1.25:8181, :scheme=http, user-agent=armeria/0.52.0, :path=/rpc/MarketChargeService/marketCharge], content=DefaultRpcRequest{serviceType=GrpcLogUtil, method=MarketChargeService/marketCharge, params=[]}}
10----------------------------------------

**2017-08-23 09:26:33.183  INFO 19313 --- [orker-epoll-3-1] c.l.a.client.logging.LoggingClient       : [id: 0x27ae5be7, L:/192.168.1.25:40156 - R:192.168.1.25/192.168.1.25:8181][http://192.168.1.25:8181/rpc/#POST] Response: {startTime=2017-08-23T01:26:33.181Z(1503451593181), length=0B, duration=110µs(110421ns), headers=[:status=200, content-type=application/grpc+proto, grpc-status=0], content=DefaultRpcResponse{success}}
java.util.concurrent.TimeoutException: io.grpc.StatusRuntimeException: INTERNAL: No value received for unary call
        at com.afis.jzcg.PingAnFunction.balanceFreeze(PingAnFunction.java:128)
        at com.afis.jx.htp.util.FundTransfer$27.get(FundTransfer.java:1750)
        at com.afis.jx.htp.util.FundTransfer$27.get(FundTransfer.java:1743)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)**

the  server side log:

2017-08-23 09:26:31.924 [DEBUG] [armeria-server-epoll-5-4] c.l.a.internal.Http2GoAwayListener - [id: 0xf4642e1f, L:/192.168.1.25:8181 - R:/192.168.1.25:40159] HTTP/2 upgrade stream removed: CLOSED
2017-08-23 09:26:31.924 [DEBUG] [armeria-server-epoll-5-6] c.l.a.internal.Http2GoAwayListener - [id: 0xe765d8de, L:/192.168.1.25:8181 - R:/192.168.1.25:40161] HTTP/2 upgrade stream removed: CLOSED
2017-08-23 09:26:31.925 [DEBUG] [armeria-server-epoll-5-1] c.l.a.internal.Http2GoAwayListener - [id: 0xb4672d97, L:/192.168.1.25:8181 - R:/192.168.1.25:40156] HTTP/2 upgrade stream removed: CLOSED
2017-08-23 09:26:31.926 [DEBUG] [armeria-server-epoll-5-9] c.l.a.internal.Http2GoAwayListener - [id: 0x75360336, L:/192.168.1.25:8181 - R:/192.168.1.25:40164] HTTP/2 upgrade stream removed: CLOSED
2017-08-23 09:26:31.926 [DEBUG] [armeria-server-epoll-5-8] c.l.a.internal.Http2GoAwayListener - [id: 0x128b3bf1, L:/192.168.1.25:8181 - R:/192.168.1.25:40163] HTTP/2 upgrade stream removed: CLOSED
2017-08-23 09:26:31.926 [DEBUG] [armeria-server-epoll-5-5] c.l.a.internal.Http2GoAwayListener - [id: 0x58e3169b, L:/192.168.1.25:8181 - R:/192.168.1.25:40160] HTTP/2 upgrade stream removed: CLOSED
2017-08-23 09:26:31.927 [DEBUG] [armeria-server-epoll-5-10] c.l.a.internal.Http2GoAwayListener - [id: 0xc6457a94, L:/192.168.1.25:8181 - R:/192.168.1.25:40165] HTTP/2 upgrade stream removed: CLOSED
2017-08-23 09:26:31.926 [DEBUG] [armeria-server-epoll-5-3] c.l.a.internal.Http2GoAwayListener - [id: 0x4f5bac9c, L:/192.168.1.25:8181 - R:/192.168.1.25:40158] HTTP/2 upgrade stream removed: CLOSED
2017-08-23 09:26:31.927 [DEBUG] [armeria-server-epoll-5-7] c.l.a.internal.Http2GoAwayListener - [id: 0xee49da00, L:/192.168.1.25:8181 - R:/192.168.1.25:40162] HTTP/2 upgrade stream removed: CLOSED
2017-08-23 09:26:31.927 [DEBUG] [armeria-server-epoll-5-2] c.l.a.internal.Http2GoAwayListener - [id: 0x7652431f, L:/192.168.1.25:8181 - R:/192.168.1.25:40157] HTTP/2 upgrade stream removed: CLOSED
2017-08-23 09:26:32.056 [INFO ] [armeria-server-epoll-5-1] armeria.services.rpc - [id: 0xb4672d97, L:/192.168.1.25:8181 - R:/192.168.1.25:40156][h2c://afistest25:8181/rpc/BalanceFreezeService/BalanceFreeze#POST] Request: {startTime=2017-08-23T01:26:31.948Z(1503451591948), length=66B, duration=69053µs(69053619ns), scheme=gproto+h2c, host=afistest25, headers=[:method=POST, :authority=192.168.1.25:8181, :scheme=http, :path=/rpc/BalanceFreezeService/BalanceFreeze, content-type=application/grpc+proto, grpc-accept-encoding=gzip, grpc-timeout=30000000u, user-agent=armeria/0.52.0], content=DefaultRpcRequest{serviceType=GrpcLogUtil, method=BalanceFreezeService/BalanceFreeze, params=[]}}
2017-08-23 09:26:32.056 [INFO ] [armeria-server-epoll-5-7] armeria.services.rpc - [id: 0xee49da00, L:/192.168.1.25:8181 - R:/192.168.1.25:40162][h2c://afistest25:8181/rpc/MarketChargeService/marketCharge#POST] Request: {startTime=2017-08-23T01:26:31.948Z(1503451591948), length=67B, duration=65892µs(65892274ns), scheme=gproto+h2c, host=afistest25, headers=[:method=POST, :authority=192.168.1.25:8181, :scheme=http, :path=/rpc/MarketChargeService/marketCharge, content-type=application/grpc+proto, grpc-accept-encoding=gzip, grpc-timeout=30000000u, user-agent=armeria/0.52.0], content=DefaultRpcRequest{serviceType=GrpcLogUtil, method=MarketChargeService/marketCharge, params=[]}}
2017-08-23 09:26:32.056 [INFO ] [armeria-server-epoll-5-2] armeria.services.rpc - [id: 0x7652431f, L:/192.168.1.25:8181 - R:/192.168.1.25:40157][h2c://afistest25:8181/rpc/MarketChargeService/marketCharge#POST] Request: {startTime=2017-08-23T01:26:31.948Z(1503451591948), length=67B, duration=71103µs(71103886ns), scheme=gproto+h2c, host=afistest25, headers=[:method=POST, :authority=192.168.1.25:8181, :scheme=http, :path=/rpc/MarketChargeService/marketCharge, content-type=application/grpc+proto, grpc-accept-encoding=gzip, grpc-timeout=30000000u, user-agent=armeria/0.52.0], content=DefaultRpcRequest{serviceType=GrpcLogUtil, method=MarketChargeService/marketCharge, params=[]}}
2017-08-23 09:26:32.056 [INFO ] [armeria-server-epoll-5-4] armeria.services.rpc - [id: 0xf4642e1f, L:/192.168.1.25:8181 - R:/192.168.1.25:40159][h2c://afistest25:8181/rpc/MarketChargeService/marketCharge#POST] Request: {startTime=2017-08-23T01:26:31.948Z(1503451591948), length=67B, duration=68835µs(68835603ns), scheme=gproto+h2c, host=afistest25, headers=[:method=POST, :authority=192.168.1.25:8181, :scheme=http, :path=/rpc/MarketChargeService/marketCharge, content-type=application/grpc+proto, grpc-accept-encoding=gzip, grpc-timeout=30000000u, user-agent=armeria/0.52.0], content=DefaultRpcRequest{serviceType=GrpcLogUtil, method=MarketChargeService/marketCharge, params=[]}}
2017-08-23 09:26:32.056 [INFO ] [armeria-server-epoll-5-8] armeria.services.rpc - [id: 0x128b3bf1, L:/192.168.1.25:8181 - R:/192.168.1.25:40163][h2c://afistest25:8181/rpc/BalanceFreezeService/BalanceFreeze#POST] Request: {startTime=2017-08-23T01:26:31.948Z(1503451591948), length=67B, duration=63811µs(63811621ns), scheme=gproto+h2c, host=afistest25, headers=[:method=POST, :authority=192.168.1.25:8181, :scheme=http, :path=/rpc/BalanceFreezeService/BalanceFreeze, content-type=application/grpc+proto, grpc-accept-encoding=gzip, grpc-timeout=30000000u, user-agent=armeria/0.52.0], content=DefaultRpcRequest{serviceType=GrpcLogUtil, method=BalanceFreezeService/BalanceFreeze, params=[]}}
2017-08-23 09:26:32.056 [INFO ] [armeria-server-epoll-5-10] armeria.services.rpc - [id: 0xc6457a94, L:/192.168.1.25:8181 - R:/192.168.1.25:40165][h2c://afistest25:8181/rpc/BalanceFreezeService/BalanceFreeze#POST] Request: {startTime=2017-08-23T01:26:31.948Z(1503451591948), length=68B, duration=66461µs(66461073ns), scheme=gproto+h2c, host=afistest25, headers=[:method=POST, :authority=192.168.1.25:8181, :scheme=http, :path=/rpc/BalanceFreezeService/BalanceFreeze, content-type=application/grpc+proto, grpc-accept-encoding=gzip, grpc-timeout=30000000u, user-agent=armeria/0.52.0], content=DefaultRpcRequest{serviceType=GrpcLogUtil, method=BalanceFreezeService/BalanceFreeze, params=[]}}
2017-08-23 09:26:32.056 [INFO ] [armeria-server-epoll-5-6] armeria.services.rpc - [id: 0xe765d8de, L:/192.168.1.25:8181 - R:/192.168.1.25:40161][h2c://afistest25:8181/rpc/BalanceFreezeService/BalanceFreeze#POST] Request: {startTime=2017-08-23T01:26:31.948Z(1503451591948), length=68B, duration=68037µs(68037037ns), scheme=gproto+h2c, host=afistest25, headers=[:method=POST, :authority=192.168.1.25:8181, :scheme=http, :path=/rpc/BalanceFreezeService/BalanceFreeze, content-type=application/grpc+proto, grpc-accept-encoding=gzip, grpc-timeout=30000000u, user-agent=armeria/0.52.0], content=DefaultRpcRequest{serviceType=GrpcLogUtil, method=BalanceFreezeService/BalanceFreeze, params=[]}}
2017-08-23 09:26:32.056 [INFO ] [armeria-server-epoll-5-3] armeria.services.rpc - [id: 0x4f5bac9c, L:/192.168.1.25:8181 - R:/192.168.1.25:40158][h2c://afistest25:8181/rpc/MarketChargeService/marketCharge#POST] Request: {startTime=2017-08-23T01:26:31.948Z(1503451591948), length=67B, duration=64857µs(64857458ns), scheme=gproto+h2c, host=afistest25, headers=[:method=POST, :authority=192.168.1.25:8181, :scheme=http, :path=/rpc/MarketChargeService/marketCharge, content-type=application/grpc+proto, grpc-accept-encoding=gzip, grpc-timeout=30000000u, user-agent=armeria/0.52.0], content=DefaultRpcRequest{serviceType=GrpcLogUtil, method=MarketChargeService/marketCharge, params=[]}}
2017-08-23 09:26:32.056 [INFO ] [armeria-server-epoll-5-9] armeria.services.rpc - [id: 0x75360336, L:/192.168.1.25:8181 - R:/192.168.1.25:40164][h2c://afistest25:8181/rpc/MarketChargeService/marketCharge#POST] Request: {startTime=2017-08-23T01:26:31.948Z(1503451591948), length=67B, duration=65194µs(65194608ns), scheme=gproto+h2c, host=afistest25, headers=[:method=POST, :authority=192.168.1.25:8181, :scheme=http, :path=/rpc/MarketChargeService/marketCharge, content-type=application/grpc+proto, grpc-accept-encoding=gzip, grpc-timeout=30000000u, user-agent=armeria/0.52.0], content=DefaultRpcRequest{serviceType=GrpcLogUtil, method=MarketChargeService/marketCharge, params=[]}}
2017-08-23 09:26:32.056 [INFO ] [armeria-server-epoll-5-5] armeria.services.rpc - [id: 0x58e3169b, L:/192.168.1.25:8181 - R:/192.168.1.25:40160][h2c://afistest25:8181/rpc/MarketChargeService/marketCharge#POST] Request: {startTime=2017-08-23T01:26:31.948Z(1503451591948), length=67B, duration=64189µs(64189296ns), scheme=gproto+h2c, host=afistest25, headers=[:method=POST, :authority=192.168.1.25:8181, :scheme=http, :path=/rpc/MarketChargeService/marketCharge, content-type=application/grpc+proto, grpc-accept-encoding=gzip, grpc-timeout=30000000u, user-agent=armeria/0.52.0], content=DefaultRpcRequest{serviceType=GrpcLogUtil, method=MarketChargeService/marketCharge, params=[]}}
2017-08-23 09:26:32.088 [DEBUG] [armeria-blocking-tasks-1-3] org.apache.ibatis.logging.LogFactory - Logging initialized using 'class org.apache.ibatis.logging.slf4j.Slf4jImpl' adapter.
2017-08-23 09:26:32.442 [DEBUG] [armeria-blocking-tasks-1-3] o.a.i.d.pooled.PooledDataSource - PooledDataSource forcefully closed/removed all connections.
2017-08-23 09:26:32.442 [DEBUG] [armeria-blocking-tasks-1-3] o.a.i.d.pooled.PooledDataSource - PooledDataSource forcefully closed/removed all connections.
2017-08-23 09:26:32.442 [DEBUG] [armeria-blocking-tasks-1-3] o.a.i.d.pooled.PooledDataSource - PooledDataSource forcefully closed/removed all connections.
2017-08-23 09:26:32.442 [DEBUG] [armeria-blocking-tasks-1-3] o.a.i.d.pooled.PooledDataSource - PooledDataSource forcefully closed/removed all connections.
2017-08-23 09:26:33.171 [DEBUG] [armeria-blocking-tasks-1-8] o.a.i.t.jdbc.JdbcTransaction - Opening JDBC Connection
2017-08-23 09:26:33.171 [DEBUG] [armeria-blocking-tasks-1-9] o.a.i.t.jdbc.JdbcTransaction - Opening JDBC Connection
2017-08-23 09:26:33.171 [DEBUG] [armeria-blocking-tasks-1-5] o.a.i.t.jdbc.JdbcTransaction - Opening JDBC Connection
2017-08-23 09:26:33.171 [DEBUG] [armeria-blocking-tasks-1-2] o.a.i.t.jdbc.JdbcTransaction - Opening JDBC Connection
2017-08-23 09:26:33.171 [DEBUG] [armeria-blocking-tasks-1-7] o.a.i.t.jdbc.JdbcTransaction - Opening JDBC Connection
2017-08-23 09:26:33.171 [DEBUG] [armeria-blocking-tasks-1-1] o.a.i.t.jdbc.JdbcTransaction - Opening JDBC Connection
2017-08-23 09:26:33.171 [DEBUG] [armeria-blocking-tasks-1-6] o.a.i.t.jdbc.JdbcTransaction - Opening JDBC Connection
2017-08-23 09:26:33.171 [DEBUG] [armeria-blocking-tasks-1-3] o.a.i.t.jdbc.JdbcTransaction - Opening JDBC Connection
2017-08-23 09:26:33.171 [DEBUG] [armeria-blocking-tasks-1-4] o.a.i.t.jdbc.JdbcTransaction - Opening JDBC Connection
**2017-08-23 09:26:33.180 [INFO ] [armeria-server-epoll-5-1] armeria.services.rpc - [id: 0xb4672d97, L:/192.168.1.25:8181 - R:/192.168.1.25:40156][h2c://afistest25:8181/rpc/BalanceFreezeService/BalanceFreeze#POST] Response: {startTime=2017-08-23T01:26:33.170Z(1503451593170), length=0B, duration=9471µs(9471389ns), headers=[:status=200, content-type=application/grpc+proto, grpc-status=0], content=DefaultRpcResponse{success}}**

**Comment by minwoox** [comment]
@anuraaga  might help you, but could you provide us a test case which reproduces the situation?

**Comment by anuraaga** [comment]
A test case would be nice. Looking at the log, all I can say is it seems to happen just after your DB connection pool was restarted for some reason. Do you think it's possible an exception was thrown and caught in a way that `onComplete()` was called without calling `onNext()` on the server?

**Comment by trustin** [comment]
Thanks, @anuraaga for looking into this.

**Comment by sunning9001** [comment]
Thanks,@minwoox @anuraaga @trustin  

it is very strange.I've done a lot of data simulation on the original environment,But none of the above shows up.

@anuraaga  You may be right.  I agree with what you said .   I only  catch InterruptedException,ExecutionException,TimeoutException.

**Comment by trustin** [comment]
@sunning9001 OK to close this issue?
