### ISSUE TITLE
Unexpected http methods are not handled correctly

### ISSUE THREAD

**Issue by krrrr38** [line/armeria#754]
I guess it should be return 405 with correct error handling or http method implementation.

w/armeria 0.52.0

```
19:28:34.564 WARN [armeria-common-worker-epoll-7-19] c.linecorp.armeria.server.Http1RequestDecoder:188 - Unexpected exception: 
java.lang.IllegalArgumentException: No enum constant com.linecorp.armeria.common.HttpMethod.RDSZ
at java.lang.Enum.valueOf(Enum.java:238)
at com.linecorp.armeria.common.HttpMethod.valueOf(HttpMethod.java:36)
at com.linecorp.armeria.internal.ArmeriaHttpUtil.toArmeria(ArmeriaHttpUtil.java:341)
at com.linecorp.armeria.server.Http1RequestDecoder.channelRead(Http1RequestDecoder.java:131)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
...
```

netty HttpMethod class handles any http methods, but armeria HttpMethod is enum.

https://github.com/line/armeria/blob/41059e7295ef16e7835b135c5c6174c3d6033605/core/src/main/java/com/linecorp/armeria/internal/ArmeriaHttpUtil.java#L343

**Comment by trustin** [comment]
Thanks for reporting. Should be fixed.

**Comment by trustin** [comment]
Please feel free to let us know if you are interested in sending a fix PR.
