### ISSUE TITLE
Failed to handle request by logging listener error

### ISSUE THREAD

**Issue by imasahiro** [line/armeria#793]
When I upgrade armeria to 0.54.0, maybe because it has some bug on metrics collection, it causes thrift handler failure.

```
2017-10-24 11:06:04.129  WARN 66691 --- [armeria-common-worker-epoll-3-29] c.l.a.c.l.RequestLogListenerInvoker      : onRequestLog() failed with an exception:
java.lang.ArrayIndexOutOfBoundsException: 500
    at io.micrometer.core.instrument.stats.quantile.CKMSQuantiles.observe(CKMSQuantiles.java:81)
    at io.micrometer.core.instrument.prometheus.internal.CustomPrometheusSummary$Child.observe(CustomPrometheusSummary.java:132)
    at io.micrometer.core.instrument.prometheus.PrometheusTimer.record(PrometheusTimer.java:40)
    at com.linecorp.armeria.internal.metric.micrometer.ConcurrentCompositeTimer.lambda$record$0(ConcurrentCompositeTimer.java:67)
    at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
    at com.linecorp.armeria.internal.metric.micrometer.ConcurrentCompositeTimer.record(ConcurrentCompositeTimer.java:67)
    at com.linecorp.armeria.internal.metric.RequestMetricSupport.onResponse(RequestMetricSupport.java:93)
    at com.linecorp.armeria.common.logging.RequestLogListenerInvoker.invokeOnRequestLog(RequestLogListenerInvoker.java:39)
    at com.linecorp.armeria.common.logging.DefaultRequestLog.notifyListeners(DefaultRequestLog.java:607)
    at com.linecorp.armeria.common.logging.DefaultRequestLog.updateAvailability(DefaultRequestLog.java:565)
    at com.linecorp.armeria.common.logging.DefaultRequestLog.updateAvailability(DefaultRequestLog.java:552)
    at com.linecorp.armeria.common.logging.DefaultRequestLog.responseContent(DefaultRequestLog.java:500)
    at com.linecorp.armeria.client.thrift.THttpClientDelegate.handleSuccess(THttpClientDelegate.java:252)
    at com.linecorp.armeria.client.thrift.THttpClientDelegate.handle(THttpClientDelegate.java:219)
    at com.linecorp.armeria.client.thrift.THttpClientDelegate.lambda$execute$0(THttpClientDelegate.java:144)
    at com.linecorp.armeria.common.util.Functions.lambda$voidFunction$1(Functions.java:192)
    at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
    at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
    at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
    at com.linecorp.armeria.common.HttpMessageAggregator.accept(HttpMessageAggregator.java:120)
    at com.linecorp.armeria.common.HttpMessageAggregator.accept(HttpMessageAggregator.java:29)
    at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
    at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
    at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
    at com.linecorp.armeria.common.stream.DefaultStreamMessage$CloseEvent.notifySubscriber(DefaultStreamMessage.java:633)
    at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberWithCloseEvent(DefaultStreamMessage.java:403)
    at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:317)
    at com.linecorp.armeria.common.stream.DefaultStreamMessage.lambda$notifySubscriber$2(DefaultStreamMessage.java:298)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by trustin** [comment]
Filed an upstream issue: https://github.com/micrometer-metrics/micrometer/issues/172
