### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: index out of covered value range

### ISSUE THREAD

**Issue by trustin** [line/armeria#809]
Probably not a flaky test:
```
RollingHdrQuantilesTest.testThatConcurrentThreadsNotHungWithThreeChunks: FAILURE

com.linecorp.armeria.common.metric.RollingHdrQuantilesTest > testThatConcurrentThreadsNotHungWithThreeChunks FAILED
    java.lang.ArrayIndexOutOfBoundsException: index out of covered value range
        at org.HdrHistogram.AbstractHistogram.normalizeIndex(AbstractHistogram.java:2281)
        at org.HdrHistogram.ConcurrentHistogram.recordConvertedDoubleValueWithCount(ConcurrentHistogram.java:185)
        at org.HdrHistogram.DoubleHistogram.recordCountAtValue(DoubleHistogram.java:340)
        at org.HdrHistogram.DoubleHistogram.recordValueWithCountAndExpectedInterval(DoubleHistogram.java:356)
        at org.HdrHistogram.DoubleHistogram.recordValueWithExpectedInterval(DoubleHistogram.java:330)
        at org.HdrHistogram.DoubleRecorder.recordValueWithExpectedInterval(DoubleRecorder.java:118)
        at com.linecorp.armeria.common.metric.RollingHdrQuantiles.observe(RollingHdrQuantiles.java:114)
        at com.linecorp.armeria.common.metric.RollingHdrQuantiles.observe(RollingHdrQuantiles.java:107)
        at com.linecorp.armeria.common.metric.RollingHdrQuantilesTest.lambda$runInParallel$2(RollingHdrQuantilesTest.java:149)
```

**Comment by minwoox** [comment]
Another? -.-;
