### ISSUE TITLE
Flaky test: ZooKeeperRegistrationTest.testConnectionRecovery

### ISSUE THREAD

**Issue by trustin** [line/armeria#838]
```
ZooKeeperRegistrationTest.testConnectionRecovery: FAILURE
---------------------------------------------------------
09:51:56.248 [Test worker-EventThread] ERROR org.apache.zookeeper.ClientCnxn - Caught unexpected throwable
com.linecorp.armeria.common.zookeeper.ZooKeeperException: Failed to notify ZooKeeper listener
	at com.linecorp.armeria.common.zookeeper.ZooKeeperConnector.notifyChange(ZooKeeperConnector.java:186)
	at com.linecorp.armeria.common.zookeeper.ZooKeeperConnector.access$600(ZooKeeperConnector.java:48)
	at com.linecorp.armeria.common.zookeeper.ZooKeeperConnector$ZkWatcher.processResult(ZooKeeperConnector.java:266)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:554)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:505)
Caused by: com.linecorp.armeria.common.zookeeper.ZooKeeperException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /testEndPoints/127.0.0.1_61351
	at com.linecorp.armeria.common.zookeeper.ZooKeeperConnector.lambda$notifyChange$0(ZooKeeperConnector.java:177)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.linecorp.armeria.common.zookeeper.ZooKeeperConnector.notifyChange(ZooKeeperConnector.java:171)
	... 4 common frames omitted
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /testEndPoints/127.0.0.1_61351
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:111)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1212)
	at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1241)
	at com.linecorp.armeria.common.zookeeper.ZooKeeperConnector.lambda$notifyChange$0(ZooKeeperConnector.java:174)
	... 6 common frames omitted
09:51:58.107 [Test worker-SendThread(127.0.0.1:43207)] WARN  org.apache.zookeeper.ClientCnxn - Unable to reconnect to ZooKeeper service, session 0x15fc43dd6170009 has expired
com.linecorp.armeria.server.zookeeper.ZooKeeperRegistrationTest > testConnectionRecovery FAILED
    java.lang.AssertionError: 
    Expecting:
     <0>
    to be greater than:
     <0> 
        at com.linecorp.armeria.server.zookeeper.ZooKeeperRegistrationTest.testConnectionRecovery(ZooKeeperRegistrationTest.java:149)
```

**Comment by trustin** [comment]
Seems like a bug in `ZooKeeperConnector` actually. See #839 instead.
