### ISSUE TITLE
NoSuchElementException from DefaultStreamMessage

### ISSUE THREAD

**Issue by trustin** [line/armeria#853]
Possibly due to #848 or #836?

```
com.linecorp.armeria.client.retry.RetryingHttpClientTest > differentBackoffBasedOnStatus FAILED
    java.util.concurrent.CompletionException: java.util.NoSuchElementException
        at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
        at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
        at com.linecorp.armeria.client.retry.RetryingHttpClientTest.differentBackoffBasedOnStatus(RetryingHttpClientTest.java:490)
        Caused by:
        java.util.NoSuchElementException
            at java.util.AbstractQueue.remove(AbstractQueue.java:117)
            at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberWithElements(DefaultStreamMessage.java:384)
            at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:367)
            at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:298)
            at com.linecorp.armeria.common.stream.DefaultStreamMessage$SubscriptionImpl.request(DefaultStreamMessage.java:580)
            at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$StreamMessageProcessor.requestDemand(AbstractStreamMessageDuplicator.java:321)
            at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$DownstreamSubscription.request(AbstractStreamMessageDuplicator.java:576)
            at com.linecorp.armeria.internal.HttpHeaderSubscriber.onSubscribe(HttpHeaderSubscriber.java:56)
            at com.linecorp.armeria.common.stream.FilteredStreamMessage$FilteringSubscriber.onSubscribe(FilteredStreamMessage.java:129)
            at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$DownstreamSubscription.invokeOnSubscribe(AbstractStreamMessageDuplicator.java:558)
            at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$StreamMessageProcessor.subscribe(AbstractStreamMessageDuplicator.java:272)
            at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$ChildStreamMessage.subscribe0(AbstractStreamMessageDuplicator.java:437)
            at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$ChildStreamMessage.subscribe(AbstractStreamMessageDuplicator.java:409)
            at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$ChildStreamMessage.subscribe(AbstractStreamMessageDuplicator.java:403)
            at com.linecorp.armeria.common.stream.StreamMessageWrapper.subscribe(StreamMessageWrapper.java:68)
            at com.linecorp.armeria.common.stream.FilteredStreamMessage.subscribe(FilteredStreamMessage.java:89)
            at com.linecorp.armeria.client.retry.HttpStatusBasedRetryStrategy.shouldRetry(HttpStatusBasedRetryStrategy.java:52)
            at com.linecorp.armeria.client.retry.HttpStatusBasedRetryStrategy.shouldRetry(HttpStatusBasedRetryStrategy.java:35)
            at com.linecorp.armeria.client.retry.RetryingHttpClient.doExecute0(RetryingHttpClient.java:132)
            at com.linecorp.armeria.client.retry.RetryingHttpClient.doExecute(RetryingHttpClient.java:116)
            at com.linecorp.armeria.client.retry.RetryingHttpClient.doExecute(RetryingHttpClient.java:52)
            at com.linecorp.armeria.client.retry.RetryingClient.execute(RetryingClient.java:69)
            at com.linecorp.armeria.client.UserClient.execute(UserClient.java:160)
            at com.linecorp.armeria.client.DefaultHttpClient.execute(DefaultHttpClient.java:55)
            at com.linecorp.armeria.client.DefaultHttpClient.execute(DefaultHttpClient.java:68)
            at com.linecorp.armeria.client.DefaultHttpClient.execute(DefaultHttpClient.java:64)
            at com.linecorp.armeria.client.HttpClient.execute(HttpClient.java:156)
            at com.linecorp.armeria.client.HttpClient.get(HttpClient.java:198)
            ... 1 more
```

**Comment by minwoox** [comment]
Oops~ will check it~!

**Comment by trustin** [comment]
`DefaultStreamMessage.notifySubscriber()` can be invoked by more than one threads at the same time when a `Subscriber` subscribed without an `Executor` and stream elements are written by multiple threads, because we do not have any locking mechanism for multiple writers.

This race condition can also occur when the `Executor` specified by a user is not single-threaded, because a `Subscriber` can write to the `DefaultStreamMessage` it's subscribed to although it's not very usual.

We should note that we currently violate the section 1.3 of the Reactive Streams specification, too:

> `onSubscribe`, `onNext`, `onError` and `onComplete` signaled to a `Subscriber` MUST be signaled in a thread-safe manner—and if performed by multiple threads—use external synchronization.

The simplest solution to this problem is to:

- choose one of the `EventLoop`s in `CommonPools.workerGroup()` when `subscribe()` did not specify an `Executor`
- and require `EventLoop` instead of `Executor`.

More complicated non-breaking change would be to use locks, but I don't think it's a good idea.

Thoughts?

/cc @anuraaga

**Comment by anuraaga** [comment]
Just wondering, is there also an issue where the retrying client should have specified the Executor but didn't? It'd probably be the quicker fix if there is.


I was thinking about the default `Executor` problem myself too, including using one from the `CommonPools.workerGroup` - it seems to make sense to me.

By the way, I'm almost done with `EventLoopStreamMessage` which does actually serialize absolutely everything through an event loop so I guess doesn't have this issue. As expected, it's much slower than `DefaultStreamMessage` when the writer and reader threads differ, but assuming that's not supposed to happen much, maybe we can replace `DefaultStreamMessage` completely?

READ_WRITE is when both reader and writer are the event loop, READ_ONLY is when only reader is the event loop, etc.
```
Benchmark                          (eventLoopType)  (flowControl)  (num)            (streamType)   Mode  Cnt      Score     Error  Units
StreamMessageBenchmark.writeFirst       READ_WRITE          false   1000  DEFAULT_STREAM_MESSAGE  thrpt   20  12044.017 ± 288.413  ops/s
StreamMessageBenchmark.writeFirst       READ_WRITE          false   1000      EVENT_LOOP_MESSAGE  thrpt   20  19162.500 ± 425.940  ops/s
StreamMessageBenchmark.writeFirst       READ_WRITE           true   1000  DEFAULT_STREAM_MESSAGE  thrpt   20   9927.459 ± 162.440  ops/s
StreamMessageBenchmark.writeFirst       READ_WRITE           true   1000      EVENT_LOOP_MESSAGE  thrpt   20  16152.675 ± 471.307  ops/s
StreamMessageBenchmark.writeFirst        READ_ONLY          false   1000  DEFAULT_STREAM_MESSAGE  thrpt   20  11740.113 ± 313.403  ops/s
StreamMessageBenchmark.writeFirst        READ_ONLY          false   1000      EVENT_LOOP_MESSAGE  thrpt   20   4227.644 ± 280.026  ops/s
StreamMessageBenchmark.writeFirst        READ_ONLY           true   1000  DEFAULT_STREAM_MESSAGE  thrpt   20   9206.425 ± 506.174  ops/s
StreamMessageBenchmark.writeFirst        READ_ONLY           true   1000      EVENT_LOOP_MESSAGE  thrpt   20   4241.079 ± 292.585  ops/s
StreamMessageBenchmark.writeFirst       WRITE_ONLY          false   1000  DEFAULT_STREAM_MESSAGE  thrpt   20  11331.690 ± 936.254  ops/s
StreamMessageBenchmark.writeFirst       WRITE_ONLY          false   1000      EVENT_LOOP_MESSAGE  thrpt   20   3926.905 ± 268.320  ops/s
StreamMessageBenchmark.writeFirst       WRITE_ONLY           true   1000  DEFAULT_STREAM_MESSAGE  thrpt   20   9446.406 ± 616.502  ops/s
StreamMessageBenchmark.writeFirst       WRITE_ONLY           true   1000      EVENT_LOOP_MESSAGE  thrpt   20    239.676 ±  36.376  ops/s
StreamMessageBenchmark.writeFirst             NONE          false   1000  DEFAULT_STREAM_MESSAGE  thrpt   20  11548.984 ± 639.254  ops/s
StreamMessageBenchmark.writeFirst             NONE          false   1000      EVENT_LOOP_MESSAGE  thrpt   20   2399.476 ± 171.868  ops/s
StreamMessageBenchmark.writeFirst             NONE           true   1000  DEFAULT_STREAM_MESSAGE  thrpt   20   9258.161 ± 657.501  ops/s
StreamMessageBenchmark.writeFirst             NONE           true   1000      EVENT_LOOP_MESSAGE  thrpt   20    235.476 ±  16.359  ops/s
StreamMessageBenchmark.writeLast        READ_WRITE          false   1000  DEFAULT_STREAM_MESSAGE  thrpt   20  11125.725 ± 262.078  ops/s
StreamMessageBenchmark.writeLast        READ_WRITE          false   1000      EVENT_LOOP_MESSAGE  thrpt   20  25426.484 ± 708.844  ops/s
StreamMessageBenchmark.writeLast        READ_WRITE           true   1000  DEFAULT_STREAM_MESSAGE  thrpt   20   9978.121 ± 462.633  ops/s
StreamMessageBenchmark.writeLast        READ_WRITE           true   1000      EVENT_LOOP_MESSAGE  thrpt   20  20033.420 ± 557.617  ops/s
StreamMessageBenchmark.writeLast         READ_ONLY          false   1000  DEFAULT_STREAM_MESSAGE  thrpt   20   3885.780 ± 159.991  ops/s
StreamMessageBenchmark.writeLast         READ_ONLY          false   1000      EVENT_LOOP_MESSAGE  thrpt   20   5401.878 ± 310.098  ops/s
StreamMessageBenchmark.writeLast         READ_ONLY           true   1000  DEFAULT_STREAM_MESSAGE  thrpt   20   4256.135 ± 259.570  ops/s
StreamMessageBenchmark.writeLast         READ_ONLY           true   1000      EVENT_LOOP_MESSAGE  thrpt   20   4826.192 ± 164.817  ops/s
StreamMessageBenchmark.writeLast        WRITE_ONLY          false   1000  DEFAULT_STREAM_MESSAGE  thrpt   20   4464.657 ± 289.032  ops/s
StreamMessageBenchmark.writeLast        WRITE_ONLY          false   1000      EVENT_LOOP_MESSAGE  thrpt   20   4121.658 ±  91.915  ops/s
StreamMessageBenchmark.writeLast        WRITE_ONLY           true   1000  DEFAULT_STREAM_MESSAGE  thrpt   20   3889.335 ± 352.466  ops/s
StreamMessageBenchmark.writeLast        WRITE_ONLY           true   1000      EVENT_LOOP_MESSAGE  thrpt   20    258.229 ±  14.023  ops/s
StreamMessageBenchmark.writeLast              NONE          false   1000  DEFAULT_STREAM_MESSAGE  thrpt   20   3947.588 ± 225.759  ops/s
StreamMessageBenchmark.writeLast              NONE          false   1000      EVENT_LOOP_MESSAGE  thrpt   20   3073.582 ±  39.918  ops/s
StreamMessageBenchmark.writeLast              NONE           true   1000  DEFAULT_STREAM_MESSAGE  thrpt   20   3981.429 ± 202.925  ops/s
StreamMessageBenchmark.writeLast              NONE           true   1000      EVENT_LOOP_MESSAGE  thrpt   20    234.538 ±  14.652  ops/s
StreamMessageBenchmark.writeOnDemand       READ_WRITE          false   1000  DEFAULT_STREAM_MESSAGE  thrpt   20  3575.318 ± 105.687  ops/s
StreamMessageBenchmark.writeOnDemand       READ_WRITE          false   1000      EVENT_LOOP_MESSAGE  thrpt   20  4917.236 ± 166.525  ops/s
StreamMessageBenchmark.writeOnDemand       READ_WRITE           true   1000  DEFAULT_STREAM_MESSAGE  thrpt   20  3447.410 ±  86.308  ops/s
StreamMessageBenchmark.writeOnDemand       READ_WRITE           true   1000      EVENT_LOOP_MESSAGE  thrpt   20  4937.906 ± 133.443  ops/s
StreamMessageBenchmark.writeOnDemand        READ_ONLY          false   1000  DEFAULT_STREAM_MESSAGE  thrpt   20   255.636 ±  15.810  ops/s
StreamMessageBenchmark.writeOnDemand        READ_ONLY          false   1000      EVENT_LOOP_MESSAGE  thrpt   20   250.063 ±   9.808  ops/s
StreamMessageBenchmark.writeOnDemand        READ_ONLY           true   1000  DEFAULT_STREAM_MESSAGE  thrpt   20   249.861 ±  11.486  ops/s
StreamMessageBenchmark.writeOnDemand        READ_ONLY           true   1000      EVENT_LOOP_MESSAGE  thrpt   20   250.271 ±   7.779  ops/s
StreamMessageBenchmark.writeOnDemand       WRITE_ONLY          false   1000  DEFAULT_STREAM_MESSAGE  thrpt   20   253.745 ±  13.701  ops/s
StreamMessageBenchmark.writeOnDemand       WRITE_ONLY          false   1000      EVENT_LOOP_MESSAGE  thrpt   20  1865.055 ±  91.483  ops/s
StreamMessageBenchmark.writeOnDemand       WRITE_ONLY           true   1000  DEFAULT_STREAM_MESSAGE  thrpt   20   244.939 ±  10.902  ops/s
StreamMessageBenchmark.writeOnDemand       WRITE_ONLY           true   1000      EVENT_LOOP_MESSAGE  thrpt   20   235.658 ±   9.051  ops/s
StreamMessageBenchmark.writeOnDemand             NONE          false   1000  DEFAULT_STREAM_MESSAGE  thrpt   20   244.169 ±  12.363  ops/s
StreamMessageBenchmark.writeOnDemand             NONE          false   1000      EVENT_LOOP_MESSAGE  thrpt   20   179.424 ±  14.112  ops/s
StreamMessageBenchmark.writeOnDemand             NONE           true   1000  DEFAULT_STREAM_MESSAGE  thrpt   20   250.204 ±  15.314  ops/s
StreamMessageBenchmark.writeOnDemand             NONE           true   1000      EVENT_LOOP_MESSAGE  thrpt   20   114.351 ±   6.559  ops/s
```

**Comment by trustin** [comment]
> By the way, I'm almost done with `EventLoopStreamMessage` which does actually serialize absolutely everything through an event loop so I guess doesn't have this issue. As expected, it's much slower than `DefaultStreamMessage` when the writer and reader threads differ, but assuming that's not supposed to happen much, maybe we can replace `DefaultStreamMessage` completely?

Sounds good to me, given it performs great on READ_WRITE and OK on READ/WRITE_ONLY, which are vast majority of use cases. Curious about what other folks think. Comments?

**Comment by minwoox** [comment]
will send a PR soon to fix DefaultStreamMessage
