### ISSUE TITLE
Investigate ZooKeeperRegistrationTest.testConnectionRecovery failure

### ISSUE THREAD

**Issue by trustin** [line/armeria#881]
https://travis-ci.org/line/armeria/builds/308873600

```
ZooKeeperRegistrationTest.testConnectionRecovery: FAILURE
---------------------------------------------------------
09:45:26.470 [Test worker-EventThread] ERROR org.apache.zookeeper.ClientCnxn - Caught unexpected throwable
com.linecorp.armeria.common.zookeeper.ZooKeeperException: Failed to notify ZooKeeper listener
	at com.linecorp.armeria.common.zookeeper.ZooKeeperConnector.notifyChange(ZooKeeperConnector.java:192)
	at com.linecorp.armeria.common.zookeeper.ZooKeeperConnector.access$600(ZooKeeperConnector.java:49)
	at com.linecorp.armeria.common.zookeeper.ZooKeeperConnector$ZkWatcher.processResult(ZooKeeperConnector.java:272)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:555)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:506)
Caused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /testEndPoints
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1535)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1563)
	at com.linecorp.armeria.common.zookeeper.ZooKeeperConnector.notifyChange(ZooKeeperConnector.java:160)
	... 4 common frames omitted
09:45:28.182 [Test worker-SendThread(127.0.0.1:33675)] WARN  org.apache.zookeeper.ClientCnxn - Unable to reconnect to ZooKeeper service, session 0x100029b12de0009 has expired
09:45:38.627 [Test worker-SendThread(127.0.0.1:33675)] WARN  org.apache.zookeeper.ClientCnxn - Client session timed out, have not heard from server in 6666ms for sessionid 0x100029b12de000a
09:45:38.627 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:0] WARN  o.a.zookeeper.server.NIOServerCnxn - Unable to read additional data from client sessionid 0x100029b12de000a, likely client has closed socket
09:45:38.628 [Test worker-SendThread(127.0.0.1:33675)] WARN  org.apache.zookeeper.ClientCnxn - Client session timed out, have not heard from server in 6667ms for sessionid 0x100029b12de000b
09:45:38.628 [Test worker-SendThread(127.0.0.1:33675)] WARN  org.apache.zookeeper.ClientCnxn - Client session timed out, have not heard from server in 6668ms for sessionid 0x100029b12de000c
09:45:38.628 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:0] WARN  o.a.zookeeper.server.NIOServerCnxn - Unable to read additional data from client sessionid 0x100029b12de000c, likely client has closed socket
09:45:38.629 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:0] WARN  o.a.zookeeper.server.NIOServerCnxn - Unable to read additional data from client sessionid 0x100029b12de000b, likely client has closed socket
09:45:39.914 [SyncThread:0] WARN  o.a.z.server.persistence.FileTxnLog - fsync-ing the write ahead log in SyncThread:0 took 7003ms which will adversely effect operation latency. See the ZooKeeper troubleshooting guide
com.linecorp.armeria.server.zookeeper.ZooKeeperRegistrationTest > testConnectionRecovery FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 10000 milliseconds
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
        at javascalautils.concurrent.FutureImpl.ready(FutureImpl.java:244)
        at javascalautils.concurrent.FutureImpl.result(FutureImpl.java:228)
        at javascalautils.concurrent.Future.result(Future.java:395)
        at zookeeperjunit.CloseableZooKeeper.blockingConnect(CloseableZooKeeper.java:82)
        at zookeeperjunit.ZKInstanceImpl.lambda$null$18(ZKInstanceImpl.java:141)
        at zookeeperjunit.ZKInstanceImpl$$Lambda$19/2079812548.apply(Unknown Source)
        at javascalautils.Try.apply(Try.java:140)
        at javascalautils.TryCompanion.Try(TryCompanion.java:105)
        at zookeeperjunit.ZKInstanceImpl.lambda$connect$19(ZKInstanceImpl.java:141)
        at zookeeperjunit.ZKInstanceImpl$$Lambda$18/2027001369.apply(Unknown Source)
        at javascalautils.Some.lambda$map$23(Some.java:97)
        at javascalautils.Some$$Lambda$16/734860802.apply(Unknown Source)
        at javascalautils.Some.flatMap(Some.java:108)
        at javascalautils.Some.map(Some.java:97)
        at zookeeperjunit.ZKInstanceImpl.connect(ZKInstanceImpl.java:139)
        at zookeeperjunit.ZooKeeperAssert.connection(ZooKeeperAssert.java:64)
        at zookeeperjunit.ZooKeeperAssert.assertExists(ZooKeeperAssert.java:37)
        at com.linecorp.armeria.server.zookeeper.ZooKeeperRegistrationTest.lambda$testServerNodeCreateAndDelete$1(ZooKeeperRegistrationTest.java:88)
        at com.linecorp.armeria.server.zookeeper.ZooKeeperRegistrationTest$$Lambda$148/248109204.accept(Unknown Source)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at com.linecorp.armeria.server.zookeeper.ZooKeeperRegistrationTest.testConnectionRecovery(ZooKeeperRegistrationTest.java:174)
```

**Comment by trustin** [comment]
```
ZooKeeperRegistrationTest.testConnectionRecovery: FAILURE
---------------------------------------------------------
11:38:19.044 [Test worker-EventThread] ERROR org.apache.zookeeper.ClientCnxn - Caught unexpected throwable
com.linecorp.armeria.common.zookeeper.ZooKeeperException: Failed to retrieve the data from: /testEndPoints/127.0.0.1_4004
	at com.linecorp.armeria.common.zookeeper.ZooKeeperConnector.lambda$notifyChange$0(ZooKeeperConnector.java:180)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.linecorp.armeria.common.zookeeper.ZooKeeperConnector.notifyChange(ZooKeeperConnector.java:172)
	at com.linecorp.armeria.common.zookeeper.ZooKeeperConnector.access$600(ZooKeeperConnector.java:49)
	at com.linecorp.armeria.common.zookeeper.ZooKeeperConnector$ZkWatcher.processResult(ZooKeeperConnector.java:272)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:555)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:506)
Caused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /testEndPoints/127.0.0.1_4004
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1215)
	at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1244)
	at com.linecorp.armeria.common.zookeeper.ZooKeeperConnector.lambda$notifyChange$0(ZooKeeperConnector.java:175)
	... 6 common frames omitted
11:38:19.044 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:0] WARN  o.a.zookeeper.server.NIOServerCnxn - Unable to read additional data from client sessionid 0x1000012f578000b, likely client has closed socket
11:38:19.310 [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:0] WARN  o.a.zookeeper.server.NIOServerCnxn - Unable to read additional data from client sessionid 0x1000012f5780009, likely client has closed socket
com.linecorp.armeria.server.zookeeper.ZooKeeperRegistrationTest > testConnectionRecovery FAILED
    java.util.concurrent.CompletionException: java.net.BindException: Address already in use: bind
        at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
        at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
        at com.linecorp.armeria.server.zookeeper.ZooKeeperRegistrationTest.startServers(ZooKeeperRegistrationTest.java:70)
        Caused by:
        java.net.BindException: Address already in use: bind
```

**Comment by trustin** [comment]
Superceded by #882
