### ISSUE TITLE
Performance problem when use armeria as proxy server

### ISSUE THREAD

**Issue by huydx** [line/armeria#897]
# Problem
I used armeria to create very simple proxy server and notice some performance problem when upstream is very slow response server. The proxy server itself is just few lines of code:

```java
    public static void main(String[] args) {
        int workerNumber = 16;
        ClientFactory clientFactory = new ClientFactoryBuilder()
                .workerGroup(EventLoopGroups.newEventLoopGroup(workerNumber), true)
                .build();
        ClientBuilder clientBuilder = new ClientBuilder("none+http://127.0.0.1:9998").factory(clientFactory);
        final HttpClient httpClient = clientBuilder.build(HttpClient.class);

        ServerBuilder sb =  new ServerBuilder().port(20080, SessionProtocol.HTTP).defaultRequestTimeoutMillis(0);
        sb.service("/", (HttpService) (ctx, req) ->
                HttpResponse.from(req.aggregate()
                                     .thenComposeAsync(message -> {
                                         try (SafeCloseable ignored = Clients.withContextCustomizer(clientCtx -> {})) {
                                             return httpClient
                                                     .execute(message.toHttpRequest())
                                                     .aggregate()
                                                     .thenApply(AggregatedHttpMessage::toHttpResponse);
                                         }
                                     })));
        sb.build().start().join();
    }
```

Assume that upstream server has very low response, which I simulate using below golang code:

```golang
package main

import (
	"fmt"
	"net/http"
	"time"
)

func handler(w http.ResponseWriter, r *http.Request) {
	time.Sleep(time.Duration(2) * time.Second)
	fmt.Fprintf(w, "ok")
}

func main() {
	http.HandleFunc("/", handler)
	http.ListenAndServe(":9998", nil)
}
```

# Some numbers using `ab` tool
 ab -n 1000 -c 100 http://localhost:20080/

Raw result without using proxy

```
Percentage of the requests served within a certain time (ms)
  50%   2016
  66%   2017
  75%   2018
  80%   2019
  90%   2023
  95%   2027
  98%   2031
  99%   2031
 100%   2032 (longest request)
```

### Using 16 thread (*2 core)

```
Percentage of the requests served within a certain time (ms)
  50%   8272
  66%  12015
  75%  12017
  80%  12019
  90%  12022
  95%  14022
  98%  14026
  99%  14028
 100%  14029 (longest request)
```

### Using 100 threads (== number of concurrent request)
Had better result, but 80% still have 2 times compare to upstream

```
Percentage of the requests served within a certain time (ms)
  50%   2013
  66%   2018
  75%   2022
  80%   2031
  90%   4400
  95%   4418
  98%   4424
  99%   4428
 100%   4432 (longest request)
```

### Using 500 threads
Same result with 100 threads

### Using keep-alive of ab
The latecy is just worse with keep-alive (which is strange cc @trustin )
```
 50%  17025
  66%  17026
  75%  17027
  80%  17027
  90%  17029
  95%  17030
  98%  17031
```

**Comment by anuraaga** [comment]
I think the issue might be aggravated by it being an HTTP/1 client with slow responses, I think much of our tuning has focused on HTTP/2

**Comment by imasahiro** [comment]
Adds metrics of server/client and looks something wrong with client/server look?
```
client_total_duration_seconds{method="GET",quantile="0.0",} 1.996488704
client_total_duration_seconds{method="GET",quantile="0.5",} 12.012486655
client_total_duration_seconds{method="GET",quantile="0.75",} 12.079595519
client_total_duration_seconds{method="GET",quantile="0.9",} 14.025752575
client_total_duration_seconds{method="GET",quantile="0.95",} 14.025752575
client_total_duration_seconds{method="GET",quantile="0.98",} 14.025752575
client_total_duration_seconds{method="GET",quantile="0.99",} 14.092861439
client_total_duration_seconds{method="GET",quantile="0.999",} 14.092861439
client_total_duration_seconds{method="GET",quantile="1.0",} 14.092861439

server_total_duration_seconds{hostnamePattern="*",method="GET",pathMapping="exact:/",quantile="0.0",} 2.004877312
server_total_duration_seconds{hostnamePattern="*",method="GET",pathMapping="exact:/",quantile="0.5",} 12.079595519
server_total_duration_seconds{hostnamePattern="*",method="GET",pathMapping="exact:/",quantile="0.75",} 12.079595519
server_total_duration_seconds{hostnamePattern="*",method="GET",pathMapping="exact:/",quantile="0.9",} 14.025752575
server_total_duration_seconds{hostnamePattern="*",method="GET",pathMapping="exact:/",quantile="0.95",} 14.025752575
server_total_duration_seconds{hostnamePattern="*",method="GET",pathMapping="exact:/",quantile="0.98",} 14.092861439
server_total_duration_seconds{hostnamePattern="*",method="GET",pathMapping="exact:/",quantile="0.99",} 14.092861439
server_total_duration_seconds{hostnamePattern="*",method="GET",pathMapping="exact:/",quantile="0.999",} 14.092861439
server_total_duration_seconds{hostnamePattern="*",method="GET",pathMapping="exact:/",quantile="1.0",} 14.092861439
```

**Comment by huydx** [comment]
Some more test result if proxy server is put behind a nginx server with keepalive, the result is quite good

```
Percentage of the requests served within a certain time (ms)
  50%   2020
  66%   2024
  75%   2026
  80%   2028
  90%   2365
  95%   2379
  98%   2388
  99%   2391
 100%   2396 (longest request)
```

I don't know what is different between using nginx keepalive and option -k of `ab`

**Comment by huydx** [comment]
More observation, with client timeout of 20 seconds:

```
 ClientFactory clientFactory = new ClientFactoryBuilder()
                .workerGroup(EventLoopGroups.newEventLoopGroup(100), true)
                .connectTimeout(Duration.ofSeconds(20))
```

I've test with delay simuation of 10 seconds and see a lot of armeria `ResponseTimeoutException`, I wonder that,  if upstream server is delay for too long, or has very slow response, is that may cause miscalculation of response time out? In another word, how timeout is calculate right now, is that from the timing that the request is queued, or when the request actually be sent to upstream server?

**Comment by trustin** [comment]
> I've test with upstream server which has delay simulation of 10 seconds and see a lot of armeria ResponseTimeoutException.

You need to set `defaultResponseTimeout(Duration.ofSeconds(20))`.

**Comment by huydx** [comment]
More observation, below weird exception sometimes occur:

```
07-12-2017 13:29:22.831 [armeria-eventloop-nio-6-387] WARN  c.l.a.client.HttpSessionHandler.logIfUnexpected - [id: 0x185ead18, L:/127.0.0.1:60340 - R:/127.0.0.1:9998][h1c] Unexpected exception:
java.lang.NullPointerException: null
	at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$SignalQueue.addAndRemoveIfRequested(AbstractStreamMessageDuplicator.java:810)
	at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$StreamMessageProcessor.pushSignal(AbstractStreamMessageDuplicator.java:262)
	at com.linecorp.armeria.common.stream.AbstractStreamMessageDuplicator$StreamMessageProcessor.onNext(AbstractStreamMessageDuplicator.java:228)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberWithElements(DefaultStreamMessage.java:342)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:320)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:250)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:236)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.addObject(DefaultStreamMessage.java:148)
	at com.linecorp.armeria.common.stream.AbstractStreamMessageAndWriter.write(AbstractStreamMessageAndWriter.java:74)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.write(DefaultStreamMessage.java:64)
	at com.linecorp.armeria.client.DecodedHttpResponse.write(DecodedHttpResponse.java:52)
	at com.linecorp.armeria.client.HttpResponseDecoder$HttpResponseWrapper.write(HttpResponseDecoder.java:201)
	at com.linecorp.armeria.client.Http1
```

**Comment by imasahiro** [comment]
Just remember that because armeria uses Http1 pipelining by default and some servers does not support, it causes unexpected slowness when sending requests to http1 servers.

If I disable http1 pipelining, the number become much better.
```java
HttpClient client = new HttpClientBuilder("http://127.0.0.1:9998")
        .factory(new ClientFactoryBuilder()
                         .useHttp1Pipelining(false)
                         .build())
        .build();
ServerBuilder sb =  new ServerBuilder().port(20080, SessionProtocol.HTTP).defaultRequestTimeoutMillis(0);
sb.service("/no-pipe", (HttpService) (ctx, req) -> client.execute(req));
sb.build().start().join();
```

```
$ ab  -n 1000 -c 100 http://localhost:20080/no-pipe
...
Percentage of the requests served within a certain time (ms)
  50%   2011
  66%   2013
  75%   2014
  80%   2015
  90%   2021
  95%   2024
  98%   2028
  99%   2030
 100%   2036 (longest request)
```

**Comment by anuraaga** [comment]
Nice find! AFAIK, most clients, including browsers, don't enable pipelining by default since many servers don't work well with it. Any thoughts on changing the default in armeria to false?

**Comment by huydx** [comment]
In this case, it's obviously that disable http pipeline make throughput much better. However AFAIK, golang http server enable Http 1.1/pipeline by default for idempotent request (GET), so we have pipeline upstream + pipeline client, so it should make request faster right?

**Comment by huydx** [comment]
Btw, the final result with pipelining is satisfied, so I'm gonna close this issue and get further investigation with golang server / armeria client to see why pipelining did not works as different issue. 
Thanks @imasahiro @anuraaga and @trustin for your helps

**Comment by trustin** [comment]
> the final result with pipelining is satisfied

Did you mean 'without'?

**Comment by huydx** [comment]
yes, my typo -.-, I mean without, as @imasahiro pointed out

**Comment by sidhant92** [comment]
@huydx @trustin , I am facing the same issue but I am using Armeria as the server and ab as the client. When I enable -K in ab the response is very slow with armeria.

I am using Armeria with Dropwizard, the default Jetty server works just fine.
