### ISSUE TITLE
Flaky test: AnnotatedHttpServiceExceptionHandlerTest > testExceptionHandler

### ISSUE THREAD

**Issue by hyangtack** [line/armeria#977]
```
com.linecorp.armeria.server.AnnotatedHttpServiceExceptionHandlerTest > testExceptionHandler FAILED
    org.junit.ComparisonFailure: expected:<[400 Bad Request]> but was:<[503 Service Unavailable]>
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at com.linecorp.armeria.server.AnnotatedHttpServiceExceptionHandlerTest.testExceptionHandler(AnnotatedHttpServiceExceptionHandlerTest.java:249)
```

**Comment by trustin** [comment]
Didn't see this failure quite a while.
